import {resolve} from "node:path";
import {beforeAll,describe,expect,it} from "vitest";
import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";
import type {LoadedRuleset} from "../ruleset/types.js";
import {runAutomaticScheduler} from "../engine/automaticScheduler.js";
import {createInitialSetup,resolveInitialRedraw} from "../engine/setup.js";
import type {AuthoritativeGameState,Seat} from "../engine/state.js";
import {GameService} from "./gameService.js";
import {GameProjector} from "./projection.js";
import {playOffers,type RawPlayOffer} from "./playRegistry.js";
import {validateProtocol} from "./protocol.js";
import type {AppRoom,AppSettings,AppUser} from "./types.js";

let ruleset:LoadedRuleset;
const settings:AppSettings={roomName:"BOSS使用",allowGuests:true,allowSpectators:false,turnTimeSeconds:60,responseTimeSeconds:20,reserveTimeSeconds:30,rulesetVersion:"1.3.4",dismantleBossEnabled:true};
const users:Record<Seat,AppUser>={1:{userId:"u1",displayName:"一"},2:{userId:"u2",displayName:"二"},3:{userId:"u3",displayName:"三"},4:{userId:"u4",displayName:"四"}};
beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function openedState(seed=301):AuthoritativeGameState{let state=createInitialSetup(ruleset,{gameId:`boss-play-${seed}`,firstSeat:1,seed,usersBySeat:{1:users[1]!.userId,2:users[2]!.userId,3:users[3]!.userId,4:users[4]!.userId},characterIdsBySeat:{1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as Seat[])state=resolveInitialRedraw(state,seat,false,ruleset).state;const scheduled=runAutomaticScheduler(state,ruleset,()=>21000);state=scheduled.state;if(state.phase!=="play")throw new Error(`expected play phase, got ${state.phase}`);return state;}
function moveCard(state:AuthoritativeGameState,cardRef:string,toZoneRef:string,owner:Seat=1){const card=state.cards[cardRef]!,from=state.zones[card.zoneRef]!,index=from.orderedCardRefs.indexOf(cardRef);if(index<0)throw new Error("card not in source zone");from.orderedCardRefs.splice(index,1);const to=state.zones[toZoneRef]!;to.orderedCardRefs.push(cardRef);card.zoneRef=toZoneRef;card.ownerSeat=to.ownerSeat??owner;card.controllerSeat=to.ownerSeat??owner;card.faceUp=!toZoneRef.startsWith("hand:");}
function makeRoom(state:AuthoritativeGameState):AppRoom{return{roomId:state.gameId,roomCode:"BOSS",revision:1,phase:"inGame",settings,passwordHash:null,players:state.players.map(player=>({userId:player.userId,displayName:users[player.seat]!.displayName,seat:player.seat,team:player.team,isHost:player.seat===1,ready:true,connection:"online",latencyMs:null,selectionState:"revealed",candidates:[],preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:null})),spectators:[],chat:[],gameChat:[],game:state,createdAt:0,updatedAt:0};}
function snapshotValid(room:AppRoom,userId:string){expect(validateProtocol("game",new GameProjector(ruleset).game(room,userId))).toEqual({ok:true});}
function bossRef(state:AuthoritativeGameState,templateId:string):string{const ref=Object.values(state.cards).find(card=>card.templateId===templateId)?.cardRef;if(!ref)throw new Error(`boss ${templateId} not in state`);return ref;}
function bossOffers(state:AuthoritativeGameState):RawPlayOffer[]{return playOffers(state,ruleset,1,"u1",()=>Date.now()+20000).filter(o=>o.offerId.includes("boss-use"));}
function submit(room:AppRoom,service:GameService,offerId:string,selections:Record<string,Array<string|number|boolean>>,commandId:string){const before=room.game!.stateRevision,command={type:"GAME_COMMAND",commandId,gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER",payload:{selections}};const first=service.handle(room,users[1]!,command);expect(first.accepted).toBe(true);expect(service.handle(room,users[1]!,command)).toEqual(first);expect(room.game!.stateRevision).toBeGreaterThan(before);snapshotValid(room,"u1");return first;}

describe("playRegistry BOSS 使用",()=>{
 it("持续型 BOSS：出牌阶段对持有者产生使用报价",()=>{let state=openedState(301);const boss=bossRef(state,"boss.purple_lord");moveCard(state,boss,"hand:1");const offers=bossOffers(state),offer=offers.find(o=>o.cardRef===boss);expect(offer,`缺少 BOSS 使用报价（当前报价:${offers.map(o=>o.offerId).join(",")}）`).toBeTruthy();expect(offer!.kind).toBe("useCard");});
 it("持续型 BOSS：GameService 端到端使用成功、占用 BOSS 槽并记录全局回合额度",()=>{let state=openedState(302);const boss=bossRef(state,"boss.purple_lord");moveCard(state,boss,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=bossOffers(state).find(o=>o.cardRef===boss)!;submit(room,service,raw.offerId,{},"boss-use-302");expect(room.game!.zones[`boss:1`]!.orderedCardRefs).toContain(boss);expect(room.game!.zones[`hand:1`]!.orderedCardRefs).not.toContain(boss);expect(room.game!.players.find(p=>p.seat===1)!.markers["boss.lastUsedGlobalTurn"]).toBeDefined();});
 it("持续型 BOSS：BOSS 槽被占用时不再报价",()=>{let state=openedState(303);const boss=bossRef(state,"boss.purple_lord");moveCard(state,boss,"boss:1",1);const other=bossRef(state,"boss.red_lord");moveCard(state,other,"hand:1");const offers=bossOffers(state);expect(offers.find(o=>o.cardRef===other),"槽被占用时仍报价了 BOSS").toBeUndefined();});
 it("持续型 BOSS：同一全局回合已使用后不再报价",()=>{let state=openedState(304);const boss=bossRef(state,"boss.purple_lord");moveCard(state,boss,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=bossOffers(state).find(o=>o.cardRef===boss)!;submit(room,service,raw.offerId,{},"boss-use-304");expect(bossOffers(room.game!).length,"同回合重复报价了 BOSS").toBe(0);});
 it("瓦尔基里（即时型）不产生普通使用报价（只能响应他人 BOSS 使用）",()=>{let state=openedState(305);const boss=bossRef(state,"boss.valkyrie");moveCard(state,boss,"hand:1");expect(bossOffers(state).length).toBe(0);});
 it("非 BOSS 手牌不产生 BOSS 使用报价",()=>{let state=openedState(306);const offers=bossOffers(state);expect(offers.length).toBe(0);});
 it("C6H8O6：出牌阶段可发起定点轰击（选择 family 与距离1内目标）",()=>{let state=openedState(307);const c6=bossRef(state,"boss.c6h8o6");moveCard(state,c6,"hand:1");const offers=bossOffers(state),offer=offers.find(o=>o.offerId.includes("c6-bomb")&&o.cardRef===c6);expect(offer,`缺少 C6 定点轰击报价（当前报价:${offers.map(o=>o.offerId).join(",")}）`).toBeTruthy();expect((offer as RawPlayOffer & {modeOptions?:string[]}).modeOptions).toEqual(["kill","dodge"]);const room=makeRoom(state),service=new GameService(ruleset,()=>1000),projected=(new GameProjector(ruleset).game(room,"u1") as any).interaction.offers.find((o:any)=>o.offerId===offer!.offerId)!;const spec=(projected.selectionSpecs as any[]).find((s:any)=>s.kind==="option");expect(spec,`C6 报价缺少 family 选项规格:${JSON.stringify(projected.selectionSpecs)}`).toBeTruthy();expect(spec!.options).toEqual(["kill","dodge"]);submit(room,service,offer!.offerId,{targets:["public:seat_2"],mode:["dodge"]},"c6-use-307");expect(room.game!.zones[`boss:1`]!.orderedCardRefs).toContain(c6);expect(room.game!.cards[c6]!.runtime.modeId).toBe("focusedBombardment");});
 it("C6H8O6：出牌阶段可发起激光扫射（选择 family、即时型不占槽）",()=>{let state=openedState(311);const c6=bossRef(state,"boss.c6h8o6");moveCard(state,c6,"hand:1");const offers=bossOffers(state),offer=offers.find(o=>o.offerId.includes("c6-sweep")&&o.cardRef===c6);expect(offer,`缺少 C6 激光扫射报价（当前报价:${offers.map(o=>o.offerId).join(",")}）`).toBeTruthy();const room=makeRoom(state),service=new GameService(ruleset,()=>1000),limitId=ruleset.settings.combat.attackCountLimitId,countBefore=Number(room.game!.players.find(p=>p.seat===1)!.limits[limitId]??0);submit(room,service,offer!.offerId,{mode:["kill"]},"c6-sweep-311");expect(room.game!.zones.resolving!.orderedCardRefs).toContain(c6);expect(room.game!.zones[`boss:1`]!.orderedCardRefs,"激光扫射是即时型，不应占 BOSS 槽").not.toContain(c6);expect(Number(room.game!.players.find(p=>p.seat===1)!.limits[limitId]??0)).toBe(countBefore-1);expect(room.game!.pendingWindows[0]!.kind).toBe("c6LaserSweepRequest");expect(room.game!.players.find(p=>p.seat===1)!.markers["boss.lastUsedGlobalTurn"]).toBeDefined();});
 it("持续型 BOSS：stale revision 拒绝且不污染状态",()=>{let state=openedState(308);const boss=bossRef(state,"boss.purple_lord");moveCard(state,boss,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=bossOffers(state).find(o=>o.cardRef===boss)!,before=room.game!.stateRevision;const stale=service.handle(room,users[1]!,{type:"GAME_COMMAND",commandId:"boss-stale",gameId:room.game!.gameId,expectedStateRevision:before-1,promptId:room.game!.pendingWindows[0]!.promptId,offerId:raw.offerId,command:"EXECUTE_OFFER",payload:{selections:{}}});expect(stale.accepted).toBe(false);expect((stale as any).reasonCode).toBe("STALE_REVISION");expect(room.game!.stateRevision).toBe(before);expect(room.game!.zones[`hand:1`]!.orderedCardRefs).toContain(boss);});
 it("持续型 BOSS 与 C6 共享每全局回合额度：先使用持续型后 C6 不再报价",()=>{let state=openedState(309);const boss=bossRef(state,"boss.purple_lord"),c6=bossRef(state,"boss.c6h8o6");moveCard(state,boss,"hand:1");moveCard(state,c6,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=bossOffers(state).find(o=>o.cardRef===boss)!;submit(room,service,raw.offerId,{},"boss-use-309");expect(bossOffers(room.game!).filter(o=>o.cardRef===c6),"同回合仍报价了 C6").toHaveLength(0);});
 it("C6 使用：非法 family 被拒绝且零污染",()=>{let state=openedState(310);const c6=bossRef(state,"boss.c6h8o6");moveCard(state,c6,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=bossOffers(state).find(o=>o.cardRef===c6)!,before=room.game!.stateRevision;const out=service.handle(room,users[1]!,{type:"GAME_COMMAND",commandId:"c6-bad-family",gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId:raw.offerId,command:"EXECUTE_OFFER",payload:{selections:{targets:["public:seat_2"],mode:["steal"]}}});expect(out.accepted).toBe(false);expect(room.game!.stateRevision).toBe(before);expect(room.game!.zones[`hand:1`]!.orderedCardRefs).toContain(c6);});
});
