import {resolve} from "node:path";
import {beforeAll,describe,expect,it} from "vitest";
import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";
import type {LoadedRuleset} from "../ruleset/types.js";
import {runAutomaticScheduler} from "../engine/automaticScheduler.js";
import {createInitialSetup,resolveInitialRedraw} from "../engine/setup.js";
import {setWeaponPreselection} from "../engine/preselection.js";
import type {AuthoritativeGameState,Seat} from "../engine/state.js";
import {GameService} from "./gameService.js";
import {GameProjector} from "./projection.js";
import {playOffers,type RawPlayOffer} from "./playRegistry.js";
import {validateProtocol} from "./protocol.js";
import type {AppRoom,AppSettings,AppUser} from "./types.js";

let ruleset:LoadedRuleset;
const settings:AppSettings={roomName:"注册表全量",allowGuests:true,allowSpectators:false,turnTimeSeconds:60,responseTimeSeconds:20,reserveTimeSeconds:30,rulesetVersion:"1.3.4",dismantleBossEnabled:true};
const users:Record<Seat,AppUser>={1:{userId:"u1",displayName:"一"},2:{userId:"u2",displayName:"二"},3:{userId:"u3",displayName:"三"},4:{userId:"u4",displayName:"四"}};
beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function openedState(seed=201,seat1="character.knight"):AuthoritativeGameState{let state=createInitialSetup(ruleset,{gameId:`registry-full-${seed}`,firstSeat:1,seed,usersBySeat:{1:users[1]!.userId,2:users[2]!.userId,3:users[3]!.userId,4:users[4]!.userId},characterIdsBySeat:{1:seat1,2:"character.alchemist",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as Seat[])state=resolveInitialRedraw(state,seat,false,ruleset).state;const scheduled=runAutomaticScheduler(state,ruleset,()=>21000);state=scheduled.state;if(state.phase!=="play")throw new Error(`expected play phase, got ${state.phase}`);return state;}
function refsByTemplate(state:AuthoritativeGameState,prefix:string):string[]{return Object.values(state.cards).filter(card=>card.templateId.startsWith(prefix)).map(card=>card.cardRef);}
function moveCard(state:AuthoritativeGameState,cardRef:string,toZoneRef:string,owner:Seat=1){const card=state.cards[cardRef]!,from=state.zones[card.zoneRef]!,index=from.orderedCardRefs.indexOf(cardRef);if(index<0)throw new Error("card not in source zone");from.orderedCardRefs.splice(index,1);const to=state.zones[toZoneRef]!;to.orderedCardRefs.push(cardRef);card.zoneRef=toZoneRef;card.ownerSeat=to.ownerSeat??owner;card.controllerSeat=to.ownerSeat??owner;card.faceUp=!toZoneRef.startsWith("hand:");}
function makeRoom(state:AuthoritativeGameState):AppRoom{return{roomId:state.gameId,roomCode:"FULL",revision:1,phase:"inGame",settings,passwordHash:null,players:state.players.map(player=>({userId:player.userId,displayName:users[player.seat]!.displayName,seat:player.seat,team:player.team,isHost:player.seat===1,ready:true,connection:"online",latencyMs:null,selectionState:"revealed",candidates:[],preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:null})),spectators:[],chat:[],gameChat:[],game:state,createdAt:0,updatedAt:0};}
function snapshotValid(room:AppRoom,userId:string){expect(validateProtocol("game",new GameProjector(ruleset).game(room,userId))).toEqual({ok:true});}
function offerFor(state:AuthoritativeGameState,match:(o:RawPlayOffer)=>boolean):RawPlayOffer{const offers=playOffers(state,ruleset,1,"u1",()=>Date.now()+20000),found=offers.find(match);if(!found)throw new Error(`offer not found; got ${offers.map(o=>o.offerId).join(",")}`);return found;}
function selectionsFor(raw:RawPlayOffer,projected:any,overrides?:Record<string,Array<string|number|boolean>>):Record<string,Array<string|number|boolean>>{const selections:Record<string,Array<string|number|boolean>>={};for(const spec of (projected.selectionSpecs??[]) as any[]){const refs=spec.legalRefs??[];if(spec.kind==="cards"&&refs.length)selections[spec.key]=[refs[0]!];if(spec.kind==="targets"&&refs.length)selections[spec.key]=[refs[0]!];if(spec.kind==="option"&&spec.options?.length)selections[spec.key]=[spec.options[0]!];}if(!Object.keys(selections).length&&raw.cardRef)selections.cards=[`private:u1:${raw.cardRef}`];if(overrides)for(const [k,v] of Object.entries(overrides))selections[k]=v;return selections;}
function projectedOffer(room:AppRoom,offerId:string){const snap=new GameProjector(ruleset).game(room,"u1") as any;return (snap.interaction.offers as any[]).find((o:any)=>o.offerId===offerId)??(snap.interaction.offers as any[])[0]!;}
function submit(room:AppRoom,service:GameService,offerId:string,selections:Record<string,Array<string|number|boolean>>,commandId:string){const before=room.game!.stateRevision,command={type:"GAME_COMMAND",commandId,gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER",payload:{selections}};const first=service.handle(room,users[1]!,command);expect(first.accepted).toBe(true);expect(service.handle(room,users[1]!,command)).toEqual(first);expect(room.game!.stateRevision).toBeGreaterThan(before);snapshotValid(room,"u1");return first;}
function rejectStaleAndInvalid(room:AppRoom,service:GameService,offerId:string,commandId:string){const before=room.game!.stateRevision,stale=service.handle(room,users[1]!,{type:"GAME_COMMAND",commandId:`${commandId}-stale`,gameId:room.game!.gameId,expectedStateRevision:before-1,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER",payload:{selections:{}}});expect(stale.accepted).toBe(false);expect((stale as any).reasonCode).toBe("STALE_REVISION");const invalid=service.handle(room,users[1]!,{type:"GAME_COMMAND",commandId:`${commandId}-invalid`,gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER",payload:{selections:{cards:["public:missing"]}}});expect(invalid.accepted).toBe(false);expect(room.game!.stateRevision).toBe(before);}

describe("playRegistry full entry acceptance",()=>{
 it("mount equip: offer, project, execute, idempotent, zero pollution",()=>{let state=openedState(201);const mount=refsByTemplate(state,"mount.")[0]!;moveCard(state,mount,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("mount-equip")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected),"mount-equip-1");rejectStaleAndInvalid(room,service,raw.offerId,"mount-equip-x");expect(room.game!.zones[`hand:1`]!.orderedCardRefs).not.toContain(raw.cardRef);expect(Object.values(room.game!.zones).some(zone=>zone.zoneRef.startsWith("mountOffense:")||zone.zoneRef.startsWith("mountDefense:"))).toBe(true);});
 it("mount discard: offer after equip, execute and move to discard",()=>{let state=openedState(202);const mount=refsByTemplate(state,"mount.")[0]!;moveCard(state,mount,"mountOffense:1",1);const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("mount-discard"));submit(room,service,raw.offerId,{cards:[`private:u1:${mount}`]},"mount-discard-1");expect(room.game!.zones.discardPile!.orderedCardRefs).toContain(mount);});
 it("talent equip: offer, execute, and unequip guard",()=>{let state=openedState(203);const talent=refsByTemplate(state,"talent.")[0]!;moveCard(state,talent,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("talent-equip"));submit(room,service,raw.offerId,{cards:[`private:u1:${raw.cardRef}`]},"talent-equip-1");expect(room.game!.zones[`talent:1`]!.orderedCardRefs).toContain(raw.cardRef);});
 it("talent discard: offer after equip and execute",()=>{let state=openedState(204);const talent=refsByTemplate(state,"talent.")[0]!;moveCard(state,talent,"talent:1",1);const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("talent-discard"));submit(room,service,raw.offerId,{cards:[`private:u1:${talent}`]},"talent-discard-1");expect(room.game!.zones.discardPile!.orderedCardRefs).toContain(talent);});
 it("death note special.sp04: use with a legal target",()=>{let state=openedState(205);const card=refsByTemplate(state,"special.sp04")[0]!;moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp04")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_2"]}),"sp04-1");rejectStaleAndInvalid(room,service,raw.offerId,"sp04-x");expect(room.game!.zones.discardPile!.orderedCardRefs).toContain(card);});
 it("horn squad special.sp07: use and execute",()=>{let state=openedState(206);const card=refsByTemplate(state,"special.sp07")[0]!;moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp07")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected),"sp07-1");});
 it("blood altar special.sp11: use and execute",()=>{let state=openedState(207);const card=refsByTemplate(state,"special.sp11")[0]!;moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp11")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_1"]}),"sp11-1");});
 it("priest pray: red hand card cost and fixed recovery",()=>{let state=openedState(208,"character.priest");const red=Object.values(state.cards).find(card=>{const fact=(ruleset.documents.get("cards.json") as {items:Array<{cardId:string;color:string}>}).items.find(x=>x.cardId===card.templateId);return fact?.color==="red";})!;moveCard(state,red.cardRef,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("priest.pray")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected),"priest-pray-1");rejectStaleAndInvalid(room,service,raw.offerId,"priest-x");});
 it("offering pool special.sp10: pay an equipped weapon with confirm",()=>{let state=openedState(209);const weapon=refsByTemplate(state,"weapon.")[0]!,pool=refsByTemplate(state,"special.sp10")[0]!;moveCard(state,weapon,"weapon:1:1");moveCard(state,pool,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp10")),projected=projectedOffer(room,raw.offerId);expect(projected.selectionSpecs.some((s:any)=>s.kind==="confirm")).toBe(true);submit(room,service,raw.offerId,selectionsFor(raw,projected,{weapons:[`private:u1:${weapon}`],confirm:[true]}),"sp10-1");});
 it("assassin creed kill: same-color pair cost and legal target",()=>{let state=openedState(210,"character.assassin");state=setWeaponPreselection(state,1,"weapon:1:1",null,ruleset).state;const kills=refsByTemplate(state,"basic.kill.");const sameColor=kills.filter(ref=>state.cards[ref]!.templateId===state.cards[kills[0]!]!.templateId).slice(0,2);for(const ref of sameColor)moveCard(state,ref,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("creed_kill")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{cards:sameColor.map(ref=>`private:u1:${ref}`),targets:["public:seat_2"]}),"creed-kill-1");expect(room.game!.players.find(p=>p.seat===1)!.markers["assassin.creedKillUsed"]).toBe(true);});
 it("qi ball: two hand cards and a target, attack count consumed",()=>{let state=openedState(211,"character.qi_master");const cards=[...state.zones["hand:1"]!.orderedCardRefs].slice(0,2);const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("skill.qi_master")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{cards:cards.map(ref=>`private:u1:${ref}`),targets:["public:seat_2"]}),"qi-ball-1");rejectStaleAndInvalid(room,service,raw.offerId,"qi-x");});
 it("necromancer mark: offer and legal target",()=>{let state=openedState(212,"character.necromancer");state.players.find(p=>p.seat===1)!.markers["necromancer.energy"]=8;const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("necromancer.mark")),projected=projectedOffer(room,raw.offerId);const command={type:"GAME_COMMAND",commandId:"necro-mark-1",gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId:raw.offerId,command:"EXECUTE_OFFER",payload:{selections:{targets:["public:seat_2"]}}};const first=service.handle(room,users[1]!,command);expect(first.accepted).toBe(true);});
 it("robot overload: discards required hand cards and fires",()=>{let state=openedState(213,"character.robot");const hand=[...state.zones["hand:1"]!.orderedCardRefs],room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("robot.energy_overload")),projected=projectedOffer(room,raw.offerId),spec=(projected.selectionSpecs as any[]).find((s:any)=>s.kind==="cards");submit(room,service,raw.offerId,{cards:hand.slice(0,spec?.min??1).map((ref:string)=>`private:u1:${ref}`)},"robot-overload-1");});
 it("elementalist frozen satchel: no card cost, legal target",()=>{let state=openedState(214,"character.ancient_elementalist");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes(":frozen:")),projected=projectedOffer(room,raw.offerId);const command={type:"GAME_COMMAND",commandId:"element-frozen-1",gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId:raw.offerId,command:"EXECUTE_OFFER",payload:{selections:{}}};const first=service.handle(room,users[1]!,command);if(!first.accepted)console.log("ELEMENT_DIAG",JSON.stringify({offerId:raw.offerId,targetRef:raw.targetRef,reason:first}));expect(first.accepted).toBe(true);});
 it("internet addiction sp01: play against a target",()=>{let state=openedState(215);const card=refsByTemplate(state,"special.sp01")[0]!;moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp01")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_2"]}),"sp01-1");});
 it("super baby sp09: play against a target",()=>{let state=openedState(216);const card=refsByTemplate(state,"special.sp09")[0]!;moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp09")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_2"]}),"sp09-1");});
 it("statue play: use a statue card from hand",()=>{let state=openedState(217);const card=refsByTemplate(state,"statue.")[0]!;moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("statue-play")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected),"statue-play-1");expect(room.game!.zones.resolving!.orderedCardRefs).toContain(raw.cardRef);});
 it("werewolf notebook: five-color hand cost",()=>{let state=openedState(218,"character.werewolf");const colors=["white","green","blue","orange","red"],facts=(ruleset.documents.get("cards.json") as {items:Array<{cardId:string;color:string}>}).items,five:string[]=[];for(const color of colors){const id=facts.find(x=>x.color===color)!.cardId,card=Object.values(state.cards).find(c=>c.templateId===id&&!five.includes(c.cardRef)&&!state.zones["hand:1"]!.orderedCardRefs.includes(c.cardRef))!;five.push(card.cardRef);moveCard(state,card.cardRef,"hand:1");}const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("werewolf.notebook"));submit(room,service,raw.offerId,{cards:five.map(ref=>`private:u1:${ref}`),targets:["public:seat_2"]},"werewolf-1");rejectStaleAndInvalid(room,service,raw.offerId,"werewolf-x");});
 it("general mortar: no-cost area barrage",()=>{let state=openedState(219,"character.general");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("general.mortar"));const command={type:"GAME_COMMAND",commandId:"general-mortar-1",gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId:raw.offerId,command:"EXECUTE_OFFER",payload:{selections:{}}};const first=service.handle(room,users[1]!,command);expect(first.accepted).toBe(true);expect(room.game!.history.domainEvents.some(x=>x.eventType==="effect.scheduled"&&String((x.payload as any)?.scheduledId).includes("general-mortar"))).toBe(true);});
 it("origin furnace sp06: discard an equipped weapon and draw",()=>{let state=openedState(220);const weapon=refsByTemplate(state,"weapon.")[0]!,card=refsByTemplate(state,"special.sp06")[0]!;moveCard(state,weapon,"weapon:1:1");moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp06")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{weapons:[`private:u1:${weapon}`]}),"sp06-1");expect(room.game!.zones.discardPile!.orderedCardRefs).toContain(weapon);});
 it("trap master bomber: discard hand cards into bombs",()=>{let state=openedState(221,"character.trap_master");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("trap_master")),projected=projectedOffer(room,raw.offerId),hand=[...state.zones["hand:1"]!.orderedCardRefs].slice(0,1);submit(room,service,raw.offerId,{cards:hand.map(ref=>`private:u1:${ref}`)},"bomber-1");expect(Number(room.game!.players.find(p=>p.seat===1)!.markers["trap.bombs"]??0)).toBeGreaterThan(0);});
 it("engineer mech attack: active mech fires",()=>{let state=openedState(222,"character.engineer");state.players.find(p=>p.seat===1)!.markers["engineer.mechActive"]=true;state.players.find(p=>p.seat===1)!.markers["engineer.mechKind"]="prototype";const kill=refsByTemplate(state,"basic.kill.")[0]!;moveCard(state,kill,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("engineer-mech-attack")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_2"]}),"mech-attack-1");});
 it("demolition team sp08: use with equipped weapons",()=>{let state=openedState(223);const weapon=refsByTemplate(state,"weapon.")[0]!,card=refsByTemplate(state,"special.sp08")[0]!;moveCard(state,weapon,"weapon:1:1");moveCard(state,card,"hand:1");const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("special.sp08")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected),"sp08-1");});
});
