import type {LoadedRuleset} from "../ruleset/types.js";
import {projectSetupView} from "../engine/setupCommands.js";
import type {AuthoritativeGameState,Seat} from "../engine/state.js";
import type {JsonValue} from "../engine/types.js";
import type {AppRoom,AppUser} from "./types.js";
import {playOffers,type RawPlayOffer} from "./playRegistry.js";

type CardFact={cardId:string;displayName:string;category:string;color:string;resourceKey:string};
type CharacterFact={characterId:string;displayName:string;maxHp:number;maxShield:number;initialTalentIds:string[];skillIds:string[]};
const publicCardRef=(ref:string)=>`public:${ref}`,privateCardRef=(userId:string,ref:string)=>`private:${userId}:${ref}`;
export function internalRef(ref:string){if(ref.startsWith("public:seat_"))return`character:${ref.slice(12)}`;if(ref.startsWith("public:"))return ref.slice(7);if(ref.startsWith("private:")){const parts=ref.split(":");return parts.slice(2).join(":");}return ref;}
export function roomProjection(room:AppRoom,user:AppUser,ruleset:LoadedRuleset){const viewer=room.players.find(x=>x.userId===user.userId),isHost=viewer?.isHost===true,chars=new Map((ruleset.documents.get("characters.json") as {items:CharacterFact[]}).items.map(x=>[x.characterId,x]));return{type:"ROOM_SNAPSHOT",roomId:room.roomId,roomCode:room.roomCode,roomRevision:room.revision,serverTime:Date.now(),phase:room.phase,settings:room.settings,players:room.players.map(p=>({userId:p.userId,displayName:p.displayName,seat:p.seat,team:p.team,isHost:p.isHost,ready:p.ready,connection:p.connection,latencyMs:p.latencyMs,selectionState:p.selectionState,...(p.selectionState==="revealed"?{revealedCharacterId:p.lockedCharacterId}:{})})),viewerUserId:user.userId,viewerSeat:viewer?.seat??null,permissions:{canChangeSeat:isHost&&room.phase==="waiting",canUpdateSettings:isHost&&room.phase==="waiting",canKick:isHost,canTransferHost:isHost,canStartGame:isHost&&room.phase==="waiting",canCloseRoom:isHost},characterSelection:viewer&&room.phase==="characterSelection"?{candidates:viewer.candidates.map(id=>{const c=chars.get(id)!;return{characterId:id,displayName:c.displayName,portraitResourceKey:`character.${id}`,initialHp:c.maxHp,initialShield:c.maxShield,initialTalentId:c.initialTalentIds[0]??"",abilityIds:c.skillIds,difficulty:1}}),preselectedCharacterId:viewer.preselectedCharacterId,lockedCharacterId:viewer.lockedCharacterId,deadlineAt:viewer.selectionDeadlineAt}:null,chat:visibleChat(room.chat,viewer?.team??null)};}
export function lobbyProjection(user:AppUser,rooms:Iterable<AppRoom>){return{type:"LOBBY_SNAPSHOT",serverTime:Date.now(),user:{userId:user.userId,displayName:user.displayName,latencyMs:null},rulesetVersions:["1.3.4"],resumableGames:[...rooms].filter(r=>r.phase==="inGame"&&r.players.some(p=>p.userId===user.userId)).map(r=>({gameId:r.game?.gameId??"",roomCode:r.roomCode,round:r.game?.round??0,statusText:"对局进行中"}))};}
function visibleChat(chat:AppRoom["chat"],team:string|null){return chat.filter(x=>x.channel==="all"||(team&&((x.senderSeat===1||x.senderSeat===4?"A":"B")===team))).map(({clientMessageId,...x})=>x);}
function visibleGameChat(chat:AppRoom["gameChat"],team:string|null){return chat.filter(x=>x.channel==="all"||(team&&((x.senderSeat===1||x.senderSeat===4?"A":"B")===team))).map(({clientMessageId,senderDisplayName,...x})=>x);}
function life(p:AuthoritativeGameState["players"][number]){if(p.lifeState==="eliminated")return"eliminated";if(p.lifeState==="deadNotEliminated")return"deadNotEliminated";if(p.presence==="leftPlay")return"leftPlay";return"inPlay";}
export class GameProjector{
 private cards:Map<string,CardFact>;constructor(private r:LoadedRuleset){this.cards=new Map((r.documents.get("cards.json") as {items:CardFact[]}).items.map(x=>[x.cardId,x]));}
 setup(state:AuthoritativeGameState,userId:string){return projectSetupView(state,userId,this.r).protocolMessage;}
 private card(state:AuthoritativeGameState,ref:string,scope:"public"|"private",userId:string){const instance=state.cards[ref]!,fact=this.cards.get(instance.templateId)??{cardId:instance.templateId,displayName:instance.templateId,category:instance.templateId.split(".")[0]!,color:"none",resourceKey:`card.${instance.templateId}`},runtime=instance.runtime,charge=Object.entries(runtime).find(([k,v])=>k.toLowerCase().includes("charge")&&typeof v==="number")?.[1],durability=runtime.durabilityCurrent,cooldown=runtime.cooldownRemaining;return{ref:scope==="public"?publicCardRef(ref):privateCardRef(userId,ref),templateId:fact.cardId,displayName:fact.displayName,category:fact.category,printedColor:fact.color??"none",resourceKey:fact.resourceKey,summary:"",coreStats:[],badges:[],state:{effective:true,selected:false,...(typeof charge==="number"?{charge}:{}),...(typeof durability==="number"?{durability}:{}),...(typeof cooldown==="number"?{cooldown}:{})},detailAvailable:true};}
 game(room:AppRoom,userId:string){const state=room.game!,viewer=state.players.find(x=>x.userId===userId)!;if(state.lifecycle==="setupRedraw")return this.setup(state,userId);const card=(ref:string,scope:"public"|"private"="public")=>this.card(state,ref,scope,userId),zone=(ref:string)=>state.zones[ref]?.orderedCardRefs??[],slots=(seat:Seat)=>({weapon1:zone(`weapon:1:${seat}`)[0]?card(zone(`weapon:1:${seat}`)[0]!):null,weapon2:zone(`weapon:2:${seat}`)[0]?card(zone(`weapon:2:${seat}`)[0]!):null,thirdWeapon:zone(`thirdWeapon:${seat}`)[0]?card(zone(`thirdWeapon:${seat}`)[0]!):null,armor:zone(`armor:${seat}`)[0]?card(zone(`armor:${seat}`)[0]!):null,mountOffense:zone(`mountOffense:${seat}`)[0]?card(zone(`mountOffense:${seat}`)[0]!):null,mountDefense:zone(`mountDefense:${seat}`)[0]?card(zone(`mountDefense:${seat}`)[0]!):null,talents:zone(`talent:${seat}`).map(x=>card(x)),boss:zone(`boss:${seat}`)[0]?card(zone(`boss:${seat}`)[0]!):null}),players=state.players.map(p=>{const equipmentSlots=slots(p.seat),equipment=[equipmentSlots.weapon1,equipmentSlots.weapon2,equipmentSlots.thirdWeapon,equipmentSlots.armor,equipmentSlots.mountOffense,equipmentSlots.mountDefense,...equipmentSlots.talents,equipmentSlots.boss].filter(Boolean);return{seat:p.seat,team:p.team,nickname:room.players.find(x=>x.seat===p.seat)?.displayName??`玩家${p.seat}`,connected:room.players.find(x=>x.seat===p.seat)?.connection==="online",characterId:p.characterId,lifeState:life(p),hp:p.hp,maxHp:p.maxHp,shield:p.shield,maxShield:p.maxShield,ironShield:p.ironShield,handCount:zone(`hand:${p.seat}`).length,equipment,equipmentSlots,judgmentZone:zone(`judgment:${p.seat}`).map(x=>card(x)),statuses:p.statuses.map(x=>x.statusId)};}),window=state.pendingWindows.find(x=>x.prioritySeat===viewer.seat),interaction=this.interaction(state,viewer.seat,userId,window),pre=state.preselection[viewer.seat];return{type:"GAME_SNAPSHOT",gameId:state.gameId,rulesetVersion:"1.3.4",stateRevision:state.stateRevision,lastEventSeq:state.lastEventSeq,serverTime:Date.now(),viewer:{userId,seat:viewer.seat,team:viewer.team},publicView:{round:state.round,activeSeat:state.activeSeat??viewer.seat,phase:state.phase??"prepare",players,drawPileCount:zone("drawPile").length,discardTop:zone("discardPile").slice(-5).map(x=>card(x)),centralCards:zone("resolving").filter(x=>state.cards[x]!.faceUp).map(x=>card(x)),headline:state.lifecycle==="ended"?"对局结束":undefined,winnerTeam:state.winnerTeam},privateView:{hand:zone(`hand:${viewer.seat}`).map(x=>card(x,"private")),preselectedWeaponSlot:pre.weaponSlot,preselectedModeId:pre.modeId,preselectableWeaponSlots:[`weapon:1:${viewer.seat}`,`weapon:2:${viewer.seat}`,`weapon:3:${viewer.seat}`,`thirdWeapon:${viewer.seat}`],concealedChoices:this.concealed(window)},interaction,chat:visibleGameChat(room.gameChat,viewer.team)};}
 private concealed(window:AuthoritativeGameState["pendingWindows"][number]|undefined){const count=Number(window?.context?.hiddenCardCount??0);return Array.from({length:count},(_,i)=>`concealed:${window!.promptId}:${i}`);}
 private interaction(state:AuthoritativeGameState,seat:Seat,userId:string,window:AuthoritativeGameState["pendingWindows"][number]|undefined){if(!window)return{prompt:null,offers:[],disabledHints:[]};const offers=window.kind==="playPhaseAction"?[...playOffers(state,this.r,seat,userId,()=>window.deadlineAt).map(raw=>this.playOffer(state,userId,raw)),...window.legalOfferIds.filter(id=>id.includes("finish")).map((offerId,index)=>this.windowOffer(state,window,offerId,index,userId))]:window.legalOfferIds.map((offerId,index)=>this.windowOffer(state,window,offerId,index,userId));return{prompt:{promptId:window.promptId,kind:window.kind,mandatory:window.mandatory,deadlineAt:window.deadlineAt,prioritySeat:window.prioritySeat,timeoutPolicy:window.timeoutPolicy},offers,disabledHints:[]};}
 private playOffer(state:AuthoritativeGameState,userId:string,raw:RawPlayOffer){const object=(x:unknown)=>x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,any>:{},targets=object(raw.targets),source=object(raw.source),mode=object(source.mode),legalTargets=(raw.legalTargetRefs??targets.legalTargetRefs??[]) as string[],legalCards=(raw.legalCardRefs??[]) as string[],killCards=(raw.legalKillCardRefs??[]) as string[],resourceCards=(raw.legalResourceCardRefs??[]) as string[],weaponCards=(raw.legalWeaponRefs??[]) as string[],privateRef=(ref:string)=>privateCardRef(userId,ref),cardRef=(ref:string)=>state.cards[ref]?.zoneRef.startsWith("hand:")?privateRef(ref):publicCardRef(ref),targetRef=(ref:string)=>ref.startsWith("character:")?`public:seat_${ref.split(":")[1]}`:publicCardRef(ref),specs:any[]=[];if(killCards.length)specs.push({key:"killCards",kind:"cards",min:Number(mode.costs?.killCards??1),max:Number(mode.costs?.killCards??1),distinct:true,legalRefs:killCards.map(cardRef)});if(resourceCards.length){const count=Number(mode.costs?.cards?.[0]?.count??1);specs.push({key:"resourceCards",kind:"cards",min:count,max:count,distinct:true,legalRefs:resourceCards.map(cardRef)});}if(legalCards.length){const count=Number(raw.requiredCardCount??raw.costCount??1);specs.push({key:"cards",kind:"cards",min:count,max:count,distinct:true,legalRefs:legalCards.map(cardRef)});}if(weaponCards.length){const count=Number(raw.requiredCount??1);specs.push({key:"weapons",kind:"cards",min:count,max:count,distinct:true,legalRefs:weaponCards.map(cardRef)});}if(legalTargets.length){const rule=object(targets.spec),min=Number(raw.targetMin??raw.targetCount??rule.min??1),max=Number(raw.targetMax??raw.targetCount??rule.max??1);specs.push({key:"targets",kind:"targets",min,max,distinct:true,legalRefs:legalTargets.map(targetRef)});}const fixedRefs=[raw.cardRef,raw.weaponRef].filter((x):x is string=>typeof x==="string").map(cardRef);return{offerId:raw.offerId,kind:raw.offerId.includes("attack")?"declareAttack":raw.offerId.includes("equip")?"equip":raw.offerId.includes("discard")?"discardEquipment":raw.offerId.includes("synthesis")?"synthesize":raw.offerId.includes("skill")||raw.offerId.includes("ability")?"activateAbility":"useCard",sourceRefs:fixedRefs,legalTargetRefs:legalTargets.map(targetRef),selectionSpecs:specs,preview:{weaponRef:typeof source.weaponRef==="string"?cardRef(source.weaponRef):null,modeId:typeof mode.modeId==="string"?mode.modeId:null,range:typeof mode.range==="number"?mode.range:null,costSummary:null}};}
 private windowOffer(state:AuthoritativeGameState,w:AuthoritativeGameState["pendingWindows"][number],offerId:string,index:number,userId:string){void index;const context=w.context??{},arrays=(keys:string[])=>keys.flatMap(key=>Array.isArray(context[key])?(context[key] as unknown[]).filter((x):x is string=>typeof x==="string"):[]),legal=[...new Set(arrays(["legalCardRefs","legalDodgeCardRefs","legalMeleeBlockRefs","legalArmorKillBlockRefs","legalWeaponRefs","legalEquipmentRefs","cardRefs"]))],targets=[...new Set(arrays(["legalTargetRefs","candidateTargetRefs"]))],pass=offerId.includes("pass")||offerId.includes("decline")||offerId.includes("skip"),kind=offerId.includes("finish")?"endPhase":pass?"pass":w.kind.toLowerCase().includes("response")||w.kind.toLowerCase().includes("dodge")?"respond":w.kind.toLowerCase().includes("dying")?"rescueDying":w.kind.toLowerCase().includes("judgment")?"interveneJudgment":"resolveChoice",specs:any[]=[],cardViewRef=(ref:string)=>state.cards[ref]?.zoneRef.startsWith("hand:")?privateCardRef(userId,ref):state.cards[ref]?.faceUp?publicCardRef(ref):privateCardRef(userId,ref),targetViewRef=(ref:string)=>ref.startsWith("character:")?`public:seat_${ref.split(":")[1]}`:publicCardRef(ref);if(legal.length&&!pass){const required=Math.max(1,Number(context.requiredCount??1));specs.push({key:"cards",kind:"cards",min:required,max:required,distinct:true,legalRefs:legal.map(cardViewRef)});}if(targets.length&&!pass){const required=Math.max(1,Number(context.targetCount??1));specs.push({key:"targets",kind:"targets",min:required,max:required,distinct:true,legalRefs:targets.map(targetViewRef)});}return{offerId,kind,sourceRefs:legal.map(cardViewRef),legalTargetRefs:targets.map(targetViewRef),selectionSpecs:specs,preview:{costSummary:null}};}
}
export function presentation(events:AuthoritativeGameState["history"]["domainEvents"]){return events.map(e=>({type:"PRESENTATION_EVENT",eventSeq:e.eventSeq,stateRevision:e.stateRevision,eventType:mapEvent(e.eventType),payload:eventPayload(e.eventType,e.payload)})).filter(Boolean);}
function mapEvent(type:string){if(type.startsWith("phase."))return"PHASE_CHANGED";if(type==="card.moved")return"CARD_MOVED";if(type==="attack.targets.chosen")return"ATTACK_TARGETED";if(type==="response.window.opened")return"RESPONSE_WINDOW_OPENED";if(type==="response.resolved")return"RESPONSE_RESOLVED";if(type==="judgment.card.revealed")return"JUDGMENT_REVEALED";if(type.startsWith("judgment."))return"JUDGMENT_RESULT_CHANGED";if(type==="damage.applied")return"DAMAGE_SEGMENT_APPLIED";if(type==="status.applied"||type==="status.removed")return"STATUS_CHANGED";if(type==="dying.started")return"DYING_STARTED";if(type==="character.rescued")return"CHARACTER_RESCUED";if(type==="character.died")return"CHARACTER_DIED";if(type==="character.eliminated")return"CHARACTER_ELIMINATED";if(type==="game.ended")return"GAME_ENDED";return"ACTION_COMMITTED";}
function eventPayload(type:string,payload:JsonValue){const p=(payload&&typeof payload==="object"&&!Array.isArray(payload)?payload:{}) as Record<string,JsonValue>;if(type.startsWith("phase."))return{activeSeat:Number(p.seat??p.activeSeat??1),phase:String(p.phase??"prepare")};if(type==="card.moved")return{cardRef:publicCardRef(String(p.cardRef)),from:String(p.fromZoneRef),to:String(p.toZoneRef)};if(type==="attack.targets.chosen")return{sourceRef:publicCardRef(String(p.attackId)),targetRefs:Array.isArray(p.targetRefs)?p.targetRefs.map(x=>`public:seat_${String(x).split(":")[1]}`):[]};return{sourceRef:typeof p.sourceRef==="string"?publicCardRef(p.sourceRef):"public:system",actionKind:type};}
