import {createHash,randomBytes,randomUUID,timingSafeEqual} from "node:crypto";
import type {LoadedRuleset} from "../ruleset/types.js";
import {createInitialSetup} from "../engine/setup.js";
import type {Seat,Team} from "../engine/state.js";
import {JsonPersistence} from "./persistence.js";
import type {AppChat,AppPlayer,AppRoom,AppSession,AppSettings,AppUser,JsonObject,PersistedApplication} from "./types.js";

const seats=[1,2,3,4] as const,alphabet="ABCDEFGHJKMNPQRSTUVWXYZ23456789";
const team=(seat:Seat):Team=>seat===1||seat===4?"A":"B";
const hash=(password:string)=>createHash("sha256").update(password,"utf8").digest("hex");
const sameHash=(password:string,expected:string)=>{const a=Buffer.from(hash(password)),b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b)};
function code(){const bytes=randomBytes(6);return [...bytes].map(x=>alphabet[x%alphabet.length]).join("")}
function settings(input:unknown):AppSettings{const x=input as Partial<AppSettings>;if(typeof x?.roomName!=="string"||!x.roomName.trim()||x.roomName.trim().length>40)throw new RoomError("ROOM_SETTINGS_INVALID");for(const key of ["turnTimeSeconds","responseTimeSeconds","reserveTimeSeconds"] as const)if(!Number.isInteger(x[key])||Number(x[key])<5||Number(x[key])>600)throw new RoomError("ROOM_SETTINGS_INVALID");return{roomName:x.roomName.trim(),allowGuests:x.allowGuests===true,allowSpectators:x.allowSpectators===true,turnTimeSeconds:Number(x.turnTimeSeconds),responseTimeSeconds:Number(x.responseTimeSeconds),reserveTimeSeconds:Number(x.reserveTimeSeconds),rulesetVersion:"1.3.4",dismantleBossEnabled:x.dismantleBossEnabled!==false};}
export class RoomError extends Error{constructor(public code:string,public refresh=false){super(code)}}
export interface RoomMutation {room:AppRoom|null;accepted:{type:"ROOM_COMMAND_ACCEPTED";commandId:string;roomRevision:number;roomId?:string|null}}
export class RoomService{
 readonly rooms=new Map<string,AppRoom>();readonly commandResults=new Map<string,JsonObject>();readonly sessions=new Map<string,AppSession>();private restoredGameResults:Record<string,Record<string,JsonObject>>={};
 constructor(readonly ruleset:LoadedRuleset,private persistence:JsonPersistence){ }
 async restore(loaded?:PersistedApplication){loaded??=await this.persistence.load();for(const room of loaded.rooms){for(const p of room.players)p.connection="offline";this.rooms.set(room.roomId,room)}for(const [hash,session] of Object.entries(loaded.sessions))this.sessions.set(hash,session);for(const [roomId,results] of Object.entries(loaded.roomCommandResults))for(const [commandId,result] of Object.entries(results)){const accepted=result.accepted as {roomId?:string}|undefined;this.commandResults.set(commandId,{room:accepted?.roomId?this.rooms.get(accepted.roomId)??null:null,accepted});}this.restoredGameResults=loaded.gameCommandResults;}
 async persist(extra:{gameCommandResults?:Record<string,Record<string,JsonObject>>}={}){await this.persistence.save({version:1,rooms:[...this.rooms.values()],sessions:Object.fromEntries(this.sessions),roomCommandResults:this.persistedRoomResults(),gameCommandResults:extra.gameCommandResults??{}})}
 restoredGameResultsSnapshot(){return this.restoredGameResults;}
 createSession(displayName:string){const userId=randomUUID(),token=randomBytes(32).toString("base64url"),hash=createHash("sha256").update(token).digest("hex");this.sessions.set(hash,{userId,displayName:displayName.slice(0,30)||`玩家${userId.slice(0,4)}`,createdAt:Date.now()});return{userId,displayName:displayName.slice(0,30)||`玩家${userId.slice(0,4)}`,token};}
 resolveSession(token:string){const hash=createHash("sha256").update(token).digest("hex"),session=this.sessions.get(hash);return session?{userId:session.userId,displayName:session.displayName}:null;}
 private persistedRoomResults(){const byRoom:Record<string,Record<string,JsonObject>>={};for(const [commandId,result] of this.commandResults){const accepted=result.accepted as {roomId?:string}|undefined,roomId=accepted?.roomId??"__no_room";byRoom[roomId]??={};byRoom[roomId]![commandId]={accepted};}for(const roomId of Object.keys(byRoom)){const entries=Object.entries(byRoom[roomId]!);byRoom[roomId]=Object.fromEntries(entries.slice(-2000));}return byRoom;}
 byCode(value:string){return[...this.rooms.values()].find(x=>x.roomCode===value.toUpperCase()&&x.phase!=="closed")??null}
 roomForUser(userId:string){return[...this.rooms.values()].find(x=>x.players.some(p=>p.userId===userId)||x.spectators.some(p=>p.userId===userId))??null}
 private player(room:AppRoom,userId:string){const p=room.players.find(x=>x.userId===userId);if(!p)throw new RoomError("PLAYER_NOT_IN_ROOM");return p}
 private host(room:AppRoom,userId:string){const p=this.player(room,userId);if(!p.isHost)throw new RoomError("HOST_PERMISSION_REQUIRED");return p}
 private touch(room:AppRoom){room.revision++;room.updatedAt=Date.now()}
 private candidates(){const chars=(this.ruleset.documents.get("characters.json") as {items:Array<{characterId:string}>}).items.map(x=>x.characterId),copy=[...chars];for(let i=copy.length-1;i>0;i--){const j=randomBytes(1)[0]!%(i+1);[copy[i],copy[j]]=[copy[j]!,copy[i]!];}return copy.slice(0,4)}
 async handle(user:AppUser,command:any):Promise<RoomMutation>{console.log("ROOM_HANDLE_START",command.commandId);const prior=this.commandResults.get(command.commandId);if(prior)return prior as unknown as RoomMutation;let room:AppRoom|null=null;const name=String(command.command),payload=(command.payload??{}) as any;
  if(name==="CREATE_ROOM"){if(this.roomForUser(user.userId))throw new RoomError("ALREADY_IN_ROOM");let roomCode=code();while(this.byCode(roomCode))roomCode=code();const now=Date.now(),seat:Seat=1;room={roomId:randomUUID(),roomCode,revision:1,phase:"waiting",settings:settings(payload.settings),passwordHash:typeof payload.password==="string"&&payload.password?hash(payload.password):null,players:[{...user,seat,team:team(seat),isHost:true,ready:false,connection:"online",latencyMs:null,selectionState:"notStarted",candidates:[],preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:null}],spectators:[],chat:[],gameChat:[],game:null,createdAt:now,updatedAt:now};this.rooms.set(room.roomId,room);}
  else if(name==="JOIN_ROOM"){room=this.byCode(String(payload.roomCode));if(!room)throw new RoomError("ROOM_NOT_FOUND");if(room.passwordHash&&!sameHash(String(payload.password??""),room.passwordHash))throw new RoomError("ROOM_PASSWORD_INVALID");if(room.players.some(x=>x.userId===user.userId)||room.spectators.some(x=>x.userId===user.userId)){}else if(payload.asSpectator===true){if(!room.settings.allowSpectators)throw new RoomError("SPECTATORS_DISABLED");room.spectators.push(user);this.touch(room);}else{if(room.phase!=="waiting"||room.players.length>=4)throw new RoomError("ROOM_NOT_JOINABLE");const seat=seats.find(n=>!room!.players.some(p=>p.seat===n));if(!seat)throw new RoomError("ROOM_FULL");room.players.push({...user,seat,team:team(seat),isHost:false,ready:false,connection:"online",latencyMs:null,selectionState:"notStarted",candidates:[],preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:null});this.touch(room);}}
  else{room=this.rooms.get(String(command.roomId))??null;if(!room)throw new RoomError("ROOM_NOT_FOUND");if(Number(command.expectedRoomRevision)!==room.revision)throw new RoomError("STALE_REVISION",true);const actor=this.player(room,user.userId);
   if(name==="LEAVE_ROOM"){room.players=room.players.filter(x=>x.userId!==user.userId);room.spectators=room.spectators.filter(x=>x.userId!==user.userId);if(actor.isHost&&room.players[0])room.players[0].isHost=true;if(!room.players.length)room.phase="closed";this.touch(room);}
   else if(name==="SET_READY"){if(room.phase!=="waiting")throw new RoomError("ROOM_PHASE_INVALID");actor.ready=payload.ready===true;this.touch(room);}
   else if(name==="CHANGE_SEAT"){this.host(room,user.userId);if(room.phase!=="waiting")throw new RoomError("ROOM_PHASE_INVALID");const target=this.player(room,String(payload.userId)),wanted=Number(payload.seat) as Seat,other=room.players.find(x=>x.seat===wanted),old=target.seat;target.seat=wanted;target.team=team(wanted);if(other){other.seat=old;other.team=team(old)}this.touch(room);}
   else if(name==="UPDATE_ROOM_SETTINGS"){this.host(room,user.userId);if(room.phase!=="waiting")throw new RoomError("ROOM_PHASE_INVALID");room.settings=settings(payload.settings);this.touch(room);}
   else if(name==="KICK_PLAYER"){this.host(room,user.userId);const target=this.player(room,String(payload.userId));if(target.isHost)throw new RoomError("CANNOT_KICK_HOST");room.players=room.players.filter(x=>x.userId!==target.userId);this.touch(room);}
   else if(name==="TRANSFER_HOST"){this.host(room,user.userId);const target=this.player(room,String(payload.userId));actor.isHost=false;target.isHost=true;this.touch(room);}
   else if(name==="CLOSE_ROOM"){this.host(room,user.userId);room.phase="closed";this.touch(room);}
   else if(name==="START_GAME"){this.host(room,user.userId);if(room.players.length!==4||room.players.some(x=>!x.ready||x.connection!=="online"))throw new RoomError("START_CONDITIONS_NOT_MET");room.phase="characterSelection";const deadline=Date.now()+room.settings.turnTimeSeconds*1000;for(const p of room.players){Object.assign(p,{selectionState:"choosing",candidates:this.candidates(),preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:deadline});}this.touch(room);}
   else if(name==="PRESELECT_CHARACTER"){if(room.phase!=="characterSelection")throw new RoomError("ROOM_PHASE_INVALID");const id=payload.characterId===null?null:String(payload.characterId);if(id&&!actor.candidates.includes(id))throw new RoomError("CHARACTER_NOT_OFFERED");actor.preselectedCharacterId=id;this.touch(room);}
   else if(name==="LOCK_CHARACTER"){if(room.phase!=="characterSelection")throw new RoomError("ROOM_PHASE_INVALID");const id=String(payload.characterId);if(!actor.candidates.includes(id))throw new RoomError("CHARACTER_NOT_OFFERED");actor.lockedCharacterId=id;actor.preselectedCharacterId=id;actor.selectionState="locked";this.touch(room);if(room.players.every(x=>x.lockedCharacterId)){for(const p of room.players)p.selectionState="revealed";const chars=Object.fromEntries(room.players.map(p=>[p.seat,p.lockedCharacterId!])) as Record<Seat,string>,users=Object.fromEntries(room.players.map(p=>[p.seat,p.userId])) as Record<Seat,string>;room.game=createInitialSetup(this.ruleset,{gameId:randomUUID(),firstSeat:1,seed:randomBytes(4).readUInt32LE(),usersBySeat:users,characterIdsBySeat:chars,setupStartedAt:Date.now()});room.phase="inGame";this.touch(room);}}
   else if(name==="SEND_CHAT"){this.addChat(room,actor,payload,false);this.touch(room);}
   else throw new RoomError("COMMAND_UNSUPPORTED");}
  const accepted={type:"ROOM_COMMAND_ACCEPTED" as const,commandId:String(command.commandId),roomRevision:room?.revision??0,...(room?{roomId:room.roomId}:{})},result={room,accepted};this.commandResults.set(String(command.commandId),result as unknown as JsonObject);console.log("ROOM_HANDLE_END",command.commandId);return result;}
 addChat(room:AppRoom,actor:AppPlayer,payload:any,game:boolean){const text=String(payload.text??"").trim();if(!text||text.length>500)throw new RoomError("CHAT_INVALID");const list=game?room.gameChat:room.chat;if(list.some(x=>x.clientMessageId===String(payload.clientMessageId)&&x.senderSeat===actor.seat))return;const message:AppChat={messageId:randomUUID(),clientMessageId:String(payload.clientMessageId),channel:payload.channel==="team"?"team":"all",senderSeat:actor.seat,senderDisplayName:actor.displayName,sentAt:Date.now(),text};list.push(message);if(list.length>200)list.splice(0,list.length-200);}
setConnection(userId:string,value:"online"|"reconnecting"|"offline"){const room=this.roomForUser(userId),p=room?.players.find(x=>x.userId===userId);if(p){p.connection=value;if(value!=="reconnecting")p.disconnectDeadlineAt=null;room!.updatedAt=Date.now();}}
setDisconnected(userId:string,now=Date.now()){const room=this.roomForUser(userId),p=room?.players.find(x=>x.userId===userId);if(p){p.connection="reconnecting";p.disconnectDeadlineAt=now+room!.settings.reserveTimeSeconds*1000;room!.updatedAt=now;}}
resolveDisconnectTimeouts(now=Date.now()){let changed=false;for(const room of this.rooms.values())for(const p of room.players){if(p.connection!=="reconnecting"||!p.disconnectDeadlineAt||p.disconnectDeadlineAt>now)continue;p.connection="offline";p.disconnectDeadlineAt=null;room.updatedAt=now;changed=true;}return changed;}
cleanupRooms(now=Date.now()){const removed:string[]=[];for(const room of this.rooms.values()){const closedExpired=room.phase==="closed"&&now-room.updatedAt>30*60*1000,idleWaiting=room.phase==="waiting"&&room.players.every(p=>p.connection==="offline")&&now-room.updatedAt>60*60*1000;if(closedExpired||idleWaiting)removed.push(room.roomId);}for(const roomId of removed)this.rooms.delete(roomId);return removed.length>0;}
 resolveCharacterTimeouts(now=Date.now()){let changed=false;for(const room of this.rooms.values()){if(room.phase!=="characterSelection")continue;let roomChanged=false;for(const player of room.players){if(player.lockedCharacterId||!player.selectionDeadlineAt||player.selectionDeadlineAt>now)continue;player.lockedCharacterId=player.preselectedCharacterId??player.candidates[0]!;player.preselectedCharacterId=player.lockedCharacterId;player.selectionState="locked";roomChanged=true;}if(roomChanged&&room.players.every(x=>x.lockedCharacterId)){for(const p of room.players)p.selectionState="revealed";const chars=Object.fromEntries(room.players.map(p=>[p.seat,p.lockedCharacterId!])) as Record<Seat,string>,users=Object.fromEntries(room.players.map(p=>[p.seat,p.userId])) as Record<Seat,string>;room.game=createInitialSetup(this.ruleset,{gameId:randomUUID(),firstSeat:1,seed:randomBytes(4).readUInt32LE(),usersBySeat:users,characterIdsBySeat:chars,setupStartedAt:now});room.phase="inGame";}if(roomChanged){this.touch(room);changed=true;}}return changed;}
}
