import {createServer,type Server as HttpServer} from "node:http";
import {readFile,stat} from "node:fs/promises";
import {extname,resolve} from "node:path";
import {randomUUID} from "node:crypto";
import {WebSocketServer,type WebSocket} from "ws";
import type {LoadedRuleset} from "../ruleset/types.js";
import {RoomError,RoomService} from "./roomService.js";
import {GameService} from "./gameService.js";
import {GameProjector,lobbyProjection,roomProjection} from "./projection.js";
import type {AppUser} from "./types.js";
import {validateProtocol} from "./protocol.js";

type Client={socket:WebSocket;user:AppUser};
const wire=(socket:WebSocket,type:"MESSAGE"|"COMMAND_RESULT",channel:"room"|"game",message:unknown)=>{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify({type,channel,message}))};
const mime:Record<string,string>={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".gif":"image/gif",".ico":"image/x-icon",".woff2":"font/woff2",".wasm":"application/wasm"};
export class SkbApplicationServer{
 readonly http:HttpServer;private wss:WebSocketServer;private clients=new Set<Client>();private games:GameService;private projector:GameProjector;private tickTimer:ReturnType<typeof setInterval>|null=null;private closing=false;
 constructor(private rooms:RoomService,private ruleset:LoadedRuleset,restoredGameResults:Record<string,Record<string,unknown>>={}){this.games=new GameService(ruleset);this.games.restore(restoredGameResults);this.projector=new GameProjector(ruleset);this.http=createServer(async(req,res)=>{if(req.url==="/health"){res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({ok:true,rulesetVersion:"1.3.4"}));return}if(req.method==="POST"&&req.url==="/api/session"){let body="";req.on("data",chunk=>{body+=String(chunk);if(body.length>4096)req.destroy()});req.on("end",()=>{let displayName="玩家";try{const parsed=JSON.parse(body||"{}");if(typeof parsed?.displayName==="string")displayName=parsed.displayName;}catch{/* default */}const session=this.rooms.createSession(displayName);res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify(session))});return}await this.serveStatic(req,res)});this.wss=new WebSocketServer({server:this.http,path:"/ws"});this.wss.on("connection",(socket,request)=>this.connect(socket,request.url??"/ws"));this.tickTimer=setInterval(()=>void this.tick(),250).unref();}
 private async serveStatic(req:import("node:http").IncomingMessage,res:import("node:http").ServerResponse){if(req.method!=="GET"&&req.method!=="HEAD"){res.writeHead(404);res.end("Not found");return}const root=resolve(import.meta.dirname,"../../../client/dist"),url=new URL(req.url??"/","http://localhost"),pathname=decodeURIComponent(url.pathname),relative=pathname==="/"?"index.html":pathname.replace(/^\/+/,""),candidate=resolve(root,relative),sep=process.platform==="win32"?"\\":"/",inside=candidate===root||candidate.startsWith(root+sep);if(!inside){res.writeHead(403);res.end("Forbidden");return}let file=candidate;try{const info=await stat(file);if(info.isDirectory())file=resolve(file,"index.html");await stat(file);}catch{try{const fallback=resolve(root,"index.html");const body=await readFile(fallback);res.writeHead(200,{"content-type":"text/html; charset=utf-8"});res.end(body);return}catch{res.writeHead(404);res.end("Not found");return}}const body=await readFile(file),type=mime[extname(file).toLowerCase()]??"application/octet-stream";res.writeHead(200,{"content-type":type,"cache-control":extname(file)===".html"?"no-cache":"public, max-age=31536000, immutable"});res.end(req.method==="HEAD"?undefined:body);}
 private connect(socket:WebSocket,path:string){const url=new URL(path,"http://localhost"),token=url.searchParams.get("token"),session=token?this.rooms.resolveSession(token):null,user=session??{userId:url.searchParams.get("userId")||randomUUID(),displayName:(url.searchParams.get("displayName")||"玩家").slice(0,30)},client={socket,user};this.clients.add(client);this.rooms.setConnection(user.userId,"online");this.sync(client);socket.on("message",raw=>void this.receive(client,String(raw)));socket.on("close",()=>{this.clients.delete(client);if(!this.closing){this.rooms.setDisconnected(user.userId);void this.persist();this.broadcast();}});}
 private async receive(client:Client,raw:string){let message:any;try{message=JSON.parse(raw)}catch{return}if(message.type==="PING"){client.socket.send(JSON.stringify({type:"PONG",sentAt:message.sentAt,serverTime:Date.now()}));return}if(message.type!=="COMMAND"||!message.command||(message.channel!=="room"&&message.channel!=="game"))return;let beforeEventSeq=0;const validation=validateProtocol(message.channel,message.command);if(!validation.ok){wire(client.socket,"COMMAND_RESULT",message.channel,message.channel==="room"?{type:"ROOM_COMMAND_REJECTED",commandId:String(message.command?.commandId??"invalid"),reasonCode:"PROTOCOL_INVALID",messageKey:"command.protocol_invalid",roomRevision:this.rooms.roomForUser(client.user.userId)?.revision??null,refreshRequired:false}:{type:"COMMAND_REJECTED",commandId:String(message.command?.commandId??"invalid"),reasonCode:"PROTOCOL_INVALID",messageKey:"command.protocol_invalid",stateRevision:this.rooms.roomForUser(client.user.userId)?.game?.stateRevision??0,refreshRequired:false});return}
   if(message.channel==="room"){try{const result=await this.rooms.handle(client.user,message.command);await this.persist();wire(client.socket,"COMMAND_RESULT","room",result.accepted)}catch(error){const e=error instanceof RoomError?error:new RoomError("COMMAND_FAILED",true),room=this.rooms.roomForUser(client.user.userId);wire(client.socket,"COMMAND_RESULT","room",{type:"ROOM_COMMAND_REJECTED",commandId:String(message.command.commandId),reasonCode:e.code,messageKey:`command.${e.code.toLowerCase()}`,roomRevision:room?.revision??null,refreshRequired:e.refresh})}}
   else if(message.channel==="game"){const room=this.rooms.roomForUser(client.user.userId);if(!room){wire(client.socket,"COMMAND_RESULT","game",{type:"COMMAND_REJECTED",commandId:String(message.command.commandId),reasonCode:"GAME_NOT_FOUND",messageKey:"command.game_not_found",stateRevision:0,refreshRequired:false});return}beforeEventSeq=room.game?.lastEventSeq??0;if(message.command.command==="SEND_CHAT"){try{const player=room.players.find(x=>x.userId===client.user.userId);if(!player)throw new RoomError("PLAYER_NOT_IN_GAME");this.rooms.addChat(room,player,message.command.payload,true);room.revision++;await this.persist();wire(client.socket,"COMMAND_RESULT","game",{type:"COMMAND_ACCEPTED",commandId:message.command.commandId,stateRevision:room.game?.stateRevision??0,firstEventSeq:Math.max(1,room.game?.lastEventSeq??1)})}catch(error){const e=error instanceof RoomError?error:new RoomError("CHAT_INVALID");wire(client.socket,"COMMAND_RESULT","game",{type:"COMMAND_REJECTED",commandId:message.command.commandId,reasonCode:e.code,messageKey:`command.${e.code.toLowerCase()}`,stateRevision:room.game?.stateRevision??0,refreshRequired:false})}}else{const result=this.games.handle(room,client.user,message.command);await this.persist();wire(client.socket,"COMMAND_RESULT","game",result.accepted?{type:"COMMAND_ACCEPTED",commandId:result.commandId,stateRevision:result.stateRevision,firstEventSeq:result.firstEventSeq}:{type:"COMMAND_REJECTED",commandId:result.commandId,reasonCode:result.reasonCode,messageKey:result.messageKey,stateRevision:result.stateRevision,refreshRequired:result.refreshRequired});}}
  if(message.channel==="game")this.broadcast(beforeEventSeq);else this.broadcast();
 }
 private sync(client:Client){const room=this.rooms.roomForUser(client.user.userId);wire(client.socket,"MESSAGE","room",room?roomProjection(room,client.user,this.ruleset):lobbyProjection(client.user,this.rooms.rooms.values()));if(room?.game&&room.players.some(x=>x.userId===client.user.userId))wire(client.socket,"MESSAGE","game",this.projector.game(room,client.user.userId));else if(room?.game&&room.spectators.some(x=>x.userId===client.user.userId))wire(client.socket,"MESSAGE","game",this.projector.spectator(room,client.user.userId));}
 private broadcast(fromEventSeq?:number){for(const client of this.clients){this.sync(client);if(fromEventSeq===undefined)continue;const room=this.rooms.roomForUser(client.user.userId);if(!room?.game||(!room.players.some(x=>x.userId===client.user.userId)&&!room.spectators.some(x=>x.userId===client.user.userId)))continue;const events=this.projector.presentationFor(room.game,client.user.userId,room.game.history.domainEvents.filter(event=>event.eventSeq>fromEventSeq));for(const event of events)wire(client.socket,"MESSAGE","game",event);}}
 private async persist(){await this.rooms.persist({gameCommandResults:this.games.persistedResults()});}
 private async tick(){let changed=this.rooms.resolveCharacterTimeouts();changed=this.rooms.resolveDisconnectTimeouts()||changed;changed=this.rooms.cleanupRooms()||changed;for(const room of this.rooms.rooms.values()){try{changed=this.games.timeout(room)||changed}catch{/* 单个房间超时异常不中断 tick */}}if(changed){await this.persist();this.broadcast();}}
 listen(port:number,host="0.0.0.0"){return new Promise<void>(resolve=>this.http.listen(port,host,resolve))}
 close(){this.closing=true;if(this.tickTimer)clearInterval(this.tickTimer);this.tickTimer=null;for(const c of this.clients)c.socket.close(1001,"server shutdown");return new Promise<void>((resolve,reject)=>this.wss.close(()=>this.http.close(e=>e?reject(e):resolve())))}
}
