import {createServer,type Server as HttpServer} from "node:http";
import {randomUUID} from "node:crypto";
import {WebSocketServer,type WebSocket} from "ws";
import type {LoadedRuleset} from "../ruleset/types.js";
import {RoomError,RoomService} from "./roomService.js";
import {GameService} from "./gameService.js";
import {GameProjector,lobbyProjection,roomProjection} from "./projection.js";
import type {AppUser} from "./types.js";
import {validateProtocol} from "./protocol.js";

type Client={socket:WebSocket;user:AppUser};
const wire=(socket:WebSocket,type:"MESSAGE"|"COMMAND_RESULT",channel:"room"|"game",message:unknown)=>{if(socket.readyState===socket.OPEN)socket.send(JSON.stringify({type,channel,message}))};
export class SkbApplicationServer{
 readonly http:HttpServer;private wss:WebSocketServer;private clients=new Set<Client>();private games:GameService;private projector:GameProjector;
 constructor(private rooms:RoomService,private ruleset:LoadedRuleset){this.games=new GameService(ruleset);this.projector=new GameProjector(ruleset);this.http=createServer((req,res)=>{if(req.url==="/health"){res.writeHead(200,{"content-type":"application/json"});res.end(JSON.stringify({ok:true,rulesetVersion:"1.3.4"}));return}res.writeHead(404);res.end("Not found")});this.wss=new WebSocketServer({server:this.http,path:"/ws"});this.wss.on("connection",(socket,request)=>this.connect(socket,request.url??"/ws"));setInterval(()=>void this.tick(),250).unref();}
 private connect(socket:WebSocket,path:string){const url=new URL(path,"http://localhost"),user={userId:url.searchParams.get("userId")||randomUUID(),displayName:(url.searchParams.get("displayName")||"玩家").slice(0,30)},client={socket,user};this.clients.add(client);this.rooms.setConnection(user.userId,"online");this.sync(client);socket.on("message",raw=>void this.receive(client,String(raw)));socket.on("close",()=>{this.clients.delete(client);this.rooms.setConnection(user.userId,"offline");void this.rooms.persist();this.broadcast()});}
 private async receive(client:Client,raw:string){let message:any;try{message=JSON.parse(raw)}catch{return}if(message.type==="PING"){client.socket.send(JSON.stringify({type:"PONG",sentAt:message.sentAt,serverTime:Date.now()}));return}if(message.type!=="COMMAND"||!message.command||(message.channel!=="room"&&message.channel!=="game"))return;const validation=validateProtocol(message.channel,message.command);if(!validation.ok){wire(client.socket,"COMMAND_RESULT",message.channel,message.channel==="room"?{type:"ROOM_COMMAND_REJECTED",commandId:String(message.command?.commandId??"invalid"),reasonCode:"PROTOCOL_INVALID",messageKey:"command.protocol_invalid",roomRevision:this.rooms.roomForUser(client.user.userId)?.revision??null,refreshRequired:false}:{type:"COMMAND_REJECTED",commandId:String(message.command?.commandId??"invalid"),reasonCode:"PROTOCOL_INVALID",messageKey:"command.protocol_invalid",stateRevision:this.rooms.roomForUser(client.user.userId)?.game?.stateRevision??0,refreshRequired:false});return}
  if(message.channel==="room"){try{const result=await this.rooms.handle(client.user,message.command);wire(client.socket,"COMMAND_RESULT","room",result.accepted)}catch(error){const e=error instanceof RoomError?error:new RoomError("COMMAND_FAILED",true),room=this.rooms.roomForUser(client.user.userId);wire(client.socket,"COMMAND_RESULT","room",{type:"ROOM_COMMAND_REJECTED",commandId:String(message.command.commandId),reasonCode:e.code,messageKey:`command.${e.code.toLowerCase()}`,roomRevision:room?.revision??null,refreshRequired:e.refresh})}}
  else if(message.channel==="game"){const room=this.rooms.roomForUser(client.user.userId);if(!room){wire(client.socket,"COMMAND_RESULT","game",{type:"COMMAND_REJECTED",commandId:String(message.command.commandId),reasonCode:"GAME_NOT_FOUND",messageKey:"command.game_not_found",stateRevision:0,refreshRequired:false});return}if(message.command.command==="SEND_CHAT"){try{const player=room.players.find(x=>x.userId===client.user.userId);if(!player)throw new RoomError("PLAYER_NOT_IN_GAME");this.rooms.addChat(room,player,message.command.payload,true);room.revision++;await this.rooms.persist();wire(client.socket,"COMMAND_RESULT","game",{type:"COMMAND_ACCEPTED",commandId:message.command.commandId,stateRevision:room.game?.stateRevision??0,firstEventSeq:Math.max(1,room.game?.lastEventSeq??1)})}catch(error){const e=error instanceof RoomError?error:new RoomError("CHAT_INVALID");wire(client.socket,"COMMAND_RESULT","game",{type:"COMMAND_REJECTED",commandId:message.command.commandId,reasonCode:e.code,messageKey:`command.${e.code.toLowerCase()}`,stateRevision:room.game?.stateRevision??0,refreshRequired:false})}}else{wire(client.socket,"COMMAND_RESULT","game",this.games.handle(room,client.user,message.command));await this.rooms.persist();}}
  this.broadcast();
 }
 private sync(client:Client){const room=this.rooms.roomForUser(client.user.userId);wire(client.socket,"MESSAGE","room",room?roomProjection(room,client.user,this.ruleset):lobbyProjection(client.user,this.rooms.rooms.values()));if(room?.game&&room.players.some(x=>x.userId===client.user.userId))wire(client.socket,"MESSAGE","game",this.projector.game(room,client.user.userId));}
 private broadcast(){for(const client of this.clients)this.sync(client)}
 private async tick(){let changed=this.rooms.resolveCharacterTimeouts();for(const room of this.rooms.rooms.values())changed=this.games.timeout(room)||changed;if(changed){await this.rooms.persist();this.broadcast();}}
 listen(port:number,host="0.0.0.0"){return new Promise<void>(resolve=>this.http.listen(port,host,resolve))}
 close(){for(const c of this.clients)c.socket.close(1001,"server shutdown");return new Promise<void>((resolve,reject)=>this.wss.close(()=>this.http.close(e=>e?reject(e):resolve())))}
}
