import {resolve} from "node:path";
import {beforeAll,describe,expect,it} from "vitest";
import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";
import type {LoadedRuleset} from "../ruleset/types.js";
import {runAutomaticScheduler} from "../engine/automaticScheduler.js";
import {createInitialSetup,resolveInitialRedraw} from "../engine/setup.js";
import {setWeaponPreselection} from "../engine/preselection.js";
import type {AuthoritativeGameState,Seat} from "../engine/state.js";
import {GameService} from "./gameService.js";
import {GameProjector} from "./projection.js";
import {playOffers,type RawPlayOffer} from "./playRegistry.js";
import {validateProtocol} from "./protocol.js";
import type {AppRoom,AppSettings,AppUser} from "./types.js";

// 非普通武器应用层验收：蓄力、多方式武器模式、武器专属主动（陨星杖/激光鱼/激光雨）。
let ruleset:LoadedRuleset;
const settings:AppSettings={roomName:"武器主动",allowGuests:true,allowSpectators:false,turnTimeSeconds:60,responseTimeSeconds:20,reserveTimeSeconds:30,rulesetVersion:"1.3.4",dismantleBossEnabled:true};
const users:Record<Seat,AppUser>={1:{userId:"u1",displayName:"一"},2:{userId:"u2",displayName:"二"},3:{userId:"u3",displayName:"三"},4:{userId:"u4",displayName:"四"}};
beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function openedState(seed=401,seat1="character.knight"):AuthoritativeGameState{let state=createInitialSetup(ruleset,{gameId:`weapon-special-${seed}`,firstSeat:1,seed,usersBySeat:{1:users[1]!.userId,2:users[2]!.userId,3:users[3]!.userId,4:users[4]!.userId},characterIdsBySeat:{1:seat1,2:"character.alchemist",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as Seat[])state=resolveInitialRedraw(state,seat,false,ruleset).state;const scheduled=runAutomaticScheduler(state,ruleset,()=>21000);state=scheduled.state;if(state.phase!=="play")throw new Error(`expected play phase, got ${state.phase}`);return state;}
function refsByTemplate(state:AuthoritativeGameState,prefix:string):string[]{return Object.values(state.cards).filter(card=>card.templateId.startsWith(prefix)).map(card=>card.cardRef);}
function moveCard(state:AuthoritativeGameState,cardRef:string,toZoneRef:string,owner:Seat=1){const card=state.cards[cardRef]!,from=state.zones[card.zoneRef]!,index=from.orderedCardRefs.indexOf(cardRef);if(index<0)throw new Error("card not in source zone");from.orderedCardRefs.splice(index,1);const to=state.zones[toZoneRef]!;to.orderedCardRefs.push(cardRef);card.zoneRef=toZoneRef;card.ownerSeat=to.ownerSeat??owner;card.controllerSeat=to.ownerSeat??owner;card.faceUp=!toZoneRef.startsWith("hand:");}
function moveKillToHand(state:AuthoritativeGameState):string{const kill=refsByTemplate(state,"basic.kill.")[0]!;if(state.zones[`hand:1`]!.orderedCardRefs.includes(kill))return kill;moveCard(state,kill,`hand:1`);return kill;}
function makeRoom(state:AuthoritativeGameState):AppRoom{return{roomId:state.gameId,roomCode:"WSP",revision:1,phase:"inGame",settings,passwordHash:null,players:state.players.map(player=>({userId:player.userId,displayName:users[player.seat]!.displayName,seat:player.seat,team:player.team,isHost:player.seat===1,ready:true,connection:"online",latencyMs:null,selectionState:"revealed",candidates:[],preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:null})),spectators:[],chat:[],gameChat:[],game:state,createdAt:0,updatedAt:0};}
function snapshotValid(room:AppRoom,userId:string){let projected;try{projected=new GameProjector(ruleset).game(room,userId);}catch(error){throw new Error(`projection threw: ${(error as Error).message}
${(error as Error).stack}`)}expect(validateProtocol("game",projected)).toEqual({ok:true});}
function offerFor(state:AuthoritativeGameState,match:(o:RawPlayOffer)=>boolean):RawPlayOffer{const offers=playOffers(state,ruleset,1,"u1",()=>Date.now()+20000),found=offers.find(match);if(!found)throw new Error(`offer not found; got ${offers.map(o=>o.offerId).join(",")}`);return found;}
function selectionsFor(raw:RawPlayOffer,projected:any,overrides?:Record<string,Array<string|number|boolean>>):Record<string,Array<string|number|boolean>>{const selections:Record<string,Array<string|number|boolean>>={};for(const spec of (projected.selectionSpecs??[]) as any[]){const refs=spec.legalRefs??[];if(spec.kind==="cards"&&refs.length)selections[spec.key]=[refs[0]!];if(spec.kind==="targets"&&refs.length)selections[spec.key]=[refs[0]!];if(spec.kind==="option"&&spec.options?.length)selections[spec.key]=[spec.options[0]!];}if(overrides)for(const [k,v] of Object.entries(overrides))selections[k]=v;return selections;}
function projectedOffer(room:AppRoom,offerId:string){const snap=new GameProjector(ruleset).game(room,"u1") as any;return (snap.interaction.offers as any[]).find((o:any)=>o.offerId===offerId)??(snap.interaction.offers as any[])[0]!;}
function submit(room:AppRoom,service:GameService,offerId:string,selections:Record<string,Array<string|number|boolean>>,commandId:string){const before=room.game!.stateRevision,command={type:"GAME_COMMAND",commandId,gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER",payload:{selections}};const first=service.handle(room,users[1]!,command);expect(first.accepted).toBe(true);expect(service.handle(room,users[1]!,command)).toEqual(first);expect(room.game!.stateRevision).toBeGreaterThan(before);snapshotValid(room,"u1");return first;}
function rejectInvalid(room:AppRoom,service:GameService,offerId:string,commandId:string){const before=room.game!.stateRevision,command={type:"GAME_COMMAND",commandId:commandId,gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER",payload:{selections:{cards:["public:missing"]}}};const out=service.handle(room,users[1]!,command);expect(out.accepted).toBe(false);expect(room.game!.stateRevision).toBe(before);}

describe("non-ordinary weapon application-layer offers",()=>{
 it("charge offer (W-11): costs kill+count, increments progress, keeps play window, no offer at max",()=>{let state=openedState(401);const w11=refsByTemplate(state,"weapon.w11")[0]!;moveCard(state,w11,"weapon:1:1");const kill=moveKillToHand(state);state=setWeaponPreselection(state,1,"weapon:1:1",null,ruleset).state;const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("weapon-charge")),projected=projectedOffer(room,raw.offerId);expect(raw.kind).toBe("chargeWeapon");expect((projected.selectionSpecs??[]).some((spec:any)=>spec.kind==="cards")).toBe(true);submit(room,service,raw.offerId,selectionsFor(raw,projected),"charge-1");expect(room.game!.cards[w11]!.runtime.chargeProgress).toBe(1);expect(room.game!.zones.discardPile!.orderedCardRefs).toContain(kill);expect(room.game!.players[0]!.limits.attackCountRemaining).toBe(0);expect(room.game!.pendingWindows.some(w=>w.kind==="playPhaseAction"),"蓄力后出牌窗口必须保留").toBe(true);rejectInvalid(room,service,raw.offerId,"charge-x");expect(playOffers(room.game!,ruleset,1,"u1",()=>Date.now()+20000).some(o=>o.offerId.includes("weapon-charge")),"满档后不得再提供蓄力报价").toBe(false);});
 it("charge rejects stale revision and wrong kill with zero pollution",()=>{let state=openedState(402);const w11=refsByTemplate(state,"weapon.w11")[0]!;moveCard(state,w11,"weapon:1:1");moveKillToHand(state);state=setWeaponPreselection(state,1,"weapon:1:1",null,ruleset).state;const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("weapon-charge"));const before=room.game!.stateRevision;const stale=service.handle(room,users[1]!,{type:"GAME_COMMAND",commandId:"charge-stale",gameId:room.game!.gameId,expectedStateRevision:before-1,promptId:room.game!.pendingWindows[0]!.promptId,offerId:raw.offerId,command:"EXECUTE_OFFER",payload:{selections:{cards:["private:u1:missing"]}}});expect(stale.accepted).toBe(false);expect((stale as any).reasonCode).toBe("STALE_REVISION");expect(room.game!.stateRevision).toBe(before);});
 it("meteor W-58: offers a full-table attack, pays kill+count, starts cooldown, no offer while cooling",()=>{let state=openedState(403);const w58=refsByTemplate(state,"weapon.w58")[0]!;moveCard(state,w58,"weapon:1:1");const kill=moveKillToHand(state);const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("w58-meteor")),projected=projectedOffer(room,raw.offerId);expect(raw.kind).toBe("activateWeapon");submit(room,service,raw.offerId,selectionsFor(raw,projected),"w58-1");expect(room.game!.zones.discardPile!.orderedCardRefs).toContain(kill);expect(room.game!.players[0]!.limits.attackCountRemaining).toBe(0);expect(room.game!.cards[w58]!.runtime.cooldownOwnPreparesUntilReady).toBe(3);expect(playOffers(room.game!,ruleset,1,"u1",()=>Date.now()+20000).some(o=>o.offerId.includes("w58-meteor")),"冷却中不得提供陨星杖报价").toBe(false);});
 it("laser fish W-64: aim consumes count and sets aimTarget, then cancel consumes a kill",()=>{let state=openedState(404);const w64=refsByTemplate(state,"weapon.w64")[0]!;moveCard(state,w64,"weapon:1:1");moveKillToHand(state);let room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("w64-aim")),projected=projectedOffer(room,raw.offerId);expect((projected.selectionSpecs??[]).some((spec:any)=>spec.kind==="targets")).toBe(true);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_2"]}),"w64-aim-1");const aimRef=Object.values(room.game!.zones).find(z=>z.ownerSeat===1&&["weaponSlot","thirdWeaponSlot"].includes(z.zoneType))!.orderedCardRefs[0]!;expect(room.game!.cards[aimRef]!.runtime.aimTarget).toBe("character:2");expect(room.game!.players[0]!.limits.attackCountRemaining).toBe(0);const cancelRaw=offerFor(room.game!,o=>o.offerId.includes("w64-cancel-aim")),cancelProjected=projectedOffer(room,cancelRaw.offerId);submit(room,service,cancelRaw.offerId,selectionsFor(cancelRaw,cancelProjected),"w64-cancel-1");expect(room.game!.cards[aimRef]!.runtime.aimTarget).toBeNull();});
 it("laser rain W-12: charged display offer resolves without an attack and clears progress",()=>{let state=openedState(405);const w12=refsByTemplate(state,"weapon.w12")[0]!;moveCard(state,w12,"weapon:1:1");moveKillToHand(state);state.cards[w12]!.runtime.chargeProgress=1;state=setWeaponPreselection(state,1,"weapon:1:1",null,ruleset).state;const room=makeRoom(state),service=new GameService(ruleset,()=>1000),raw=offerFor(state,o=>o.offerId.includes("w12-display")),projected=projectedOffer(room,raw.offerId);submit(room,service,raw.offerId,selectionsFor(raw,projected,{targets:["public:seat_2"]}),"w12-1");expect(room.game!.combat.attack).toBeNull();expect(room.game!.cards[w12]!.runtime.chargeProgress).toBe(0);expect(room.game!.history.domainEvents.some(e=>e.eventType==="weapon.resolution.committed")).toBe(true);});
 it("mode projection: W-50 exposes selectable modeIds to the owner and preselection carries modeId",()=>{let state=openedState(406);const w50=refsByTemplate(state,"weapon.w50")[0]!;moveCard(state,w50,"weapon:1:1");state=setWeaponPreselection(state,1,"weapon:1:1","mode_2",ruleset).state;const room=makeRoom(state);const snap=new GameProjector(ruleset).game(room,"u1") as any;const weapon=snap.publicView.players.find((p:any)=>p.seat===1)!.equipmentSlots.weapon1;expect(weapon.state.modeIds).toEqual(["mode_1","mode_2"]);expect(weapon.state.modeId).toBe("mode_2");expect(snap.privateView.preselectedModeId).toBe("mode_2");expect(validateProtocol("game",snap)).toEqual({ok:true});});
});
