// @vitest-environment jsdom
// 装备区卡牌点击交互：当前操作（activeOffer）需要选中装备区牌时，点击装备槽必须作为选择处理，
// 绝不能打断为预选；空闲状态下点击武器槽才进行预选；已选择操作时可随时取消恢复空闲。
// 这些用例在旧实现（点击装备槽一律先按预选处理）下失败，属于 bug 依据与回归防护。
import {mount} from "@vue/test-utils";
import {describe,expect,it} from "vitest";
import GameView from "./GameView.vue";

const emptyPlayer={seat:1 as const,team:"A" as const,nickname:"玩家1",connected:true,characterId:"character.knight",lifeState:"inPlay" as const,hp:5,maxHp:5,shield:5,maxShield:5,ironShield:0,handCount:0,handLimit:4,equipment:[],equipmentSlots:{weapon1:null,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[],mountDual:false},judgmentZone:[],statuses:[]};
const weaponCard={ref:"public:c-w1",templateId:"weapon.w23",displayName:"手里剑",category:"weapon" as const,printedColor:"white" as const,coreStats:[],summary:"",resourceKey:"card.weapon.w23",badges:[],state:{selected:false,effective:true},detailAvailable:true};
const player1={...emptyPlayer,equipmentSlots:{weapon1:weaponCard,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[],mountDual:false},handCount:1};
function snapshotWith(offers:any[]){return{type:"GAME_SNAPSHOT" as const,gameId:"g",rulesetVersion:"1.3.4" as const,stateRevision:1,lastEventSeq:1,serverTime:Date.now(),viewer:{userId:"u1",seat:1 as const,team:"A" as const},publicView:{round:1,activeSeat:1 as const,phase:"play" as const,players:[player1,{...emptyPlayer,seat:2 as const}],drawPileCount:10,discardTop:[],centralCards:[],headline:undefined,winnerTeam:null},privateView:{hand:[],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:["weapon:1:1"],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:"playPhaseAction",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers,disabledHints:[]},chat:[]} as any;}
// 合成报价：材料可来自装备区（public:c-w1），玩家必须先选择“合成”操作再点装备区牌。
const synthesisOffer={offerId:"offer:weapon-synthesis:w24",kind:"synthesize" as const,sourceRefs:[],legalTargetRefs:[],selectionSpecs:[{key:"cards",kind:"cards",min:1,max:1,distinct:true,legalRefs:["public:c-w1"]}],preview:{costSummary:null}};
// 攻击报价：需要的【杀】是手牌，不含装备区牌（用于验证“已选操作时点无关装备槽不打断”）。
const attackOffer={offerId:"offer:attack:1",kind:"declareAttack" as const,sourceRefs:[],legalTargetRefs:["public:seat_2"],selectionSpecs:[{key:"killCards",kind:"cards",min:1,max:1,distinct:true,legalRefs:["private:u1:kill1"]},{key:"targets",kind:"targets",min:1,max:1,distinct:true,legalRefs:["public:seat_2"]}],preview:{costSummary:null}};
function mountView(snapshot:any){return mount(GameView,{props:{snapshot,events:[]},global:{stubs:{PromptBanner:true,GameEventFeed:true,GameChatPanel:true,CardDetailDrawer:true,CharacterDetailDrawer:true,ResourceImage:true}}});}
const slot=()=>'.equipment-slot[data-slot="weapon:1:1"]';

describe("GameView equipment-slot clicks vs preselection",()=>{
 it("selects an equipped card for the chosen offer instead of preselecting",async()=>{const wrapper=mountView(snapshotWith([synthesisOffer]));await wrapper.find(".offer-list .button").trigger("click");await wrapper.find(slot()).trigger("click");expect(wrapper.emitted("preselection"),"点击装备区合法材料绝不能触发预选打断合成").toBeUndefined();const submit=wrapper.findAll(".interaction-panel .button--primary").at(-1)!;expect((submit.element as HTMLButtonElement).disabled).toBe(false);await submit.trigger("click");expect(wrapper.emitted("execute")![0]![0]).toBe(synthesisOffer.offerId);expect(wrapper.emitted("execute")![0]![1]).toEqual({cards:["public:c-w1"]});});
 it("preselects an equipped weapon when no offer was chosen",async()=>{const wrapper=mountView(snapshotWith([synthesisOffer]));await wrapper.find(slot()).trigger("click");expect(wrapper.emitted("preselection")![0]).toEqual(["weapon:1:1",null]);expect(wrapper.emitted("execute")).toBeUndefined();});
 it("does not preselect nor interrupt when an active offer does not need the equipped card",async()=>{const wrapper=mountView(snapshotWith([attackOffer]));await wrapper.find(".offer-list .button").trigger("click");await wrapper.find(slot()).trigger("click");expect(wrapper.emitted("preselection"),"已选择操作时点击无关装备槽不能打断").toBeUndefined();expect(wrapper.emitted("execute")).toBeUndefined();});
 it("shows a cancel button once an offer is chosen and cancel restores idle preselection",async()=>{const wrapper=mountView(snapshotWith([synthesisOffer]));expect(wrapper.find(".offer-cancel").exists()).toBe(false);await wrapper.find(".offer-list .button").trigger("click");expect(wrapper.find(".offer-cancel").exists()).toBe(true);await wrapper.find(slot()).trigger("click");expect(wrapper.emitted("preselection")).toBeUndefined();await wrapper.find(".offer-cancel .button").trigger("click");expect(wrapper.find(".offer-cancel").exists()).toBe(false);await wrapper.find(slot()).trigger("click");expect(wrapper.emitted("preselection")![0]).toEqual(["weapon:1:1",null]);});
 it("shows a cancel button for response windows that select equipped cards (melee block)",async()=>{const meleeBlockOffer={offerId:"offer:attack-response:meleeBlock:a1",kind:"respond" as const,sourceRefs:["public:c-w1"],legalTargetRefs:[],selectionSpecs:[{key:"cards",kind:"cards",min:1,max:1,distinct:true,legalRefs:["public:c-w1"]}],preview:{costSummary:null}};const snapshot=snapshotWith([meleeBlockOffer]);snapshot.interaction.prompt={promptId:"p:r",kind:"attackResponse",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const};snapshot.interaction.offers=[meleeBlockOffer,{offerId:"offer:attack-response:pass:a1",kind:"pass" as const,sourceRefs:[],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null}}];const wrapper=mountView(snapshot);await wrapper.find(".offer-list .button").trigger("click");expect(wrapper.find(".offer-cancel").exists()).toBe(true);await wrapper.find(slot()).trigger("click");expect(wrapper.emitted("preselection")).toBeUndefined();const submit=wrapper.findAll(".interaction-panel .button--primary").at(-1)!;expect((submit.element as HTMLButtonElement).disabled).toBe(false);});
 it("forwards a mode switch to preselection while idle",async()=>{const w50={...weaponCard,ref:"public:c-w50",templateId:"weapon.w50",displayName:"玄冥",state:{selected:false,effective:true,modeIds:["mode_1","mode_2"],modeId:"mode_1"}},snapshot=snapshotWith([]);snapshot.publicView.players[0].equipmentSlots.weapon1=w50;snapshot.privateView.preselectedWeaponSlot="weapon:1:1";snapshot.privateView.preselectedModeId="mode_1";const wrapper=mountView(snapshot),modes=wrapper.findAll(".weapon-mode");expect(modes.length).toBe(2);await modes[1]!.trigger("click");expect(wrapper.emitted("preselection")![0]).toEqual(["weapon:1:1","mode_2"]);});
 it("does not switch weapon mode while an offer is chosen",async()=>{const w50={...weaponCard,ref:"public:c-w50",templateId:"weapon.w50",state:{selected:false,effective:true,modeIds:["mode_1","mode_2"],modeId:"mode_1"}},snapshot=snapshotWith([synthesisOffer]);snapshot.publicView.players[0].equipmentSlots.weapon1=w50;snapshot.privateView.preselectedWeaponSlot="weapon:1:1";snapshot.privateView.preselectedModeId="mode_1";const wrapper=mountView(snapshot);await wrapper.find(".offer-list .button").trigger("click");await wrapper.findAll(".weapon-mode")[1]!.trigger("click");expect(wrapper.emitted("preselection"),"已选择操作时不得切换武器模式").toBeUndefined();});
 it("labels charge and weapon-active offers with the weapon name",async()=>{const sling={...weaponCard,ref:"public:c-w11",templateId:"weapon.w11",displayName:"弹弓",state:{selected:false,effective:true,charge:0}},meteor={...weaponCard,ref:"public:c-w58",templateId:"weapon.w58",displayName:"陨星杖",state:{selected:false,effective:true}},snapshot=snapshotWith([{offerId:"offer:weapon-charge:c-w11",kind:"chargeWeapon",sourceRefs:["public:c-w11"],legalTargetRefs:[],selectionSpecs:[{key:"killCards",kind:"cards",min:1,max:1,distinct:true,legalRefs:["private:u1:kill1"]}],preview:{costSummary:null}},{offerId:"offer:weapon-w58-meteor:1",kind:"activateWeapon",sourceRefs:["public:c-w58"],legalTargetRefs:[],selectionSpecs:[{key:"killCards",kind:"cards",min:1,max:1,distinct:true,legalRefs:["private:u1:kill1"]}],preview:{costSummary:null}}]);snapshot.publicView.players[0].equipmentSlots.weapon1=sling;snapshot.publicView.players[0].equipment=[sling];snapshot.publicView.discardTop=[meteor];const wrapper=mountView(snapshot),labels=wrapper.findAll(".offer-list .button").map(b=>b.text());expect(labels.some(t=>t.includes("蓄力")&&t.includes("弹弓"))).toBe(true);expect(labels.some(t=>t.includes("使用")&&t.includes("陨星杖"))).toBe(true);});
});
