// @vitest-environment jsdom
import {mount} from "@vue/test-utils";
import {describe,expect,it} from "vitest";
import GameCard from "./GameCard.vue";
import ResourceImage from "./ResourceImage.vue";
import GamePlayerPanel from "./GamePlayerPanel.vue";

const card=(overrides:Record<string,unknown>={})=>({ref:"card:1",templateId:"basic.kill.white",displayName:"杀",category:"basic" as const,printedColor:"white" as const,coreStats:[],summary:"攻击",resourceKey:"card.basic.kill.white",badges:[],state:{selected:false,effective:true},detailAvailable:false,...overrides});

describe("GameCard",()=>{
 it("highlights legal cards and emits select on click",async()=>{const wrapper=mount(GameCard,{props:{card:card(),legal:true}});expect(wrapper.find(".game-card--legal").exists()).toBe(true);await wrapper.find(".game-card").trigger("click");expect(wrapper.emitted("select")![0]).toEqual(["card:1"]);});
 it("shows disabled reason and emits detail",async()=>{const wrapper=mount(GameCard,{props:{card:card({state:{selected:false,effective:false},detailAvailable:true}),disabledReason:"装备失效"}});expect(wrapper.find(".game-card--disabled").exists()).toBe(true);expect(wrapper.find(".game-card__disabled-hint").exists()).toBe(true);await wrapper.find(".game-card__detail").trigger("click");expect(wrapper.emitted("detail")![0]![0]).toMatchObject({ref:"card:1"});});
});

describe("ResourceImage",()=>{
 it("starts with the first candidate and falls back on error",async()=>{const wrapper=mount(ResourceImage,{props:{resourceKey:"character.character.knight",alt:"骑士"}});const img=wrapper.find("img");const first=(img.element as HTMLImageElement).src;await img.trigger("error");const second=(wrapper.find("img").element as HTMLImageElement).src;expect(second).not.toBe(first);});
});

describe("GamePlayerPanel",()=>{
 const player=(overrides:Record<string,unknown>={})=>({seat:1 as const,team:"A" as const,nickname:"玩家1",connected:true,characterId:"character.knight",lifeState:"inPlay" as const,hp:5,maxHp:5,shield:5,maxShield:5,ironShield:0,handCount:4,handLimit:4,equipment:[],equipmentSlots:{weapon1:null,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[],mountDual:false},judgmentZone:[],statuses:[],...overrides});
 it("marks legal equipment cards and emits cardSelect",async()=>{const weapon=card({ref:"card:w1",templateId:"weapon.w06"}),wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:weapon,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,legalCardRefs:new Set(["card:w1"])}});const legalCard=wrapper.find(".game-card--legal");expect(legalCard.exists()).toBe(true);await legalCard.trigger("click");expect(wrapper.emitted("cardSelect")![0]).toEqual(["card:w1"]);});
 it("marks the player panel legal target and emits select",async()=>{const wrapper=mount(GamePlayerPanel,{props:{player:player(),active:false,local:false,legalTarget:true}});expect(wrapper.find(".game-player--legal").exists()).toBe(true);await wrapper.find(".game-player").trigger("click");expect(wrapper.emitted("select")![0]).toEqual(["public:seat_1"]);});
 it("matches server slot refs (weapon:1:1) so empty weapon slots are preselectable",async()=>{const wrapper=mount(GamePlayerPanel,{props:{player:player(),active:true,local:true,preselectedWeaponSlot:null,preselectableWeaponSlots:["weapon:1:1","weapon:2:1","thirdWeapon:1"]}});const emptySlots=wrapper.findAll(".equipment-slot");expect(emptySlots.length).toBeGreaterThan(0);const enabled=emptySlots.filter(slot=>!slot.attributes("disabled"));expect(enabled.length,`empty slots must be clickable for preselection; disabled=${emptySlots.filter(s=>s.attributes("disabled")).length}`).toBeGreaterThan(0);await enabled[0]!.trigger("click");expect(wrapper.emitted("slotSelect")![0]![0]).toMatch(/^(weapon:[1-3]:1|thirdWeapon:1)$/);});
 it("an equipped card that is a legal selection of the active offer emits cardSelect, not preselection",async()=>{const weapon=card({ref:"card:w1",templateId:"weapon.w06"}),wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:weapon,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,preselectedWeaponSlot:null,preselectableWeaponSlots:["weapon:1:1"],legalCardRefs:new Set(["card:w1"])}});await wrapper.find(".equipment-slot").trigger("click");expect(wrapper.emitted("cardSelect")![0]).toEqual(["card:w1"]);expect(wrapper.emitted("slotSelect"),`a legal equipment card must select it for the active offer instead of preselecting`).toBeUndefined();});
 it("preselects an equipped weapon slot when the card is not part of the active offer selection",async()=>{const weapon=card({ref:"card:w1",templateId:"weapon.w06"}),wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:weapon,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,preselectedWeaponSlot:null,preselectableWeaponSlots:["weapon:1:1"],legalCardRefs:new Set([])}});await wrapper.find(".equipment-slot").trigger("click");expect(wrapper.emitted("slotSelect")!.length).toBeGreaterThan(0);expect(wrapper.emitted("slotSelect")![0]![0]).toBe("weapon:1:1");expect(wrapper.emitted("cardSelect")).toBeUndefined();});
 it("empty armor and talent slots are clickable when listed as preselectable (client can equip armor/choose talent slot)",async()=>{const wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:null,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,preselectedWeaponSlot:null,preselectableWeaponSlots:["weapon:1:1","armor","talent:0:1","talent:1:1","talent:2:1"]}});const armor=wrapper.find('.equipment-slot[data-slot="armor"]'),talent0=wrapper.find('.equipment-slot[data-slot="talent:0:1"]'),talent1=wrapper.find('.equipment-slot[data-slot="talent:1:1"]');for(const slot of [armor,talent0,talent1]){expect(slot.exists(),`slot ${slot.attributes("data-slot")} must exist`).toBe(true);expect((slot.element as HTMLButtonElement).disabled,`slot ${slot.attributes("data-slot")} must be clickable`).toBe(false);}await armor.trigger("click");expect(wrapper.emitted("slotSelect")![0]![0]).toBe("armor");await talent0.trigger("click");expect(wrapper.emitted("slotSelect")![1]![0]).toBe("talent:0:1");});
 it("clicks an occupied talent slot to replace/route the equip to that slot",async()=>{const talentCard=card({ref:"card:t1",templateId:"talent.owl"}),wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:null,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[talentCard],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,preselectedWeaponSlot:null,preselectableWeaponSlots:["talent:0:1"],legalCardRefs:new Set([])}});const slot=wrapper.find('.equipment-slot[data-slot="talent:0:1"]');await slot.trigger("click");expect(wrapper.emitted("slotSelect")![0]![0]).toBe("talent:0:1");});
 it("shows mode buttons for a preselected multi-mode weapon and emits modeSelect",async()=>{const weapon=card({ref:"card:w50",templateId:"weapon.w50",state:{selected:false,effective:true,modeIds:["mode_1","mode_2"],modeId:"mode_1"}}),wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:weapon,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,preselectedWeaponSlot:"weapon:1:1",preselectedModeId:"mode_1",preselectableWeaponSlots:["weapon:1:1"]}});const modes=wrapper.findAll(".weapon-mode");expect(modes.length).toBe(2);await modes[1]!.trigger("click");expect(wrapper.emitted("modeSelect")![0]).toEqual(["weapon:1:1","mode_2"]);});
 it("does not show mode buttons when the multi-mode weapon is not preselected",async()=>{const weapon=card({ref:"card:w50",templateId:"weapon.w50",state:{selected:false,effective:true,modeIds:["mode_1","mode_2"],modeId:"mode_1"}}),wrapper=mount(GamePlayerPanel,{props:{player:player({equipmentSlots:{weapon1:weapon,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[]}}),active:true,local:true,preselectedWeaponSlot:null,preselectableWeaponSlots:["weapon:1:1"]}});expect(wrapper.findAll(".weapon-mode").length).toBe(0);});
});
describe("SeatCard",()=>{
 it("prefers the login username over the display name",async()=>{const {default:SeatCard}=await import("./SeatCard.vue");const wrapper=mount(SeatCard,{props:{seat:1,player:{userId:"u1",displayName:"昵称",username:"账号",seat:1,team:"A",isHost:false,ready:true,connection:"online",latencyMs:5,selectionState:"notStarted"}}});expect(wrapper.text()).toContain("账号");expect(wrapper.text()).not.toContain("昵称");});
});
