// @vitest-environment jsdom
import {mount} from "@vue/test-utils";
import {describe,expect,it} from "vitest";
import GameView from "../views/GameView.vue";

const emptyPlayer={seat:1 as const,team:"A" as const,nickname:"玩家1",connected:true,characterId:"character.knight",lifeState:"inPlay" as const,hp:5,maxHp:5,shield:5,maxShield:5,ironShield:0,handCount:0,equipment:[],equipmentSlots:{weapon1:null,weapon2:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null},judgmentZone:[],statuses:[]};
function snapshotWith(specs:any[],offerKind:"resolveChoice"="resolveChoice",promptKind="test"){return{type:"GAME_SNAPSHOT" as const,gameId:"g",rulesetVersion:"1.3.4" as const,stateRevision:1,lastEventSeq:1,serverTime:Date.now(),viewer:{userId:"u1",seat:1 as const,team:"A" as const},publicView:{round:1,activeSeat:1 as const,phase:"play" as const,players:[emptyPlayer,{...emptyPlayer,seat:2 as const}],drawPileCount:10,discardTop:[],centralCards:[],headline:undefined,winnerTeam:null},privateView:{hand:[],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:promptKind,mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:test:1",kind:offerKind,sourceRefs:[],legalTargetRefs:[],selectionSpecs:specs,preview:{costSummary:null}}],disabledHints:[]},chat:[]};}
function mountView(snapshot:any){return mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});}

describe("GameView choice selectors",()=>{
 it("selects a color option and submits it with the offer",async()=>{const snapshot=snapshotWith([{key:"color",kind:"color",min:1,max:1,options:["red","blue"]}]),wrapper=mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});await wrapper.find(".offer-list .button").trigger("click");const red=wrapper.findAll(".choice-buttons .mini-button").find((b)=>b.text().includes("红"))!;await red.trigger("click");const submit=wrapper.findAll(".interaction-panel .button--primary").at(-1)!;expect((submit.element as HTMLButtonElement).disabled).toBe(false);await submit.trigger("click");expect(wrapper.emitted("execute")![0]![0]).toBe("offer:test:1");expect(wrapper.emitted("execute")![0]![1]).toEqual({color:["red"]});});
 it("selects a number option and a confirm checkbox",async()=>{const snapshot=snapshotWith([{key:"amount",kind:"number",min:1,max:1,options:[0,1,2]},{key:"confirm",kind:"confirm",min:1,max:1,options:[true,false]}]),wrapper=mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});await wrapper.find(".offer-list .button").trigger("click");const buttons=wrapper.findAll(".choice-buttons .mini-button");await buttons.find((b)=>b.text()==="1")!.trigger("click");await buttons.find((b)=>b.text()==="确认")!.trigger("click");await wrapper.findAll(".interaction-panel .button--primary").at(-1)!.trigger("click");expect(wrapper.emitted("execute")![0]![1]).toEqual({amount:[1],confirm:[true]});});
 it("blocks submit until the spec minimum is met",async()=>{const snapshot=snapshotWith([{key:"color",kind:"color",min:1,max:1,options:["red","blue"]}]),wrapper=mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});await wrapper.find(".offer-list .button").trigger("click");const submit=wrapper.findAll(".interaction-panel .button--primary").at(-1)!;expect((submit.element as HTMLButtonElement).disabled).toBe(true);await submit.trigger("click");expect(wrapper.emitted("execute")).toBeUndefined();});
 it("shows a plain-language hint for the play phase window",async()=>{const wrapper=mountView(snapshotWith([],undefined,"playPhaseAction"));const hint=wrapper.find(".prompt-hint");expect(hint.exists()).toBe(true);expect(hint.text()).toContain("出牌阶段");expect(hint.text()).toContain("攻击");});
 it("shows a plain-language hint for the attack response window",async()=>{const wrapper=mountView(snapshotWith([],undefined,"attackResponse"));const hint=wrapper.find(".prompt-hint");expect(hint.exists()).toBe(true);expect(hint.text()).toContain("被攻击");});
 it("falls back to a generic hint for unknown window kinds",async()=>{const wrapper=mountView(snapshotWith([],undefined,"someUnknownKind"));const hint=wrapper.find(".prompt-hint");expect(hint.exists()).toBe(true);expect(hint.text().length).toBeGreaterThan(0);});
});
