// @vitest-environment jsdom
import {mount} from "@vue/test-utils";
import {describe,expect,it} from "vitest";
import GameView from "../views/GameView.vue";

const emptyPlayer={seat:1 as const,team:"A" as const,nickname:"玩家1",connected:true,characterId:"character.knight",lifeState:"inPlay" as const,hp:5,maxHp:5,shield:5,maxShield:5,ironShield:0,handCount:0,handLimit:4,equipment:[],equipmentSlots:{weapon1:null,weapon2:null,weapon3:null,thirdWeapon:null,armor:null,mountOffense:null,mountDefense:null,talents:[],boss:null,tripleWield:false,mountOccupied:[],mountDual:false},judgmentZone:[],statuses:[]};
function snapshotWith(specs:any[],offerKind:string="resolveChoice",promptKind="test"){return{type:"GAME_SNAPSHOT" as const,gameId:"g",rulesetVersion:"1.3.4" as const,stateRevision:1,lastEventSeq:1,serverTime:Date.now(),viewer:{userId:"u1",seat:1 as const,team:"A" as const},publicView:{round:1,activeSeat:1 as const,phase:"play" as const,players:[emptyPlayer,{...emptyPlayer,seat:2 as const}],drawPileCount:10,discardTop:[],centralCards:[],headline:undefined,winnerTeam:null},privateView:{hand:[],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:promptKind,mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:test:1",kind:offerKind,sourceRefs:[],legalTargetRefs:[],selectionSpecs:specs,preview:{costSummary:null}}],disabledHints:[]},chat:[]} as any;}
function mountView(snapshot:any){return mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});}

describe("GameView choice selectors",()=>{
 it("selects a color option and submits it with the offer",async()=>{const snapshot=snapshotWith([{key:"color",kind:"color",min:1,max:1,options:["red","blue"]}]),wrapper=mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});await wrapper.find(".offer-list .button").trigger("click");const red=wrapper.findAll(".choice-buttons .mini-button").find((b)=>b.text().includes("红"))!;await red.trigger("click");const submit=wrapper.findAll(".interaction-panel .button--primary").at(-1)!;expect((submit.element as HTMLButtonElement).disabled).toBe(false);await submit.trigger("click");expect(wrapper.emitted("execute")![0]![0]).toBe("offer:test:1");expect(wrapper.emitted("execute")![0]![1]).toEqual({color:["red"]});});
 it("selects a number option and a confirm checkbox",async()=>{const snapshot=snapshotWith([{key:"amount",kind:"number",min:1,max:1,options:[0,1,2]},{key:"confirm",kind:"confirm",min:1,max:1,options:[true,false]}]),wrapper=mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});await wrapper.find(".offer-list .button").trigger("click");const buttons=wrapper.findAll(".choice-buttons .mini-button");await buttons.find((b)=>b.text()==="1")!.trigger("click");await buttons.find((b)=>b.text()==="确认")!.trigger("click");await wrapper.findAll(".interaction-panel .button--primary").at(-1)!.trigger("click");expect(wrapper.emitted("execute")![0]![1]).toEqual({amount:[1],confirm:[true]});});
 it("blocks submit until the spec minimum is met",async()=>{const snapshot=snapshotWith([{key:"color",kind:"color",min:1,max:1,options:["red","blue"]}]),wrapper=mount(GameView,{props:{snapshot,events:[]},global:{stubs:{GamePlayerPanel:true,GameCard:true,PromptBanner:true,GameChatPanel:true,GameEventFeed:true,ResourceImage:true}}});await wrapper.find(".offer-list .button").trigger("click");const submit=wrapper.findAll(".interaction-panel .button--primary").at(-1)!;expect((submit.element as HTMLButtonElement).disabled).toBe(true);await submit.trigger("click");expect(wrapper.emitted("execute")).toBeUndefined();});
 it("shows a plain-language hint for the play phase window",async()=>{const wrapper=mountView(snapshotWith([],undefined,"playPhaseAction"));const hint=wrapper.find(".prompt-hint");expect(hint.exists()).toBe(true);expect(hint.text()).toContain("出牌阶段");expect(hint.text()).toContain("攻击");});
 it("shows a plain-language hint for the attack response window",async()=>{const wrapper=mountView(snapshotWith([],undefined,"attackResponse"));const hint=wrapper.find(".prompt-hint");expect(hint.exists()).toBe(true);expect(hint.text()).toContain("被攻击");});
 it("falls back to a generic hint for unknown window kinds",async()=>{const wrapper=mountView(snapshotWith([],undefined,"someUnknownKind"));const hint=wrapper.find(".prompt-hint");expect(hint.exists()).toBe(true);expect(hint.text().length).toBeGreaterThan(0);});
 it("shows 装备+卡牌名 for an equip offer",()=>{const snapshot={...snapshotWith([],"equip" as const,"playPhaseAction"),privateView:{hand:[{ref:"private:u1:c1",templateId:"weapon.w01",displayName:"烈焰剑",category:"weapon" as const,printedColor:"red" as const,coreStats:[],summary:"",resourceKey:"card.weapon.w01",badges:[],state:{selected:false,effective:true},detailAvailable:true}],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:"playPhaseAction",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:weapon-equip:private:u1:c1:weapon:1:1",kind:"equip" as const,sourceRefs:["private:u1:c1"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null,slot:"weapon:1:1"}}],disabledHints:[]}};
  const wrapper=mountView(snapshot);
  const button=wrapper.find(".offer-list .button");
  expect(button.text()).toContain("装备");
  expect(button.text()).toContain("烈焰剑");
 });
 it("shows 武N slot label for a weapon equip offer",()=>{const snapshot={...snapshotWith([],"equip" as const,"playPhaseAction"),privateView:{hand:[{ref:"private:u1:c1",templateId:"weapon.w01",displayName:"烈焰剑",category:"weapon" as const,printedColor:"red" as const,coreStats:[],summary:"",resourceKey:"card.weapon.w01",badges:[],state:{selected:false,effective:true},detailAvailable:true}],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:"playPhaseAction",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:weapon-equip:private:u1:c1:weapon:2:1",kind:"equip" as const,sourceRefs:["private:u1:c1"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null,slot:"weapon:2:1"}}],disabledHints:[]}};
  const wrapper=mountView(snapshot);
  expect(wrapper.find(".offer-list .button").text()).toContain("武2");
 });
 it("shows 甲 for an armor equip offer",()=>{const snapshot={...snapshotWith([],"equip" as const,"playPhaseAction"),privateView:{hand:[{ref:"private:u1:a1",templateId:"armor.w01",displayName:"锁子甲",category:"armor" as const,printedColor:"blue" as const,coreStats:[],summary:"",resourceKey:"card.armor.w01",badges:[],state:{selected:false,effective:true},detailAvailable:true}],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:"playPhaseAction",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:armor-equip:private:u1:a1",kind:"equip" as const,sourceRefs:["private:u1:a1"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null,slot:"armor"}}],disabledHints:[]}};
  const wrapper=mountView(snapshot);
  expect(wrapper.find(".offer-list .button").text()).toContain("甲");
 });
 it("shows 赋N slot label for each talent equip offer",()=>{const talentHand=(n:number)=>({ref:`private:u1:t${n}`,templateId:`talent.owl`,displayName:"枭首者",category:"talent" as const,printedColor:"orange" as const,coreStats:[],summary:"",resourceKey:"card.talent.owl",badges:[],state:{selected:false,effective:true},detailAvailable:true});const snapshot={...snapshotWith([],"equip" as const,"playPhaseAction"),privateView:{hand:[talentHand(1),talentHand(2),talentHand(3)],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:"playPhaseAction",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:talent-equip:private:u1:t1:slot:0",kind:"equip" as const,sourceRefs:["private:u1:t1"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null,slot:"talent:0:1"}},{offerId:"offer:talent-equip:private:u1:t1:slot:1",kind:"equip" as const,sourceRefs:["private:u1:t1"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null,slot:"talent:1:1"}},{offerId:"offer:talent-equip:private:u1:t1:slot:2",kind:"equip" as const,sourceRefs:["private:u1:t1"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null,slot:"talent:2:1"}}],disabledHints:[]}};
  const wrapper=mountView(snapshot);
  const buttons=wrapper.findAll(".offer-list .button");
  expect(buttons.length).toBe(3);
  expect(buttons[0]!.text()).toContain("赋1");expect(buttons[1]!.text()).toContain("赋2");expect(buttons[2]!.text()).toContain("赋3");
 });
 it("shows 技能名（非“发动技能”）for a skill offer",()=>{const snapshot=snapshotWith([],"activateAbility" as const,"playPhaseAction");snapshot.interaction.offers=[{offerId:"offer:skill.wizard.spell_strike",kind:"activateAbility" as const,sourceRefs:[],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null}}];const wrapper=mountView(snapshot);const button=wrapper.find(".offer-list .button");expect(button.text()).toContain("法术打击");expect(button.text()).not.toContain("发动技能");});
 it("shows 使用+卡牌名 for a useCard offer",()=>{const snapshot={...snapshotWith([],"useCard" as const,"playPhaseAction"),privateView:{hand:[{ref:"private:u1:c2",templateId:"support.potion",displayName:"小血瓶",category:"support" as const,printedColor:"green" as const,coreStats:[],summary:"",resourceKey:"card.support.potion",badges:[],state:{selected:false,effective:true},detailAvailable:true}],preselectedWeaponSlot:null,preselectedModeId:null,preselectableWeaponSlots:[],concealedChoices:[]},interaction:{prompt:{promptId:"p:1",kind:"playPhaseAction",mandatory:false,deadlineAt:Date.now()+10000,prioritySeat:1 as const,timeoutPolicy:"pass" as const},offers:[{offerId:"offer:basic-support:potion:private:u1:c2",kind:"useCard" as const,sourceRefs:["private:u1:c2"],legalTargetRefs:[],selectionSpecs:[],preview:{costSummary:null}}],disabledHints:[]}};
  const wrapper=mountView(snapshot);
  const button=wrapper.find(".offer-list .button");
  expect(button.text()).toContain("使用");
  expect(button.text()).toContain("小血瓶");
 });
});
