import {buildActionOffer,type ActionOffer} from "./actionOffers.js";
import {executeAction,type ActionDefinition,type ActionResolutionContext,type ActionSelections} from "./actions.js";
import {EngineTransaction} from "./transaction.js";
import type {AuthoritativeGameState,Seat} from "./state.js";
import type {DomainEvent} from "./types.js";

export interface RegisteredAction {offerId:string;definition:ActionDefinition;resolve?:(tx:EngineTransaction<AuthoritativeGameState>,context:ActionResolutionContext)=>void}
export interface ExecuteActionCommand {commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string;selections:ActionSelections}
export type ActionCommandRejectionCode="GAME_NOT_FOUND"|"STALE_REVISION"|"PROMPT_CLOSED"|"OFFER_EXPIRED"|"NOT_YOUR_PRIORITY"|"SELECTION_COUNT_INVALID"|"TARGET_NO_LONGER_LEGAL"|"COST_UNPAYABLE";
export interface AcceptedActionCommand {accepted:true;commandId:string;previousRevision:number;stateRevision:number;firstEventSeq:number|null;events:DomainEvent[];offers:ActionOffer[]}
export interface RejectedActionCommand {accepted:false;commandId:string;stateRevision:number;reasonCode:ActionCommandRejectionCode;messageKey:string;refreshRequired:boolean}
export type ActionCommandResult=AcceptedActionCommand|RejectedActionCommand;
const seatForUser=(state:AuthoritativeGameState,userId:string):Seat|null=>state.players.find(player=>player.userId===userId)?.seat??null;

export class ActionCommandSession{
  #state:AuthoritativeGameState;readonly #results=new Map<string,ActionCommandResult>();readonly #registrations:Map<string,RegisteredAction>;
  constructor(state:AuthoritativeGameState,registrations:readonly RegisteredAction[]){this.#state=state;this.#registrations=new Map(registrations.map(item=>[item.offerId,item]));}get state(){return this.#state;}
  offersFor(userId:string):ActionOffer[]{const seat=seatForUser(this.#state,userId),window=this.#state.pendingWindows.find(item=>item.kind==="playPhaseAction"&&item.prioritySeat===seat);if(!seat||!window)return[];return [...this.#registrations.values()].map(item=>buildActionOffer(this.#state,seat,item.offerId,item.definition)).filter(offer=>offer.payable);}
  handle(command:ExecuteActionCommand):ActionCommandResult{const prior=this.#results.get(command.commandId);if(prior)return structuredClone(prior);const reject=(reasonCode:ActionCommandRejectionCode,refreshRequired:boolean):RejectedActionCommand=>{const result={accepted:false as const,commandId:command.commandId,stateRevision:this.#state.stateRevision,reasonCode,messageKey:`command.${reasonCode.toLowerCase()}`,refreshRequired};this.#results.set(command.commandId,result);return structuredClone(result);};if(command.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(command.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const seat=seatForUser(this.#state,command.actorUserId),window=this.#state.pendingWindows.find(item=>item.kind==="playPhaseAction"&&item.prioritySeat===seat);if(!seat)return reject("NOT_YOUR_PRIORITY",false);if(!window||window.promptId!==command.promptId)return reject("PROMPT_CLOSED",true);const registration=this.#registrations.get(command.offerId);if(!registration)return reject("OFFER_EXPIRED",true);let committed;try{committed=executeAction(this.#state,{definition:registration.definition,actorSeat:seat,selections:command.selections},registration.resolve);}catch(error){if(!(error instanceof Error))throw error;if(error.message==="SELECTION_COUNT_INVALID"||error.message==="TARGET_NO_LONGER_LEGAL"||error.message==="COST_UNPAYABLE"||error.message==="COST_SELECTION_INVALID"||error.message==="COST_CARD_REUSED")return reject(error.message.startsWith("COST_")?"COST_UNPAYABLE":error.message as ActionCommandRejectionCode,false);throw error;}this.#state=committed.state;const result:AcceptedActionCommand={accepted:true,commandId:command.commandId,previousRevision:committed.previousRevision,stateRevision:committed.state.stateRevision,firstEventSeq:committed.events[0]?.eventSeq??null,events:committed.events,offers:this.offersFor(command.actorUserId)};this.#results.set(command.commandId,result);return structuredClone(result);}
}
