import type {AuthoritativeGameState,Seat} from "./state.js";
import {validateAuthoritativeState} from "./stateValidation.js";
import {EngineTransaction} from "./transaction.js";
import type {JsonValue,TransactionCommit} from "./types.js";

const equipmentEnabled=(state:AuthoritativeGameState,seat:Seat)=>{const player=state.players.find(item=>item.seat===seat)!;return player.markers.equipmentEffectsDisabled!==true&&!player.statuses.some(status=>status.statusId==="status.equipmentDisabled");};
const armorRef=(state:AuthoritativeGameState,seat:Seat)=>state.zones[`armor:${seat}`]?.orderedCardRefs[0]??null;
const turnKey=(state:AuthoritativeGameState,seat:Seat)=>`${state.round}:${seat}`;
export function recordCommittedWeaponAttack(tx:EngineTransaction<AuthoritativeGameState>,seat:Seat):void{const player=tx.draft.players.find(item=>item.seat===seat)!,key=turnKey(tx.draft,seat);if(player.markers.weaponAttackTurnKey!==key){player.markers.weaponAttackTurnKey=key;player.markers.committedWeaponAttacksThisTurn=0;}player.markers.committedWeaponAttacksThisTurn=Number(player.markers.committedWeaponAttacksThisTurn??0)+1;}
export function recordChargeAction(state:AuthoritativeGameState,seat:Seat):TransactionCommit<AuthoritativeGameState>{const tx=new EngineTransaction(state),draft=tx.draft,player=draft.players.find(item=>item.seat===seat)!,key=turnKey(draft,seat);if(player.markers.chargeActionTurnKey!==key){player.markers.chargeActionTurnKey=key;player.markers.chargeActionsThisTurn=0;}player.markers.chargeActionsThisTurn=Number(player.markers.chargeActionsThisTurn??0)+1;tx.emit("charge.action.committed",{seat,count:player.markers.chargeActionsThisTurn});const committed=tx.commit();committed.state.history.domainEvents.push(...committed.events);validateAuthoritativeState(committed.state);return committed;}
export function activateGhostCrownAtPlayEnd(tx:EngineTransaction<AuthoritativeGameState>,seat:Seat):void{const draft=tx.draft,player=draft.players.find(item=>item.seat===seat)!,sourceRef=armorRef(draft,seat),key=turnKey(draft,seat);if(!sourceRef||draft.cards[sourceRef]!.templateId!=="armor.a05"||!equipmentEnabled(draft,seat))return;const attacks=player.markers.weaponAttackTurnKey===key?Number(player.markers.committedWeaponAttacksThisTurn??0):0,charges=player.markers.chargeActionTurnKey===key?Number(player.markers.chargeActionsThisTurn??0):0;if(attacks!==0||charges!==0)return;const durationId=`duration:ghost-crown:${sourceRef}:${draft.stateRevision+1}`;player.markers.ghostCrownActive={sourceRef,durationId} as JsonValue;draft.durations.push({durationId,sourceRef,ownerRef:`character:${seat}`,anchorEventId:null,activationPoint:"owner.phase.play.after",expiryPoint:"owner.nextPhase.prepare.before",remainingCount:null,countScope:"owner",skipPolicy:"expireOnSkippedBoundary",sourceLeavePolicy:"cancel",ownerEliminatedPolicy:"cancel",cleanupEffects:[]});tx.emit("duration.created",{durationId,ownerSeat:seat,sourceRef,kind:"ghostCrownRangedInvalidation",expiryPoint:"owner.nextPhase.prepare.before"});}
export function ghostCrownInvalidates(state:AuthoritativeGameState,seat:Seat,attackTypes:JsonValue[],ignoreArmor:boolean):string|null{if(ignoreArmor||!equipmentEnabled(state,seat)||!attackTypes.includes("ranged")||attackTypes.includes("laser"))return null;const active=state.players.find(item=>item.seat===seat)!.markers.ghostCrownActive;if(!active||typeof active!=="object"||Array.isArray(active)||typeof active.sourceRef!=="string")return null;return armorRef(state,seat)===active.sourceRef&&state.cards[active.sourceRef]?.templateId==="armor.a05"?active.sourceRef:null;}
