import{resolve}from"node:path";import{beforeAll,describe,expect,it}from"vitest";import{loadFrozenRuleset}from"../ruleset/loadRuleset.js";import type{LoadedRuleset}from"../ruleset/types.js";import{createInitialSetup,resolveInitialRedraw}from"./setup.js";import type{AuthoritativeGameState}from"./state.js";import{buildArmorEquipOffers,ArmorEquipSession}from"./armorEquipment.js";
let r:LoadedRuleset;beforeAll(async()=>{r=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"))});
function ready(){let s=createInitialSetup(r,{gameId:"armor-equipment",firstSeat:1,seed:4101,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.knight",2:"character.ranger",3:"character.wizard",4:"character.druid"}});for(const n of[1,2,3,4]as const)s=resolveInitialRedraw(s,n,false,r).state;Object.assign(s,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});s.pendingWindows=[{promptId:"play",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];return s}
function move(s:AuthoritativeGameState,id:string,to:string){const c=Object.values(s.cards).find(x=>x.templateId===id)!,from=s.zones[c.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(c.cardRef),1);s.zones[to]!.orderedCardRefs.push(c.cardRef);Object.assign(c,{zoneRef:to,ownerSeat:s.zones[to]!.ownerSeat,controllerSeat:s.zones[to]!.ownerSeat,faceUp:!to.startsWith("hand:")});return c.cardRef}
const command=(s:AuthoritativeGameState,offerId:string,cardRef:string,id:string)=>({commandId:id,gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId,cardRef});
describe("armor equipment lifecycle",()=>{
 it("offers armor equip for armor cards in hand targeting the armor zone",()=>{const s=ready(),ref=move(s,"armor.a01","hand:1");const offers=buildArmorEquipOffers(s,r,1);const offer=offers.find(x=>x.cardRef===ref);expect(offer,"出牌阶段应生成防具装备 offer").toBeTruthy();expect(offer!.toZoneRef,"防具装备目标应为 armor 区").toBe("armor:1");expect(offer!.replacedCardRef).toBeNull()});
 it("equips armor into armor:1 and replaces an existing armor by discarding it",()=>{let s=ready();const first=move(s,"armor.a01","hand:1"),second=move(s,"armor.a02","hand:1");let session=new ArmorEquipSession(s,r);const o1=buildArmorEquipOffers(s,r,1).find(x=>x.cardRef===first)!;expect(session.handle(command(s,o1.offerId,first,"first")).accepted).toBe(true);s=session.state;expect(s.cards[first]!.zoneRef,"首次装备防具应进入 armor:1").toBe("armor:1");session=new ArmorEquipSession(s,r);const o2=buildArmorEquipOffers(s,r,1).find(x=>x.cardRef===second)!;expect(o2.replacedCardRef).toBe(first);expect(session.handle(command(s,o2.offerId,second,"replace")).accepted).toBe(true);expect(session.state.cards[first]!.zoneRef,"替换旧防具应弃置旧防具").toBe("discardPile");expect(session.state.cards[second]!.zoneRef).toBe("armor:1")});
});
