import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {commitAttack} from "./attack.js";import {runCombatUntilBlocked} from "./combatScheduler.js";import {resolveCurrentAttackTarget} from "./damage.js";import {setWeaponPreselection} from "./preselection.js";import {AttackResponseSession,openAttackResponse} from "./response.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";import type {JsonValue} from "./types.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function relocate(state:AuthoritativeGameState,ref:string,to:string){const card=state.cards[ref]!,from=state.zones[card.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);state.zones[to]!.orderedCardRefs.push(ref);card.zoneRef=to;card.ownerSeat=state.zones[to]!.ownerSeat;card.controllerSeat=state.zones[to]!.ownerSeat;card.faceUp=state.zones[to]!.zoneType!=="hand";}
function refFor(state:AuthoritativeGameState,id:string){return Object.values(state.cards).find(card=>card.templateId===id)!.cardRef;}
function hitWithArmor(armorId:string,amount:number,repeat:number){let state=createInitialSetup(ruleset,{gameId:`armor-damage-${armorId}`,firstSeat:1,seed:67,usersBySeat:users,characterIdsBySeat:characters});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;state.phase="play";state.phaseMode="manual";state.players[0]!.limits.attackCountRemaining=1;state.players[1]!.shield=10;state.players[1]!.hp=10;const armor=refFor(state,armorId==="armor.a09"?"armor.a02":armorId),kill=Object.values(state.cards).find(card=>card.templateId.startsWith("basic.kill."))!.cardRef;if(armorId==="armor.a09")state.cards[armor]!.templateId=armorId;relocate(state,armor,"armor:2");relocate(state,kill,"hand:1");state=setWeaponPreselection(state,1,"weapon:1:1",null,ruleset).state;state=commitAttack(state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[kill]}).state;const attack=state.combat.attack as Record<string,JsonValue>;attack.attackTypes=["ranged"];attack.damageSegments=[{segmentId:"base",deliveryType:"attack",attackType:"ranged",damageType:"normal",element:"none",amount,repeat,isAdditional:false,overflowPolicy:"normal"}];state=openAttackResponse(state,ruleset,500).state;const window=state.pendingWindows[0]!,session=new AttackResponseSession(state);session.handle({commandId:"pass",gameId:state.gameId,expectedStateRevision:state.stateRevision,actorUserId:"u2",promptId:window.promptId,offerId:window.legalOfferIds.find(id=>id.includes(":pass:"))!});return{state:session.state,armor};}
describe("locked armor damage replacement",()=>{
 it("Box prevents three positive segments before leaving, then later segments continue",()=>{const prepared=hitWithArmor("armor.a02",1,4),result=resolveCurrentAttackTarget(prepared.state);expect(result.state.players[1]!.shield).toBe(9);expect(result.state.cards[prepared.armor]!.runtime.durability).toBe(0);expect(result.state.cards[prepared.armor]!.zoneRef).toBe("discardPile");expect(result.events.filter(event=>event.eventType==="damage.prevented"&&String((event.payload as Record<string,unknown>).reason).includes("armor.a02"))).toHaveLength(3);});
 it("Refined Staff consumes its round quota on hit and reduces only the first positive segment",()=>{const prepared=hitWithArmor("armor.a06",1,3),result=resolveCurrentAttackTarget(prepared.state);expect(result.state.players[1]!.shield).toBe(8);expect(result.state.players[1]!.markers.refinedStaffUsed).toBe(true);expect(result.events.filter(event=>event.eventType==="damage.modified"&&String((event.payload as Record<string,unknown>).reason).includes("armor.a06"))).toHaveLength(1);});
 it("Refined Staff still consumes its quota when the hit contains only zero-damage segments",()=>{const prepared=hitWithArmor("armor.a06",0,2),result=resolveCurrentAttackTarget(prepared.state);expect(result.state.players[1]!.shield).toBe(10);expect(result.state.players[1]!.markers.refinedStaffUsed).toBe(true);expect(result.events.some(event=>event.eventType==="damage.received")).toBe(false);});
 it("ignores Box entirely when the attack ignores armor",()=>{const prepared=hitWithArmor("armor.a02",1,2);(prepared.state.combat.attack as Record<string,JsonValue>).ignoreArmor=true;const result=resolveCurrentAttackTarget(prepared.state);expect(result.state.players[1]!.shield).toBe(8);expect(result.state.cards[prepared.armor]!.zoneRef).toBe("armor:2");expect(result.state.cards[prepared.armor]!.runtime.durability).toBeUndefined();});
 it("Trap Box queues one standard counterattack per prevented segment and leaves after the last counter",()=>{const prepared=hitWithArmor("armor.a09",1,3);prepared.state.players[0]!.shield=10;prepared.state.players[0]!.hp=10;let state=resolveCurrentAttackTarget(prepared.state).state,counters=0;expect(state.cards[prepared.armor]!.zoneRef).toBe("armor:2");while(state.combat.attack){const scheduled=runCombatUntilBlocked(state,ruleset,()=>500);state=scheduled.state;if(scheduled.stoppedReason==="responseWindow"){const window=state.pendingWindows[0]!,session=new AttackResponseSession(state);session.handle({commandId:`trap-pass-${counters++}`,gameId:state.gameId,expectedStateRevision:state.stateRevision,actorUserId:`u${window.prioritySeat}`,promptId:window.promptId,offerId:window.legalOfferIds.find(id=>id.includes(":pass:"))!});state=session.state;}else if(scheduled.stoppedReason!=="combatComplete")throw new Error(`unexpected:${scheduled.stoppedReason}`);}expect(counters).toBe(3);expect(state.players[0]!.shield).toBe(4);expect(state.cards[prepared.armor]!.runtime.durability).toBe(0);expect(state.cards[prepared.armor]!.zoneRef).toBe("outsideDeck");});
});
