import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {commitAttack} from "./attack.js";import {recordChargeAction} from "./armorRuntime.js";import {setWeaponPreselection} from "./preselection.js";import {openAttackResponse} from "./response.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";import type {JsonValue} from "./types.js";import {advanceTimeline} from "./timeline.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function ready(){let state=createInitialSetup(ruleset,{gameId:"armor-runtime",firstSeat:1,seed:71,usersBySeat:users,characterIdsBySeat:characters});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;return state;}
function refFor(state:AuthoritativeGameState,id:string){return Object.values(state.cards).find(card=>card.templateId===id)!.cardRef;}
function relocate(state:AuthoritativeGameState,ref:string,to:string){const card=state.cards[ref]!,from=state.zones[card.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);state.zones[to]!.orderedCardRefs.push(ref);card.zoneRef=to;card.ownerSeat=state.zones[to]!.ownerSeat;card.controllerSeat=state.zones[to]!.ownerSeat;card.faceUp=state.zones[to]!.zoneType!=="hand";}
function activateCrown(){let state=ready();const crown=refFor(state,"armor.a05");relocate(state,crown,"armor:2");state.activeSeat=2;state.phase="play";state.phaseMode="manual";state.phaseBoundary="body";state.phaseBodyResolved=true;state.pendingWindows=[];state=advanceTimeline(state).state;return{state,crown};}
function attackCrown(state:AuthoritativeGameState){state.activeSeat=1;state.phase="play";state.phaseMode="manual";state.phaseBoundary="body";state.phaseBodyResolved=false;state.players[0]!.limits.attackCountRemaining=1;const weapon=refFor(state,"weapon.w01"),kill=Object.values(state.cards).find(card=>card.templateId.startsWith("basic.kill."))!.cardRef;relocate(state,weapon,"weapon:1:1");relocate(state,kill,"hand:1");state=setWeaponPreselection(state,1,"weapon:1:1","default",ruleset).state;return commitAttack(state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[kill]}).state;}
describe("Ghost Crown duration",()=>{
 it("invalidates ranged non-laser attacks against its owner",()=>{const active=activateCrown();expect(active.state.players[1]!.markers.ghostCrownActive).toBeDefined();const state=attackCrown(active.state),result=openAttackResponse(state,ruleset,500);expect(result.state.pendingWindows).toHaveLength(0);expect(result.state.combat.attack).toMatchObject({status:"targetMiss",currentTargetHit:false});expect(result.events.find(event=>event.eventType==="attack.invalidated")?.payload).toMatchObject({sourceRef:active.crown,sourceKind:"armor"});});
 it("does not invalidate laser or armor-ignoring attacks",()=>{let first=attackCrown(activateCrown().state);(first.combat.attack as Record<string,JsonValue>).attackTypes=["laser"];expect(openAttackResponse(first,ruleset,500).state.pendingWindows).toHaveLength(1);let second=attackCrown(activateCrown().state);(second.combat.attack as Record<string,JsonValue>).ignoreArmor=true;expect(openAttackResponse(second,ruleset,500).state.pendingWindows).toHaveLength(1);});
 it("does not activate when the owner charged during that play phase",()=>{let state=ready();const crown=refFor(state,"armor.a05");relocate(state,crown,"armor:2");state.activeSeat=2;state.phase="play";state.phaseMode="manual";state.phaseBoundary="body";state.phaseBodyResolved=true;state.pendingWindows=[];state=recordChargeAction(state,2).state;state=advanceTimeline(state).state;expect(state.players[1]!.markers.ghostCrownActive).toBeUndefined();});
});
