import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {commitAttack} from "./attack.js";import {runCombatUntilBlocked} from "./combatScheduler.js";import {finalizeJudgment} from "./judgment.js";import {JudgmentDesignationSession} from "./judgmentDesignation.js";import {setWeaponPreselection} from "./preselection.js";import {AttackResponseSession,openAttackResponse} from "./response.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";import type {JsonValue} from "./types.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.shaman",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});function relocate(state:AuthoritativeGameState,ref:string,to:string){const card=state.cards[ref]!,from=state.zones[card.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);state.zones[to]!.orderedCardRefs.push(ref);card.zoneRef=to;card.ownerSeat=state.zones[to]!.ownerSeat;card.controllerSeat=state.zones[to]!.ownerSeat;card.faceUp=!(["drawPile","hand"].includes(state.zones[to]!.zoneType));}function refFor(state:AuthoritativeGameState,prefix:string){return Object.values(state.cards).find(card=>card.templateId.startsWith(prefix))!.cardRef;}function hitWithWeapon(prefix:string){let state=createInitialSetup(ruleset,{gameId:`attack-judgment-${prefix}`,firstSeat:1,seed:47,usersBySeat:users,characterIdsBySeat:characters});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;state.phase="play";state.phaseMode="manual";state.players[0]!.limits.attackCountRemaining=1;state.players[1]!.hp=20;state.players[1]!.shield=20;const weapon=refFor(state,prefix),kill=refFor(state,"basic.kill.");relocate(state,weapon,"weapon:1:1");relocate(state,kill,"hand:1");state=setWeaponPreselection(state,1,"weapon:1:1","default",ruleset).state;state=commitAttack(state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[kill]}).state;state=openAttackResponse(state,ruleset,500).state;const window=state.pendingWindows[0]!,session=new AttackResponseSession(state);session.handle({commandId:"pass",gameId:state.gameId,expectedStateRevision:state.stateRevision,actorUserId:"u2",promptId:window.promptId,offerId:window.legalOfferIds.find(id=>id.includes(":pass:"))!});return session.state;}
function committedWithWeapon(prefix:string){
 let state=createInitialSetup(ruleset,{gameId:`targeted-${prefix}`,firstSeat:1,seed:4701,usersBySeat:users,characterIdsBySeat:characters});
 for(const seat of[1,2,3,4]as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;
 Object.assign(state,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});state.players[0]!.limits.attackCountRemaining=1;
 const weapon=refFor(state,prefix),kill=refFor(state,"basic.kill.");relocate(state,weapon,"weapon:1:1");relocate(state,kill,"hand:1");
 state=setWeaponPreselection(state,1,"weapon:1:1","default",ruleset).state;
 return commitAttack(state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[kill]}).state;
}
function shamanBypassPreJudgment(state:AuthoritativeGameState){state.players[2]!.markers.defyFateUsed=true;return state;}
describe("weapon judgment in combat",()=>{
 it("runs targeted weapon judgments before opening the ordinary response",()=>{let result=runCombatUntilBlocked(shamanBypassPreJudgment(committedWithWeapon("weapon.w16")),ruleset,()=>700);expect(result.stoppedReason).toBe("judgment");expect(result.state.resolutionStack[0]).toMatchObject({context:{judgmentRuleId:expect.any(String),resumeAttackStatus:"committed"}});let state=finalizeJudgment(result.state,"blue").state;result=runCombatUntilBlocked(state,ruleset,()=>700);expect(result.stoppedReason).toBe("responseWindow");expect(result.state.combat.attack).toMatchObject({critical:true});});
 it("honors a rule-level run-on-miss outcome even when an old effect field requires a hit",()=>{let state=shamanBypassPreJudgment(committedWithWeapon("weapon.w02")),attack=state.combat.attack as Record<string,JsonValue>;state.players[1]!.shield=10;attack.status="targetMiss";attack.currentTargetHit=false;attack.currentTargetResult="miss";let result=runCombatUntilBlocked(state,ruleset,()=>700);expect(result.stoppedReason).toBe("judgment");state=finalizeJudgment(result.state,"green").state;result=runCombatUntilBlocked(state,ruleset,()=>700);expect(result.stoppedReason).toBe("combatComplete");expect(result.state.players[1]!.shield).toBe(7);});
 it("executes the matched additional-damage outcome before resolving base damage",()=>{let result=runCombatUntilBlocked(shamanBypassPreJudgment(hitWithWeapon("weapon.w01")),ruleset,()=>500);expect(result.stoppedReason).toBe("judgment");expect(result.state.resolutionStack[0]).toMatchObject({frameType:"judgment",context:{purpose:"criticalAndWeaponEffect",attackId:expect.any(String)}});let state=finalizeJudgment(result.state,"orange").state;expect(state.combat.attack).toMatchObject({status:"targetHit",critical:true,judgmentResults:[{judgmentRuleId:"on_hit",matched:true,finalColor:"orange"}],pendingJudgmentEffects:expect.any(Array)});result=runCombatUntilBlocked(state,ruleset,()=>500);expect(result.stoppedReason).toBe("combatComplete");expect(result.state.combat.attack).toBeNull();expect(result.state.players[1]!.shield).toBe(16);expect(result.events.filter(event=>event.eventType==="damage.applied")).toHaveLength(3);});
 it("executes a matched status outcome and the frozen ice-shield trigger through shared runtimes",()=>{let result=runCombatUntilBlocked(shamanBypassPreJudgment(hitWithWeapon("weapon.w27")),ruleset,()=>500);expect(result.stoppedReason).toBe("judgment");let state=finalizeJudgment(result.state,"blue").state;state.players[0]!.initialTalentIds=["talent.ice_shield"];result=runCombatUntilBlocked(state,ruleset,()=>500);expect(result.stoppedReason).toBe("combatComplete");expect(result.state.players[1]!.statuses).toEqual(expect.arrayContaining([expect.objectContaining({statusId:"status.frozen",stackPolicy:"uniqueRefresh"})]));expect(result.state.durations.some(duration=>duration.ownerRef==="character:2")).toBe(true);expect(result.events.some(event=>event.eventType==="trigger.resolved"&&(event.payload as Record<string,unknown>).controllerSeat===1)).toBe(true);expect(result.events.find(event=>event.eventType==="damage.segment.added")?.payload).toMatchObject({sourceId:"talent.ice_shield",element:"poison",amount:1});});
 it("does not execute a default empty outcome",()=>{let result=runCombatUntilBlocked(shamanBypassPreJudgment(hitWithWeapon("weapon.w27")),ruleset,()=>500);let state=finalizeJudgment(result.state,"red").state;expect((state.combat.attack as Record<string,unknown>).pendingJudgmentEffects).toBeUndefined();result=runCombatUntilBlocked(state,ruleset,()=>500);expect(result.state.players[1]!.statuses.some(status=>status.statusId==="status.frozen")).toBe(false);});
 it("lets guaranteed critical designate only a successful outcome without drawing a card",()=>{let state=hitWithWeapon("weapon.w01");(state.combat.attack as Record<string,JsonValue>).guaranteedCritical=true;const drawCount=state.zones.drawPile!.orderedCardRefs.length;let result=runCombatUntilBlocked(state,ruleset,()=>700);expect(result.stoppedReason).toBe("judgment");expect(result.state.zones.drawPile!.orderedCardRefs).toHaveLength(drawCount);expect(result.state.zones.resolving!.orderedCardRefs.every(ref=>!ref.startsWith("card:judgment"))).toBe(true);const window=result.state.pendingWindows.find(item=>item.kind==="judgmentDesignation")!,session=new JudgmentDesignationSession(result.state),offerId=window.legalOfferIds.find(id=>id.includes(":orange:"))!,command={commandId:"designate-orange",gameId:state.gameId,expectedStateRevision:result.state.stateRevision,actorUserId:"u1",promptId:window.promptId,offerId};expect(session.handle(command).accepted).toBe(true);expect(session.handle(command).accepted).toBe(true);expect(session.state.zones.drawPile!.orderedCardRefs).toHaveLength(drawCount);result=runCombatUntilBlocked(session.state,ruleset,()=>700);expect(result.stoppedReason).toBe("combatComplete");expect(result.state.players[1]!.shield).toBe(16);});
});
