import { resolve } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { loadFrozenRuleset } from "../ruleset/loadRuleset.js";
import type { LoadedRuleset } from "../ruleset/types.js";
import { commitAttack } from "./attack.js";
import { runCombatUntilBlocked } from "./combatScheduler.js";
import { finalizeJudgment } from "./judgment.js";
import { AttackResponseSession, openAttackResponse } from "./response.js";
import { setWeaponPreselection } from "./preselection.js";
import { createInitialSetup, resolveInitialRedraw } from "./setup.js";
import type { AuthoritativeGameState } from "./state.js";
import { buildDemonicNatureOffers, DemonicNatureSession } from "./demonmancer.js";
import { resolvePhaseBody } from "./phaseBody.js";

let ruleset: LoadedRuleset;
beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function relocate(s:AuthoritativeGameState,ref:string,to:string){const c=s.cards[ref]!,from=s.zones[c.zoneRef]!,target=s.zones[to]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);target.orderedCardRefs.push(ref);Object.assign(c,{zoneRef:to,ownerSeat:target.ownerSeat,controllerSeat:target.ownerSeat,faceUp:false});}
function attack(){let s=createInitialSetup(ruleset,{gameId:"demonmancer",firstSeat:1,seed:2701,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.demonmancer",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;s.phase="play";s.phaseMode="manual";s.players[0]!.limits.attackCountRemaining=1;s.players[1]!.shield=10;s.players[1]!.maxShield=10;const kill=Object.values(s.cards).find((c)=>c.templateId.startsWith("basic.kill."))!;relocate(s,kill.cardRef,"hand:1");s=setWeaponPreselection(s,1,"weapon:1:1",null,ruleset).state;s=commitAttack(s,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[kill.cardRef]}).state;s=openAttackResponse(s,ruleset,500).state;const w=s.pendingWindows[0]!,session=new AttackResponseSession(s);session.handle({commandId:"pass",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u2",promptId:w.promptId,offerId:w.legalOfferIds.find((id)=>id.includes(":pass:"))!});return session.state;}
describe("Demonmancer hellfire",()=>{
  it("judges only after positive original damage and applies matched fire before combat resumes",()=>{let out=runCombatUntilBlocked(attack(),ruleset,()=>600);expect(out.stoppedReason).toBe("judgment");expect(out.state.resolutionStack[0]!.context).toMatchObject({purpose:"demonmancerHellfire",targetRef:"character:2"});const before=out.state.players[1]!.shield;let s=finalizeJudgment(out.state,"red").state;expect(s.scheduledEffects.some((x)=>x.scheduledId.startsWith("scheduled:demonmancer-hellfire:"))).toBe(true);out=runCombatUntilBlocked(s,ruleset,()=>600);expect(out.stoppedReason).toBe("combatComplete");expect(out.state.players[1]!.shield).toBe(before!-1);expect(out.events.find((e)=>e.eventType==="damage.applied")?.payload).toMatchObject({element:"fire",actualDamage:1});});
  it("does not judge when the original target damage is zero",()=>{const s=attack();s.players[1]!.ironShield=99;const out=runCombatUntilBlocked(s,ruleset,()=>600);expect(out.stoppedReason).toBe("combatComplete");expect(out.events.some((e)=>e.eventType==="judgment.started"&&typeof e.payload==="object"&&e.payload!==null&&!Array.isArray(e.payload)&&e.payload.purpose==="demonmancerHellfire")).toBe(false);});
});

describe("Demonic nature",()=>{
  it("spends every attack count, resolves two targets serially, then grants reward and anchored durations",()=>{let s=createInitialSetup(ruleset,{gameId:"nature",firstSeat:1,seed:2801,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.demonmancer",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;Object.assign(s,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});s.players[0]!.limits.attackCountRemaining=2;s.players[0]!.hp=2;s.players[0]!.initialTalentIds=[];for(const seat of[2,3]as const){s.players[seat-1]!.shield=20;s.players[seat-1]!.maxShield=20}s.pendingWindows=[{promptId:"play:nature",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];expect(buildDemonicNatureOffers(s,ruleset,1)[0]).toMatchObject({targetCount:2});const session=new DemonicNatureSession(s,ruleset),result=session.handle({commandId:"nature",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play:nature",offerId:"offer:skill.demonmancer.demonic_nature",targetRefs:["character:3","character:2"]});expect(result.accepted).toBe(true);s=session.state;const targets:string[]=[];while(s.combat.attack){const run=runCombatUntilBlocked(s,ruleset,()=>900);s=run.state;if(run.stoppedReason==="responseWindow"){const w=s.pendingWindows[0]!;targets.push(String(s.combat.currentTargetRef));const response=new AttackResponseSession(s);response.handle({commandId:`pass-${targets.length}`,gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:`u${w.prioritySeat}`,promptId:w.promptId,offerId:w.legalOfferIds.find((id)=>id.includes(":pass:"))!});s=response.state}else if(run.stoppedReason==="playWindow"&&!s.combat.attack)break;else if(run.stoppedReason!=="combatComplete")throw new Error(`unexpected:${run.stoppedReason}`)}expect(targets).toEqual(["character:2","character:3"]);expect(s.players[0]).toMatchObject({hp:4,maxShield:5,shield:5,ironShield:1});expect(s.players[1]!.markers["demonmancer.noShieldRecovery.1"]).toBe(3);expect(s.players[2]!.markers["demonmancer.noShieldRecovery.1"]).toBe(3);expect(s.pendingWindows[0]).toMatchObject({kind:"playPhaseAction",prioritySeat:1});});
  it("counts target and source prepare boundaries independently",()=>{let s=createInitialSetup(ruleset,{gameId:"nature-duration",firstSeat:1,seed:2901,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.demonmancer",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;const source=s.players[0]!,target=s.players[1]!;Object.assign(source.markers,{"demonmancer.natureIronActive":true,"demonmancer.natureIronRemainingPrepares":3,"demonmancer.natureIronContribution":1});source.ironShield=1;target.shield=0;target.maxShield=10;target.markers["demonmancer.noShieldRecovery.1"]=3;for(let i=0;i<3;i++){Object.assign(s,{activeSeat:2,phase:"prepare",phaseBoundary:"body",phaseMode:"automatic",phaseBodyResolved:false});s=resolvePhaseBody(s,ruleset,900).state;expect(target.shield).toBe(0)}Object.assign(s,{activeSeat:2,phase:"prepare",phaseBoundary:"body",phaseMode:"automatic",phaseBodyResolved:false});s=resolvePhaseBody(s,ruleset,900).state;expect(s.players[1]!.shield).toBe(1);for(let i=0;i<3;i++){Object.assign(s,{activeSeat:1,phase:"prepare",phaseBoundary:"body",phaseMode:"automatic",phaseBodyResolved:false});s=resolvePhaseBody(s,ruleset,900).state}expect(s.players[0]!.ironShield).toBe(0);});
});
