import type {AuthoritativeGameState,Seat} from "./state.js";

const seats=[1,2,3,4] as const;
function occupiesDistance(state:AuthoritativeGameState,seat:Seat):boolean{const player=state.players.find(item=>item.seat===seat)!;return player.lifeState!=="eliminated"||player.characterId==="character.interdimensional_traveler"&&player.presence==="leftPlay";}
export function calculateBaseDistance(state:AuthoritativeGameState,sourceSeat:Seat,targetSeat:Seat):number{
  if(sourceSeat===targetSeat)return 0;const occupied=seats.filter(seat=>occupiesDistance(state,seat));const sourceIndex=occupied.indexOf(sourceSeat),targetIndex=occupied.indexOf(targetSeat);if(sourceIndex<0||targetIndex<0)throw new Error("DISTANCE_SEAT_NOT_OCCUPYING");const direct=Math.abs(sourceIndex-targetIndex);return Math.min(direct,occupied.length-direct);
}
function numericLimit(state:AuthoritativeGameState,seat:Seat,key:string):number{const value=state.players.find(player=>player.seat===seat)!.limits[key]??0;if(typeof value!=="number"||!Number.isFinite(value))throw new Error("DISTANCE_MODIFIER_INVALID");return value;}
function equipmentEnabled(s:AuthoritativeGameState,n:Seat){const p=s.players.find(x=>x.seat===n)!;return p.markers.equipmentEffectsDisabled!==true&&!p.statuses.some(x=>x.statusId==="status.equipmentDisabled");}
function mountDelta(s:AuthoritativeGameState,n:Seat,kind:"offense"|"defense"){if(!equipmentEnabled(s,n))return 0;const refs=[...(s.zones[`mountOffense:${n}`]?.orderedCardRefs??[]),...(s.zones[`mountDefense:${n}`]?.orderedCardRefs??[])],unique=[...new Set(refs)];let total=0;for(const ref of unique){const card=s.cards[ref]!,raw=card.runtime[kind==="offense"?"mountOffenseDelta":"mountDefenseDelta"];total+=typeof raw==="number"?raw:0;if(card.runtime.mountDynamicTalentDistance===true){const p=s.players.find(x=>x.seat===n)!,ids=[...p.initialTalentIds,...(s.zones[`talent:${n}`]?.orderedCardRefs??[]).map(x=>s.cards[x]!.templateId)];total+=kind==="offense"?-ids.filter(x=>x==="talent.fire_shield"||x==="talent.poison_shield").length:ids.filter(x=>x==="talent.ice_shield"||x==="talent.electric_shield").length;}}return total;}
export function calculateEffectiveDistance(state:AuthoritativeGameState,sourceSeat:Seat,targetSeat:Seat):number{return Math.max(0,calculateBaseDistance(state,sourceSeat,targetSeat)+numericLimit(state,targetSeat,"defenseDistanceModifier")+numericLimit(state,sourceSeat,"offenseDistanceModifier")+mountDelta(state,sourceSeat,"offense")+mountDelta(state,targetSeat,"defense"));}
