import {resolve} from "node:path";import{beforeAll,describe,expect,it}from"vitest";import{loadFrozenRuleset}from"../ruleset/loadRuleset.js";import type{LoadedRuleset}from"../ruleset/types.js";import{createInitialSetup,resolveInitialRedraw}from"./setup.js";import type{AuthoritativeGameState}from"./state.js";import{buildElementSatchelOffers,ElementSatchelSession,ElementSatchelFlameSession}from"./elementalist.js";
let ruleset:LoadedRuleset;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"))});
function ready(){let s=createInitialSetup(ruleset,{gameId:"element",firstSeat:1,seed:431,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.ancient_elementalist",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;s.activeSeat=1;s.phase="play";s.phaseMode="manual";s.phaseBoundary="body";s.phaseBodyResolved=false;s.pendingWindows=[{promptId:"play",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:10,timeoutPolicy:"pass",legalOfferIds:[]}];return s}
function keepTargetCards(s:AuthoritativeGameState,count:number){const hand=s.zones["hand:2"]!;while(hand.orderedCardRefs.length>count){const ref=hand.orderedCardRefs.pop()!;s.zones.drawPile!.orderedCardRefs.push(ref);Object.assign(s.cards[ref]!,{zoneRef:"drawPile",ownerSeat:null,controllerSeat:null})}}
describe("Ancient Elementalist 元素锦囊（每锦囊一个报价、先选目标、烈焰拆牌两阶段）",()=>{
 it("每锦囊一个报价：frozen/electrified/flame 各一，均带合法目标列表",()=>{const s=ready();const offers=buildElementSatchelOffers(s,ruleset,1);expect(offers.map(o=>o.mode).sort()).toEqual(["electrified","flame","frozen"]);for(const o of offers){expect(o.legalTargetRefs.length).toBeGreaterThan(0);expect(o.targetMin).toBe(1);expect(o.targetMax).toBe(1);}expect(offers.find(o=>o.mode==="flame")!.legalTargetRefs).toContain("character:2");});
 it("frozen 锦囊：提交目标后直接令目标冰冻并消费额度",()=>{const s=ready(),offer=buildElementSatchelOffers(s,ruleset,1).find(x=>x.mode==="frozen")!,session=new ElementSatchelSession(s,ruleset),result=session.handle({commandId:"fz",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId:offer.offerId,targetRef:"character:2",cardRefs:[]});expect(result.accepted).toBe(true);expect(session.state.players.find(p=>p.seat===2)!.statuses.some(x=>x.statusId==="status.frozen")).toBe(true);expect(session.state.players[0]!.markers["elementSatchel.used.frozen"]).toBe(true);});
 it("烈焰锦囊：无任何可拆牌目标时不提供 flame 报价且不消耗额度",()=>{const s=ready();keepTargetCards(s,0);expect(buildElementSatchelOffers(s,ruleset,1).some(x=>x.mode==="flame"&&x.legalTargetRefs.includes("character:2"))).toBe(false);expect(s.players[0]!.markers["elementSatchel.used.flame"]).toBeUndefined()});
 it("烈焰锦囊两阶段：提交目标后打开拆牌窗口，第二阶段拆除所选牌并消费额度",()=>{const s=ready();keepTargetCards(s,2);const offer=buildElementSatchelOffers(s,ruleset,1).find(x=>x.mode==="flame")!,session=new ElementSatchelSession(s,ruleset),first=session.handle({commandId:"flame-1",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId:offer.offerId,targetRef:"character:2",cardRefs:[]});expect(first.accepted).toBe(true);const w=session.state.pendingWindows.find(x=>x.kind==="elementSatchelFlameDismantle");expect(w,"烈焰应打开拆牌窗口").toBeTruthy();const legal=w!.context!.legalCardRefs as string[];expect(legal.length).toBe(2);const flame=new ElementSatchelFlameSession(session.state,ruleset),second=flame.handle({commandId:"flame-2",gameId:s.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u1",promptId:w!.promptId,offerId:"offer:element-satchel-flame:dismantle",cardRefs:legal.slice(0,1)});expect(second.accepted,`拆牌被拒:${JSON.stringify(second)}`).toBe(true);expect(flame.state.zones.discardPile!.orderedCardRefs).toContain(legal[0]);expect(flame.state.players[0]!.markers).toMatchObject({"elementSatchel.used.flame":true});expect(flame.state.pendingWindows.some(x=>x.kind==="elementSatchelFlameDismantle")).toBe(false);});
 it("烈焰锦囊：目标不在合法列表时被拒且零污染",()=>{const s=ready();keepTargetCards(s,0);const session=new ElementSatchelSession(s,ruleset),result=session.handle({commandId:"bad-target",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId:"offer:skill.ancient_elementalist.element_satchel:flame",targetRef:"character:2",cardRefs:[]});expect(result).toMatchObject({accepted:false,reasonCode:"TARGET_NO_LONGER_LEGAL"});expect(session.state.players[0]!.markers["elementSatchel.used.flame"]).toBeUndefined()});
});
