import {resolve} from "node:path";import{beforeAll,describe,expect,it}from"vitest";import{loadFrozenRuleset}from"../ruleset/loadRuleset.js";import type{LoadedRuleset}from"../ruleset/types.js";import{createInitialSetup,resolveInitialRedraw}from"./setup.js";import type{AuthoritativeGameState}from"./state.js";import{buildElementSatchelOffers,ElementSatchelSession}from"./elementalist.js";
let ruleset:LoadedRuleset;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"))});
function ready(){let s=createInitialSetup(ruleset,{gameId:"element",firstSeat:1,seed:431,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.ancient_elementalist",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;s.activeSeat=1;s.phase="play";s.phaseMode="manual";s.phaseBoundary="body";s.phaseBodyResolved=false;s.pendingWindows=[{promptId:"play",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:10,timeoutPolicy:"pass",legalOfferIds:[]}];return s}
function keepTargetCards(s:AuthoritativeGameState,count:number){const hand=s.zones["hand:2"]!;while(hand.orderedCardRefs.length>count){const ref=hand.orderedCardRefs.pop()!;s.zones.drawPile!.orderedCardRefs.push(ref);Object.assign(s.cards[ref]!,{zoneRef:"drawPile",ownerSeat:null,controllerSeat:null})}}
function useFlame(s:AuthoritativeGameState){const offer=buildElementSatchelOffers(s,ruleset,1).find((x)=>x.mode==="flame"&&x.targetRef==="character:2")!,session=new ElementSatchelSession(s,ruleset),result=session.handle({commandId:"flame",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId:offer.offerId,targetRef:offer.targetRef,cardRefs:offer.legalCardRefs.slice(0,offer.requiredCardCount)});expect(result.accepted).toBe(true);return{offer,state:session.state}}
describe("Ancient Elementalist flame satchel",()=>{
 it("is illegal with zero dismantlable cards and does not consume its option",()=>{const s=ready();keepTargetCards(s,0);expect(buildElementSatchelOffers(s,ruleset,1).some((x)=>x.mode==="flame"&&x.targetRef==="character:2")).toBe(false);expect(s.players[0]!.markers["elementSatchel.used.flame"]).toBeUndefined()});
 it("requires and dismantles exactly one when the target has one",()=>{const s=ready();keepTargetCards(s,1);const out=useFlame(s);expect(out.offer.requiredCardCount).toBe(1);expect(out.state.zones["hand:2"]!.orderedCardRefs).toHaveLength(0)});
 it("requires exactly two when at least two are available and cannot repeat this play phase",()=>{const s=ready(),out=useFlame(s);expect(out.offer.requiredCardCount).toBe(2);expect(out.state.players[0]!.markers).toMatchObject({"elementSatchel.used.flame":true});expect(buildElementSatchelOffers(out.state,ruleset,1)).toHaveLength(0)});
 it("revalidates exact selected cards without consuming on rejection",()=>{const s=ready(),offer=buildElementSatchelOffers(s,ruleset,1).find((x)=>x.mode==="flame"&&x.targetRef==="character:2")!,session=new ElementSatchelSession(s,ruleset),result=session.handle({commandId:"bad",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId:offer.offerId,targetRef:offer.targetRef,cardRefs:offer.legalCardRefs.slice(0,1)});expect(result).toMatchObject({accepted:false,reasonCode:"SELECTION_COUNT_INVALID"});expect(session.state.players[0]!.markers["elementSatchel.used.flame"]).toBeUndefined()});
});
