import { resolve } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { loadFrozenRuleset } from "../ruleset/loadRuleset.js";
import type { LoadedRuleset } from "../ruleset/types.js";
import { runCombatUntilBlocked } from "./combatScheduler.js";
import { AttackResponseSession } from "./response.js";
import { createInitialSetup, resolveInitialRedraw } from "./setup.js";
import { advanceTimeline } from "./timeline.js";
import { runAutomaticScheduler } from "./automaticScheduler.js";
import { buildGeneralMortarOffers, GeneralMortarSession, tickGeneralMortarCooldownAtPrepare } from "./general.js";
import { EngineTransaction } from "./transaction.js";

let ruleset:LoadedRuleset;
beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function ready(){let state=createInitialSetup(ruleset,{gameId:"general",firstSeat:1,seed:1013,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.general"}});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;for(const player of state.players){player.shield=10;player.maxShield=10;player.hp=10;player.maxHp=10;}state.activeSeat=2;state.phase="discard";state.phaseBoundary="body";state.phaseMode="manual";state.phaseBodyResolved=true;state.pendingWindows=[];return state;}
function mortarReady(){let state=createInitialSetup(ruleset,{gameId:"mortar",firstSeat:1,seed:1019,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.general",2:"character.alchemist",3:"character.ranger",4:"character.wizard"}});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;for(const player of state.players){player.shield=10;player.maxShield=10;player.hp=10;player.maxHp=10;}state.activeSeat=1;state.phase="play";state.phaseBoundary="body";state.phaseMode="manual";state.phaseBodyResolved=false;state.pendingWindows=[{promptId:"play:mortar",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];return state;}
describe("General",()=>{
  it("starts Dog Squad at every actual end phase and resolves every in-play target from the active seat counterclockwise",()=>{const entered=advanceTimeline(ready(),{kind:"normal"},ruleset,700),attack=entered.state.combat.attack as Record<string,unknown>;expect(entered.state).toMatchObject({activeSeat:2,phase:"end",phaseBoundary:"body",phaseBodyResolved:false});expect(attack).toMatchObject({attackerSeat:4,weaponId:"talent.dog_squad",targetRefs:["character:2","character:3","character:4","character:1"]});let state=entered.state;const targetOrder:string[]=[];for(let guard=0;guard<12&&state.combat.attack;guard++){const run=runCombatUntilBlocked(state,ruleset,()=>800+guard);state=run.state;if(run.stoppedReason==="responseWindow"){const window=state.pendingWindows[0]!;targetOrder.push(String(state.combat.currentTargetRef));const session=new AttackResponseSession(state,ruleset),pass=window.legalOfferIds.find(id=>id.includes(":pass:"))!;expect(session.handle({commandId:`pass-${guard}`,gameId:state.gameId,expectedStateRevision:state.stateRevision,actorUserId:`u${window.prioritySeat}`,promptId:window.promptId,offerId:pass}).accepted).toBe(true);state=session.state;}else expect(run.stoppedReason).toBe("combatComplete");}expect(targetOrder).toEqual(["character:2","character:3","character:4","character:1"]);expect(state.players.map(player=>player.shield)).toEqual([9,9,9,9]);expect(state.combat.attack).toBeNull();});
  it("does not trigger when the General is eliminated or the end phase is skipped",()=>{let state=ready();state.players[3]!.lifeState="eliminated";expect(advanceTimeline(state,{kind:"normal"},ruleset).state.combat.attack).toBeNull();state=ready();expect(advanceTimeline(state,{kind:"skip",reason:"test"},ruleset).state.combat.attack).toBeNull();});
  it("commits Mortar atomically, damages all four serially, resumes play, and becomes ready on the third own prepare",()=>{const opened=mortarReady(),session=new GeneralMortarSession(opened,ruleset),window=opened.pendingWindows[0]!,command={commandId:"mortar",gameId:opened.gameId,expectedStateRevision:opened.stateRevision,actorUserId:"u1",promptId:window.promptId,offerId:"offer:skill.general.mortar"},first=session.handle(command);expect(first.accepted).toBe(true);expect(session.handle(command)).toEqual(first);expect(session.state.scheduledEffects.filter(item=>String((item.effect as Record<string,unknown>).op)==="createDamage").map(item=>(item.effect as Record<string,unknown>).targetRef)).toEqual(["character:1","character:2","character:3","character:4"]);const run=runAutomaticScheduler(session.state,ruleset,()=>1000);expect(run.stoppedReason).toBe("manualWindow");expect(run.state.players.map(player=>player.shield)).toEqual([7,7,7,7]);expect(run.state.pendingWindows[0]).toMatchObject({kind:"playPhaseAction",prioritySeat:1});expect(buildGeneralMortarOffers(run.state,ruleset,1)).toHaveLength(0);let state=run.state;for(let count=0;count<3;count++){const tx=new EngineTransaction(state);tickGeneralMortarCooldownAtPrepare(tx,1);const committed=tx.commit();committed.state.history.domainEvents.push(...committed.events);state=committed.state;expect(buildGeneralMortarOffers(state,ruleset,1)).toHaveLength(count===2?1:0);}});
  it("pauses Mortar on the first dying target before later targets are damaged",()=>{const opened=mortarReady();opened.players[0]!.shield=0;opened.players[0]!.hp=1;const session=new GeneralMortarSession(opened,ruleset),window=opened.pendingWindows[0]!;session.handle({commandId:"fatal-mortar",gameId:opened.gameId,expectedStateRevision:opened.stateRevision,actorUserId:"u1",promptId:window.promptId,offerId:"offer:skill.general.mortar"});const run=runAutomaticScheduler(session.state,ruleset,()=>1100);expect(run.stoppedReason).toBe("manualWindow");expect(run.state.pendingWindows[0]).toMatchObject({kind:"dyingRescue",prioritySeat:1});expect(run.state.players[1]!.shield).toBe(10);expect(run.state.scheduledEffects.filter(item=>String((item.effect as Record<string,unknown>).op)==="createDamage")).toHaveLength(3);});
});
