import type { LoadedRuleset } from "../ruleset/types.js";
import { createCompositeScriptedAttackInTransaction } from "./scriptedAttack.js";
import type { AuthoritativeGameState, Seat } from "./state.js";
import { EngineTransaction } from "./transaction.js";
import type { JsonValue } from "./types.js";
import { validateAuthoritativeState } from "./stateValidation.js";
import type { DomainEvent } from "./types.js";

interface Rule {ruleId:string;effects:Array<{op:string;params?:Record<string,unknown>;effects?:Array<{op:string;params?:Record<string,unknown>}>}>}
interface Document {rules:Rule[]}
function dogSquadDefinition(ruleset:LoadedRuleset){const document=ruleset.documents.get("character-rules.json") as Document,rule=document.rules.find(item=>item.ruleId==="character.general.dogSquad"),loop=rule?.effects.find(effect=>effect.op==="forEach"),attack=loop?.effects?.find(effect=>effect.op==="createAttack")?.params;if(loop?.params?.items!=="activeCharacter"||loop.params.mode!=="serial"||attack?.range!=="unlimited"||attack.type!=="melee"||attack.damageType!=="shield"||!Number.isInteger(attack.damage))throw new Error("GENERAL_DOG_SQUAD_RULE_INVALID");return{damage:Number(attack.damage)};}
function counterclockwiseFrom(activeSeat:Seat,seats:Seat[]):Seat[]{return [...seats].sort((a,b)=>((a-activeSeat+4)%4)-((b-activeSeat+4)%4));}
export function beginGeneralDogSquadAtEndPhase(tx:EngineTransaction<AuthoritativeGameState>,ruleset:LoadedRuleset,activeSeat:Seat):boolean {
  if(tx.draft.combat.attack||tx.draft.pendingWindows.length||tx.draft.resolutionStack.length)return false;
  const general=tx.draft.players.find(player=>player.characterId==="character.general"&&player.initialTalentIds.includes("talent.dog_squad")&&player.presence==="inPlay"&&player.lifeState==="alive");if(!general)return false;
  const active=tx.draft.players.find(player=>player.seat===activeSeat&&player.presence==="inPlay"&&player.lifeState!=="eliminated");if(!active)return false;
  const definition=dogSquadDefinition(ruleset);
  const segment={segmentId:"general.dogSquad",deliveryType:"attack",attackType:"melee",damageType:"shield",element:"none",amount:definition.damage,repeat:1,isAdditional:false,overflowPolicy:"normal"};
  createCompositeScriptedAttackInTransaction(tx,{attackId:`attack:general-dog-squad:${tx.draft.round}:${activeSeat}:${tx.draft.stateRevision+1}`,attackerSeat:general.seat,sourceRef:`character:${general.seat}`,weaponId:"talent.dog_squad",modeId:"dogSquad",range:"unlimited",targetGroups:[{targetRef:`character:${activeSeat}`,attackTypes:["melee"],damageSegments:[segment as unknown as JsonValue]}],tags:["characterTalentAttack","generalDogSquad"],preserveTargetOrder:true});
  tx.emit("ability.activation.committed",{seat:general.seat,abilityId:"talent.dog_squad",triggerSeat:activeSeat,targetRefs:[`character:${activeSeat}`]});return true;
}

const MORTAR_COOLDOWN="skill.general.mortar.cooldownOwnPrepares";
function mortarDefinition(ruleset:LoadedRuleset){const document=ruleset.documents.get("character-rules.json") as Document,rule=document.rules.find(item=>item.ruleId==="character.general.mortar"),loop=rule?.effects.find(effect=>effect.op==="forEach"),damage=loop?.effects?.find(effect=>effect.op==="createDamage")?.params;if(loop?.params?.items!=="allInPlay.counterclockwise"||loop.params.mode!=="serial"||damage?.deliveryType!=="direct"||damage.attackType!=="field"||damage.damageType!=="normal"||!Number.isInteger(damage.amount))throw new Error("GENERAL_MORTAR_RULE_INVALID");return{amount:Number(damage.amount),cooldown:2};}
export function tickGeneralMortarCooldownAtPrepare(tx:EngineTransaction<AuthoritativeGameState>,seat:Seat):void {const player=tx.draft.players.find(item=>item.seat===seat)!;if(player.characterId!=="character.general")return;const before=Number(player.markers[MORTAR_COOLDOWN]??0);if(!Number.isInteger(before)||before<=0)return;const after=before-1;if(after>0)player.markers[MORTAR_COOLDOWN]=after;else delete player.markers[MORTAR_COOLDOWN];tx.emit("cooldown.ticked",{seat,abilityId:"skill.general.mortar",from:before,to:after});}
export interface GeneralMortarOffer {offerId:string;stateRevision:number}
export function buildGeneralMortarOffers(state:AuthoritativeGameState,ruleset:LoadedRuleset,seat:Seat):GeneralMortarOffer[]{mortarDefinition(ruleset);const player=state.players.find(item=>item.seat===seat),window=state.pendingWindows.find(item=>item.kind==="playPhaseAction"&&item.prioritySeat===seat);return player?.characterId==="character.general"&&player.skillIds.includes("skill.general.mortar")&&player.lifeState==="alive"&&player.presence==="inPlay"&&state.activeSeat===seat&&state.phase==="play"&&state.phaseBoundary==="body"&&window&&Number(player.markers[MORTAR_COOLDOWN]??0)<=0&&!state.combat.attack?[{offerId:"offer:skill.general.mortar",stateRevision:state.stateRevision}]:[];}
function commitMortar(state:AuthoritativeGameState,ruleset:LoadedRuleset,seat:Seat){if(!buildGeneralMortarOffers(state,ruleset,seat).length)throw new Error("GENERAL_MORTAR_UNAVAILABLE");const tx=new EngineTransaction(state),definition=mortarDefinition(ruleset),player=tx.draft.players.find(item=>item.seat===seat)!,window=tx.draft.pendingWindows.find(item=>item.kind==="playPhaseAction"&&item.prioritySeat===seat)!;tx.draft.pendingWindows=tx.draft.pendingWindows.filter(item=>item.promptId!==window.promptId);player.markers[MORTAR_COOLDOWN]=definition.cooldown+1;const targets=counterclockwiseFrom(seat,tx.draft.players.filter(item=>item.presence==="inPlay"&&item.lifeState!=="eliminated").map(item=>item.seat));for(const targetSeat of targets){const scheduledId=`scheduled:general-mortar:${tx.draft.round}:${seat}:${targetSeat}:${tx.draft.stateRevision+1}`;tx.draft.scheduledEffects.push({scheduledId,sourceRef:`character:${seat}`,controllerSeat:seat,executeAt:"immediate.damagePipeline",effect:{op:"createDamage",targetRef:`character:${targetSeat}`,amount:definition.amount,damageType:"normal",element:"none",attackType:"field",isAdditional:false},cancelled:false});tx.emit("effect.scheduled",{scheduledId,abilityId:"skill.general.mortar",targetSeat});}tx.draft.scheduledEffects.push({scheduledId:`scheduled:general-mortar-resume:${tx.draft.stateRevision+1}:${seat}`,sourceRef:`character:${seat}`,controllerSeat:seat,executeAt:"immediate.damagePipeline",effect:{op:"resumePlayWindow",seat,deadlineAt:window.deadlineAt},cancelled:false});tx.emit("cooldown.started",{seat,abilityId:"skill.general.mortar",cooldown:definition.cooldown,ownerPreparesUntilReady:definition.cooldown+1});tx.emit("ability.activation.committed",{seat,abilityId:"skill.general.mortar",targetRefs:targets.map(target=>`character:${target}`)});const committed=tx.commit();committed.state.history.domainEvents.push(...committed.events);validateAuthoritativeState(committed.state);return committed;}
export interface GeneralMortarCommand {commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string}
export type GeneralMortarResult={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[];offers:GeneralMortarOffer[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
export class GeneralMortarSession {#state:AuthoritativeGameState;readonly #results=new Map<string,GeneralMortarResult>();constructor(state:AuthoritativeGameState,private readonly ruleset:LoadedRuleset){this.#state=state;}get state(){return this.#state;}offersFor(userId:string){const seat=this.#state.players.find(item=>item.userId===userId)?.seat;return seat?buildGeneralMortarOffers(this.#state,this.ruleset,seat):[];}handle(command:GeneralMortarCommand):GeneralMortarResult{const prior=this.#results.get(command.commandId);if(prior)return structuredClone(prior);const reject=(reasonCode:string,refreshRequired:boolean):GeneralMortarResult=>{const result={accepted:false as const,commandId:command.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired};this.#results.set(command.commandId,result);return structuredClone(result);};if(command.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(command.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const actor=this.#state.players.find(item=>item.userId===command.actorUserId),window=actor?this.#state.pendingWindows.find(item=>item.kind==="playPhaseAction"&&item.prioritySeat===actor.seat):undefined;if(!actor||!window)return reject("NOT_YOUR_PRIORITY",false);if(window.promptId!==command.promptId)return reject("PROMPT_CLOSED",true);if(command.offerId!=="offer:skill.general.mortar"||!buildGeneralMortarOffers(this.#state,this.ruleset,actor.seat).some(item=>item.offerId===command.offerId))return reject("OFFER_EXPIRED",true);const committed=commitMortar(this.#state,this.ruleset,actor.seat);this.#state=committed.state;const result={accepted:true as const,commandId:command.commandId,previousRevision:committed.previousRevision,stateRevision:committed.state.stateRevision,events:committed.events,offers:this.offersFor(command.actorUserId)};this.#results.set(command.commandId,result);return structuredClone(result);}}
