import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {beginJudgment,beginJudgmentInTransaction,finalizeJudgment} from "./judgment.js";import {JudgmentInterventionSession} from "./judgmentIntervention.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";import {EngineTransaction} from "./transaction.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.shaman",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});const initial=()=>createInitialSetup(ruleset,{gameId:"judgment",firstSeat:1,seed:43,usersBySeat:users,characterIdsBySeat:characters});const ready=()=>{let state=initial();for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;return state;};
function relocate(state:AuthoritativeGameState,ref:string,to:string){const card=state.cards[ref]!,from=state.zones[card.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);state.zones[to]!.orderedCardRefs.push(ref);card.zoneRef=to;card.ownerSeat=state.zones[to]!.ownerSeat;card.controllerSeat=state.zones[to]!.ownerSeat;card.faceUp=!(["drawPile","hand"].includes(state.zones[to]!.zoneType));}
function ensurePair(state:AuthoritativeGameState){const facts=new Map((ruleset.documents.get("cards.json") as {items:Array<{cardId:string;color:string}>}).items.map(item=>[item.cardId,item])),refs=Object.values(state.cards).filter(card=>facts.get(card.templateId)?.color==="white").slice(0,2).map(card=>card.cardRef);for(const ref of refs)relocate(state,ref,"hand:3");return refs;}
function noShamanInitial(){let state=createInitialSetup(ruleset,{gameId:"judgment-no-shaman",firstSeat:1,seed:43,usersBySeat:users,characterIdsBySeat:{1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"}});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;return state;}
describe("real card judgment",()=>{
 it("opens a shaman-exclusive intervention window with a replace offer",()=>{const state=ready();state.activeSeat=1;const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:"weapon:test",purpose:"critical",matchColors:["white","red"]},900),frame=begun.state.resolutionStack[0]!,cardRef=frame.context.cardRef as string;expect(begun.state.cards[cardRef]!.zoneRef).toBe("resolving");const window=begun.state.pendingWindows.find(item=>item.kind==="judgmentIntervention")!;expect(window.prioritySeat).toBe(3);expect(window.legalOfferIds.some(id=>id.includes(":replace:"))).toBe(true);expect(window.context).toMatchObject({shamanSeat:3,replaced:false});});
 it("lets only the shaman replace by discarding two same-color hand cards, at most once",()=>{const state=ready();state.activeSeat=1;const pair=ensurePair(state),begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"status",matchColors:["blue"]},900).state,session=new JudgmentInterventionSession(begun,ruleset),oldRef=begun.resolutionStack[0]!.context.cardRef as string,window=session.state.pendingWindows.find(item=>item.kind==="judgmentIntervention")!,replaceOffer=window.legalOfferIds.find(id=>id.includes(":replace:"))!;const nonShaman=session.handle({commandId:"non-shaman",gameId:state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u1",promptId:window.promptId,offerId:replaceOffer,cardRefs:pair});expect(nonShaman.accepted).toBe(false);const replaced=session.handle({commandId:"replace",gameId:state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u3",promptId:window.promptId,offerId:replaceOffer,cardRefs:pair});expect(replaced.accepted).toBe(true);const reopened=session.state.pendingWindows.find(item=>item.kind==="judgmentIntervention")!;expect(session.state.cards[oldRef]!.zoneRef).toBe("discardPile");expect(session.state.resolutionStack[0]!.context.replaced).toBe(true);expect(reopened.legalOfferIds.some(id=>id.includes(":replace:"))).toBe(false);expect(pair.every(ref=>session.state.cards[ref]!.zoneRef==="discardPile")).toBe(true);});
 it("can explicitly override only the final result without changing the real card",()=>{const state=ready();state.activeSeat=1;const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"critical",matchColors:["red"]}).state,cardRef=begun.resolutionStack[0]!.context.cardRef as string,result=finalizeJudgment(begun,"red");expect(result.events.map(event=>event.eventType)).toContain("judgment.matched");expect(result.events.find(event=>event.eventType==="judgment.finalized")?.payload).toMatchObject({finalColor:"red",overridden:true});expect(result.state.cards[cardRef]!.zoneRef).toBe("discardPile");});
 it("records a non-match when both deck and discard are empty",()=>{const state=noShamanInitial();for(const zoneRef of ["drawPile","discardPile"]){const refs=state.zones[zoneRef]!.orderedCardRefs.splice(0);state.zones.outsideDeck!.orderedCardRefs.push(...refs);for(const ref of refs)state.cards[ref]!.zoneRef="outsideDeck";}const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["white"]});expect(begun.state.resolutionStack).toHaveLength(0);expect(begun.state.pendingWindows).toHaveLength(0);expect(begun.events.map(event=>event.eventType)).toContain("judgment.notMatched");});
 it("auto-finalizes when no shaman is in play and leaves no window behind",()=>{const state=noShamanInitial();const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["white"]},900);expect(begun.state.resolutionStack).toHaveLength(0);expect(begun.state.pendingWindows).toHaveLength(0);expect(begun.state.zones.resolving!.orderedCardRefs).toHaveLength(0);expect(begun.events.some(event=>event.eventType==="judgment.finalized")).toBe(true);});
 it("finalizes after the shaman passes once",()=>{const state=ready();state.activeSeat=1;const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["white"]},900).state,session=new JudgmentInterventionSession(begun,ruleset),window=session.state.pendingWindows.find(item=>item.kind==="judgmentIntervention")!;const result=session.handle({commandId:"pass",gameId:state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u3",promptId:window.promptId,offerId:window.legalOfferIds.find(id=>id.includes(":pass:"))!});expect(result.accepted).toBe(true);expect(session.state.resolutionStack).toHaveLength(0);expect(session.state.pendingWindows).toHaveLength(0);expect(session.state.zones.resolving!.orderedCardRefs).toHaveLength(0);});
 it("runs the no-shaman judgment inside an existing transaction without leaving a window",()=>{const state=noShamanInitial();const tx=new EngineTransaction(state);beginJudgmentInTransaction(tx,ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["blue"]},900);expect(tx.draft.resolutionStack).toHaveLength(0);expect(tx.draft.pendingWindows).toHaveLength(0);const committed=tx.commit();expect(committed.events.some(event=>event.eventType==="judgment.finalized")).toBe(true);});
});
