import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {beginJudgment,finalizeJudgment,replaceJudgmentCard} from "./judgment.js";import {JudgmentInterventionSession} from "./judgmentIntervention.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});const initial=()=>createInitialSetup(ruleset,{gameId:"judgment",firstSeat:1,seed:43,usersBySeat:users,characterIdsBySeat:characters});const ready=()=>{let state=initial();for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;return state;};
describe("real card judgment",()=>{
 it("reveals a real card and finalizes its printed color",()=>{const begun=beginJudgment(initial(),ruleset,{controllerSeat:1,sourceRef:"weapon:test",purpose:"critical",matchColors:["white","red"]}),frame=begun.state.resolutionStack[0]!,cardRef=frame.context.cardRef as string,color=frame.context.printedColor;expect(begun.state.cards[cardRef]!.zoneRef).toBe("resolving");const result=finalizeJudgment(begun.state);expect(result.state.resolutionStack).toHaveLength(0);expect(result.state.cards[cardRef]!.zoneRef).toBe("discardPile");expect(result.events.find(event=>event.eventType==="judgment.finalized")?.payload).toMatchObject({printedColor:color,finalColor:color});});
 it("discards the old card before revealing a replacement",()=>{const begun=beginJudgment(initial(),ruleset,{controllerSeat:1,sourceRef:null,purpose:"status",matchColors:["blue"]}).state,oldRef=begun.resolutionStack[0]!.context.cardRef as string,result=replaceJudgmentCard(begun,ruleset),newRef=result.state.resolutionStack[0]!.context.cardRef as string;expect(result.state.cards[oldRef]!.zoneRef).toBe("discardPile");expect(result.state.cards[newRef]!.zoneRef).toBe("resolving");expect(result.events[0]?.eventType).toBe("card.moved");});
 it("can explicitly override only the final result without changing the real card",()=>{const begun=beginJudgment(initial(),ruleset,{controllerSeat:1,sourceRef:null,purpose:"critical",matchColors:["red"]}).state,cardRef=begun.resolutionStack[0]!.context.cardRef as string,result=finalizeJudgment(begun,"red");expect(result.events.map(event=>event.eventType)).toContain("judgment.matched");expect(result.events.find(event=>event.eventType==="judgment.finalized")?.payload).toMatchObject({finalColor:"red",overridden:true});expect(result.state.cards[cardRef]!.zoneRef).toBe("discardPile");});
 it("records a non-match when both deck and discard are empty",()=>{const state=initial();for(const zoneRef of ["drawPile","discardPile"]){const refs=state.zones[zoneRef]!.orderedCardRefs.splice(0);state.zones.outsideDeck!.orderedCardRefs.push(...refs);for(const ref of refs)state.cards[ref]!.zoneRef="outsideDeck";}const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["white"]});expect(begun.state.resolutionStack[0]!.context.status).toBe("noCard");expect(finalizeJudgment(begun.state).events.map(event=>event.eventType)).toContain("judgment.notMatched");});
 it("grants intervention priority counterclockwise and finalizes after four consecutive passes",()=>{const begun=beginJudgment(ready(),ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["white"]},900),session=new JudgmentInterventionSession(begun.state),priorities:number[]=[];for(const seat of [1,2,3,4] as const){const window=session.state.pendingWindows.find(item=>item.kind==="judgmentIntervention")!;priorities.push(window.prioritySeat);const command={commandId:`pass-${seat}`,gameId:session.state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:`u${seat}`,promptId:window.promptId,offerId:window.legalOfferIds[0]!},result=session.handle(command);expect(result.accepted).toBe(true);expect(session.handle(command)).toEqual(result);}expect(priorities).toEqual([1,2,3,4]);expect(session.state.pendingWindows).toHaveLength(0);expect(session.state.resolutionStack).toHaveLength(0);expect(session.state.zones.resolving!.orderedCardRefs).toHaveLength(0);});
 it("reopens intervention from the active seat after replacing the real card",()=>{const state=ready();state.activeSeat=3;const begun=beginJudgment(state,ruleset,{controllerSeat:1,sourceRef:null,purpose:"branch",matchColors:["blue"]},900).state,oldRef=begun.resolutionStack[0]!.context.cardRef as string,session=new JudgmentInterventionSession(begun),window=session.state.pendingWindows.find(item=>item.kind==="judgmentIntervention")!;session.handle({commandId:"pass-3",gameId:state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u3",promptId:window.promptId,offerId:window.legalOfferIds[0]!});const replaced=replaceJudgmentCard(session.state,ruleset,950);expect(replaced.state.cards[oldRef]!.zoneRef).toBe("discardPile");expect(replaced.state.pendingWindows[0]).toMatchObject({kind:"judgmentIntervention",prioritySeat:3,deadlineAt:950,context:{passedSeats:[]}});});
});
