import {finalizeJudgment,type PrintedColor} from "./judgment.js";
import {shuffleWithSource} from "./random.js";
import type {AuthoritativeGameState} from "./state.js";
import type {DomainEvent} from "./types.js";

export interface JudgmentDesignationCommand {commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string}
export type JudgmentDesignationResult={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
const activeWindow=(state:AuthoritativeGameState)=>state.pendingWindows.find(item=>item.kind==="judgmentDesignation");
const offerColor=(offerId:string):PrintedColor|null=>{const match=/^offer:judgment-designation:(white|green|blue|orange|red):/.exec(offerId);return match?match[1] as PrintedColor:null;};

export class JudgmentDesignationSession{
  #state:AuthoritativeGameState;readonly #results=new Map<string,JudgmentDesignationResult>();constructor(state:AuthoritativeGameState){this.#state=state;}get state(){return this.#state;}
  handle(command:JudgmentDesignationCommand):JudgmentDesignationResult{const prior=this.#results.get(command.commandId);if(prior)return structuredClone(prior);const reject=(reasonCode:string,refreshRequired:boolean):JudgmentDesignationResult=>{const result={accepted:false as const,commandId:command.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired};this.#results.set(command.commandId,result);return structuredClone(result);};if(command.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(command.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const window=activeWindow(this.#state);if(!window||window.promptId!==command.promptId)return reject("PROMPT_CLOSED",true);const player=this.#state.players.find(item=>item.userId===command.actorUserId);if(!player||player.seat!==window.prioritySeat)return reject("NOT_YOUR_PRIORITY",false);if(!window.legalOfferIds.includes(command.offerId))return reject("OFFER_EXPIRED",true);const color=offerColor(command.offerId),legalColors=Array.isArray(window.context?.legalColors)?window.context.legalColors:[];if(!color||!legalColors.includes(color))return reject("DESIGNATED_COLOR_INVALID",false);const committed=finalizeJudgment(this.#state,color);this.#state=committed.state;const result={accepted:true as const,commandId:command.commandId,previousRevision:committed.previousRevision,stateRevision:committed.state.stateRevision,events:committed.events};this.#results.set(command.commandId,result);return structuredClone(result);}
  handleTimeout(commandId:string):JudgmentDesignationResult{const window=activeWindow(this.#state);if(!window)return{accepted:false,commandId,stateRevision:this.#state.stateRevision,reasonCode:"PROMPT_CLOSED",refreshRequired:true};const candidates=[...window.legalOfferIds],randomSeq=this.#state.randomSource.nextRandomSeq,shuffled=shuffleWithSource(candidates,this.#state.randomSource);this.#state.randomSource=shuffled.source;const offerId=shuffled.value[0]!;this.#state.randomHistory.push({randomSeq,purpose:"timeout.judgmentDesignation",candidateRefs:candidates,resultRefs:[offerId]});return this.handle({commandId,gameId:this.#state.gameId,expectedStateRevision:this.#state.stateRevision,actorUserId:this.#state.players.find(item=>item.seat===window.prioritySeat)!.userId,promptId:window.promptId,offerId});}
}
