import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {commitAttack} from "./attack.js";import {grantGuaranteedCritical} from "./guaranteedCritical.js";import {activateRoundShield} from "./killInvalidation.js";import {resolvePhaseBody} from "./phaseBody.js";import {setWeaponPreselection} from "./preselection.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";import type {JsonValue} from "./types.js";import {advanceTimeline} from "./timeline.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function ready(){let state=createInitialSetup(ruleset,{gameId:"kill-invalidation",firstSeat:1,seed:61,usersBySeat:users,characterIdsBySeat:characters});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;state.phase="play";state.phaseMode="manual";state.phaseBoundary="body";state.phaseBodyResolved=false;state.players[0]!.limits.attackCountRemaining=1;return resolvePhaseBody(state,ruleset,1000).state;}
function refFor(state:AuthoritativeGameState,id:string){return Object.values(state.cards).find(card=>card.templateId===id)!.cardRef;}
function relocate(state:AuthoritativeGameState,ref:string,to:string){const card=state.cards[ref]!,from=state.zones[card.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);state.zones[to]!.orderedCardRefs.push(ref);card.zoneRef=to;card.ownerSeat=state.zones[to]!.ownerSeat;card.controllerSeat=state.zones[to]!.ownerSeat;card.faceUp=state.zones[to]!.zoneType!=="hand";}
function prepareAttack(state:AuthoritativeGameState,killId:string){const weapon=refFor(state,"weapon.w11"),kill=refFor(state,killId);relocate(state,weapon,"weapon:1:1");relocate(state,kill,"hand:1");state.cards[weapon]!.runtime.chargeProgress=1;state=setWeaponPreselection(state,1,"weapon:1:1",null,ruleset).state;return{state,weapon,kill};}
describe("kill invalidation",()=>{
 it("keeps paid costs spent and preserves charge when Shield invalidates a white Kill",()=>{let state=ready();const armor=refFor(state,"armor.a04");relocate(state,armor,"armor:2");const prepared=prepareAttack(state,"basic.kill.white");state=prepared.state;const result=commitAttack(state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[prepared.kill]});expect(result.state.combat.attack).toBeNull();expect(result.state.cards[prepared.kill]!.zoneRef).toBe("discardPile");expect(result.state.players[0]!.limits.attackCountRemaining).toBe(0);expect(result.state.cards[prepared.weapon]!.runtime.chargeProgress).toBe(1);expect(result.state.pendingWindows.some(window=>window.kind==="playPhaseAction")).toBe(true);expect(result.events.map(event=>event.eventType)).toContain("attack.invalidated");expect(result.events.map(event=>event.eventType)).not.toContain("attack.commit");});
 it("does not apply Shield while its equipment effects are disabled",()=>{let state=ready();const armor=refFor(state,"armor.a04");relocate(state,armor,"armor:2");state.players[1]!.markers.equipmentEffectsDisabled=true;const prepared=prepareAttack(state,"basic.kill.blue");const result=commitAttack(prepared.state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[prepared.kill]});expect(result.state.combat.attack).not.toBeNull();expect(result.state.cards[prepared.weapon]!.runtime.chargeProgress).toBe(0);});
 it("keeps a Round Shield color secret until its first matched invalidation",()=>{let state=ready();const armor=refFor(state,"armor.a08");relocate(state,armor,"armor:2");state.activeSeat=2;state.players[1]!.limits.attackCountRemaining=1;state=activateRoundShield(state,2,"red").state;const lockBefore=(state.players[1]!.markers.roundShieldLocks as Array<Record<string,unknown>>)[0]!;expect(lockBefore.revealed).toBe(false);state.activeSeat=1;const prepared=prepareAttack(state,"basic.kill.red"),result=commitAttack(prepared.state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[prepared.kill]});expect(result.state.combat.attack).toBeNull();const lockAfter=(result.state.players[1]!.markers.roundShieldLocks as Array<Record<string,unknown>>)[0]!;expect(lockAfter).toMatchObject({selectedColor:"red",revealed:true});expect(result.events.find(event=>event.eventType==="card.revealed")?.payload).toMatchObject({selectedColor:"red"});});
 it("expires Round Shield before the owner's next prepare even when prepare is skipped",()=>{let state=ready();const armor=refFor(state,"armor.a08");relocate(state,armor,"armor:2");state.activeSeat=2;state=activateRoundShield(state,2,"blue").state;state.pendingWindows=[];state.activeSeat=1;state.phase="end";state.phaseMode="automatic";state.phaseBoundary="body";state.phaseBodyResolved=true;const advanced=advanceTimeline(state,{kind:"skip",reason:"test"});expect(advanced.state.activeSeat).toBe(2);expect(advanced.state.phase).toBe("prepare");expect(advanced.state.phaseBoundary).toBe("after");expect(advanced.state.players[1]!.markers.roundShieldLocks).toBeUndefined();expect(advanced.state.durations.some(item=>item.sourceRef===armor)).toBe(false);});
 it("retains a Horn-style critical grant on invalidation and consumes it only on a committed weapon attack",()=>{let state=ready();const armor=refFor(state,"armor.a04");relocate(state,armor,"armor:2");state=grantGuaranteedCritical(state,{ownerSeat:1,sourceRef:"basic.horn.white",appliesTo:"weaponAttack",consumePolicy:"onFirstCommittedApplicableAttack",expiryPoint:"owner.currentTurn.end"}).state;const first=prepareAttack(state,"basic.kill.white"),invalid=commitAttack(first.state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[first.kill]});expect(invalid.state.players[0]!.markers.guaranteedCriticalGrants).toBeDefined();relocate(invalid.state,armor,"outsideDeck");invalid.state.players[0]!.limits.attackCountRemaining=1;const red=refFor(invalid.state,"basic.kill.red");relocate(invalid.state,red,"hand:1");const committed=commitAttack(invalid.state,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[red]});expect(committed.state.players[0]!.markers.guaranteedCriticalGrants).toBeUndefined();expect(committed.state.combat.attack as Record<string,JsonValue>).toMatchObject({guaranteedCritical:true,critical:true});expect(committed.events.map(event=>event.eventType)).toContain("critical.consumed");});
});
