import type {LoadedRuleset} from "../ruleset/types.js";
import {takeTopCardsToResolvingInTransaction} from "./deck.js";
import {calculateEffectiveDistance} from "./distance.js";
import {weaponSlotRefs} from "./preselection.js";
import type {AuthoritativeGameState,Seat} from "./state.js";
import {validateAuthoritativeState} from "./stateValidation.js";
import {EngineTransaction} from "./transaction.js";
import type {DomainEvent} from "./types.js";
export interface LaserRainCommand{commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string;targetRef:string;killCardRef:string}
export type LaserRainResult={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
function combo(s:AuthoritativeGameState,n:Seat){const p=s.players.find(x=>x.seat===n)!;if(p.initialTalentIds.includes("talent.combo_up"))return true;if(p.markers.equipmentEffectsDisabled===true||p.statuses.some(x=>x.statusId==="status.equipmentDisabled"))return false;return s.zones[`talent:${n}`]!.orderedCardRefs.some(ref=>s.cards[ref]?.templateId==="talent.combo_up")}
export class LaserRainSession{#state:AuthoritativeGameState;#results=new Map<string,LaserRainResult>();constructor(s:AuthoritativeGameState,private r:LoadedRuleset){this.#state=s}get state(){return this.#state}handle(c:LaserRainCommand):LaserRainResult{
 const old=this.#results.get(c.commandId);if(old)return structuredClone(old);const reject=(reasonCode:string,refreshRequired:boolean):LaserRainResult=>{const q={accepted:false as const,commandId:c.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired};this.#results.set(c.commandId,q);return structuredClone(q)};
 if(c.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(c.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const actor=this.#state.players.find(x=>x.userId===c.actorUserId),w=this.#state.pendingWindows.find(x=>x.promptId===c.promptId&&x.kind==="playPhaseAction");if(!actor||!w||w.prioritySeat!==actor.seat||this.#state.activeSeat!==actor.seat)return reject("NOT_YOUR_PRIORITY",false);if(c.offerId!=="offer:weapon-w12-display")return reject("OFFER_EXPIRED",true);
 const slot=this.#state.preselection[actor.seat].weaponSlot,weaponRef=slot&&weaponSlotRefs(actor.seat).includes(slot)?this.#state.zones[slot]!.orderedCardRefs[0]:undefined,weapon=weaponRef?this.#state.cards[weaponRef]:undefined;if(!weapon||weapon.templateId!=="weapon.w12")return reject("WEAPON_NOT_AVAILABLE",true);if(actor.markers.equipmentEffectsDisabled===true||actor.statuses.some(x=>x.statusId==="status.equipmentDisabled"))return reject("WEAPON_INEFFECTIVE",true);const charge=Number(weapon.runtime.chargeProgress??0);if(charge!==1&&charge!==2)return reject("WEAPON_RESOLUTION_MODE_INVALID",true);
 if(!weaponRef)return reject("WEAPON_NOT_AVAILABLE",true);
 const targetSeat=Number(c.targetRef.split(":")[1])as Seat,target=this.#state.players.find(x=>x.seat===targetSeat);if(!target||target.presence!=="inPlay"||target.lifeState==="eliminated"||calculateEffectiveDistance(this.#state,actor.seat,targetSeat)>2)return reject("TARGET_NO_LONGER_LEGAL",true);if(!this.#state.zones[`hand:${actor.seat}`]!.orderedCardRefs.includes(c.killCardRef)||!this.#state.cards[c.killCardRef]!.templateId.startsWith("basic.kill."))return reject("ATTACK_KILL_COST_INVALID",false);const available=Number(actor.limits[this.r.settings.combat.attackCountLimitId]??0);if(available<1)return reject("ATTACK_COUNT_UNPAYABLE",true);
 const tx=new EngineTransaction(this.#state),d=tx.draft,p=d.players.find(x=>x.seat===actor.seat)!,source=d.cards[weaponRef]!;d.pendingWindows=d.pendingWindows.filter(x=>x.promptId!==w.promptId);const hand=d.zones[`hand:${actor.seat}`]!,i=hand.orderedCardRefs.indexOf(c.killCardRef);hand.orderedCardRefs.splice(i,1);d.zones.discardPile!.orderedCardRefs.push(c.killCardRef);Object.assign(d.cards[c.killCardRef]!,{zoneRef:"discardPile",ownerSeat:null,controllerSeat:null,faceUp:true});p.limits[this.r.settings.combat.attackCountLimitId]=available-1;source.runtime.chargeProgress=0;
 const revealCount=(charge===1?5:7)+(combo(d,actor.seat)?2:0),revealed=takeTopCardsToResolvingInTransaction(tx,revealCount,"weapon.w12.display"),colors=new Map((this.r.documents.get("cards.json")as{items:Array<{cardId:string;color:string}>}).items.map(x=>[x.cardId,x.color])),matches=charge===1?new Set(["blue","red"]):new Set(["blue","orange","red"]);let hits=0;
 for(const ref of revealed.cardRefs){d.cards[ref]!.faceUp=true;const color=colors.get(d.cards[ref]!.templateId)??"unknown";tx.emit("card.revealed",{cardRef:ref,color,sourceRef:weaponRef,weaponId:"weapon.w12"});if(matches.has(color)){hits++;d.scheduledEffects.push({scheduledId:`scheduled:w12:${d.stateRevision+1}:${hits}`,sourceRef:weaponRef,controllerSeat:actor.seat,executeAt:"immediate.damagePipeline",effect:{op:"createDamage",targetRef:c.targetRef,amount:1,damageType:"normal",element:"none",attackType:"field",isAdditional:false},cancelled:false})}d.zones.resolving!.orderedCardRefs.splice(d.zones.resolving!.orderedCardRefs.indexOf(ref),1);d.zones.discardPile!.orderedCardRefs.push(ref);Object.assign(d.cards[ref]!,{zoneRef:"discardPile",ownerSeat:null,controllerSeat:null,faceUp:true})}
 d.scheduledEffects.push({scheduledId:`scheduled:w12:resume:${d.stateRevision+1}`,sourceRef:weaponRef,controllerSeat:actor.seat,executeAt:"immediate.damagePipeline",effect:{op:"resumePlayWindow",seat:actor.seat,deadlineAt:w.deadlineAt},cancelled:false});tx.emit("weapon.resolution.committed",{weaponId:"weapon.w12",weaponRef,charge,revealCount,matchedCount:hits,targetRef:c.targetRef});const done=tx.commit();done.state.history.domainEvents.push(...done.events);validateAuthoritativeState(done.state);this.#state=done.state;const result={accepted:true as const,commandId:c.commandId,previousRevision:c.expectedStateRevision,stateRevision:this.#state.stateRevision,events:done.events};this.#results.set(c.commandId,result);return structuredClone(result)
}}
