import type { LoadedRuleset } from "../ruleset/types.js";
import type { AuthoritativeGameState, Seat } from "./state.js";
import { EngineTransaction } from "./transaction.js";
import { moveCardInTransaction } from "./zoneMovement.js";
import { validateAuthoritativeState } from "./stateValidation.js";
import type { DomainEvent, JsonValue } from "./types.js";
import { shuffleWithSource } from "./random.js";

const CHARACTER="character.miner",ABILITY="skill.miner.dig_for_survival";
const turnKey=(s:AuthoritativeGameState,seat:Seat)=>`${s.round}:${seat}:${[...s.history.domainEvents].reverse().find((e)=>e.eventType==="turn.start"&&(e.payload as Record<string,JsonValue>).seat===seat)?.eventSeq??0}`;
export function isUnderground(s:AuthoritativeGameState,seat:Seat){return s.players.find((x)=>x.seat===seat)?.markers["miner.underground"]===true}
export function enterUnderground(tx:EngineTransaction<AuthoritativeGameState>,seat:Seat){const p=tx.draft.players.find((x)=>x.seat===seat)!;if(p.markers["miner.underground"]===true)return;p.markers["miner.underground"]=true;p.markers["miner.undergroundIronShield"]=1;p.ironShield+=1;tx.emit("status.applied",{ownerSeat:seat,targetRef:`character:${seat}`,sourceSeat:seat,result:"applied",statusId:"status.underground",statusRef:null,durationId:null});tx.emit("ironShield.changed",{seat,add:1,value:p.ironShield,sourceId:ABILITY})}
export function exitUnderground(tx:EngineTransaction<AuthoritativeGameState>,seat:Seat,reason:string){const p=tx.draft.players.find((x)=>x.seat===seat)!;if(p.markers["miner.underground"]!==true)return false;delete p.markers["miner.underground"];const contribution=Number(p.markers["miner.undergroundIronShield"]??0);delete p.markers["miner.undergroundIronShield"];p.ironShield=Math.max(0,p.ironShield-contribution);tx.emit("status.expired",{ownerSeat:seat,statusId:"status.underground",reason});tx.emit("ironShield.changed",{seat,add:-contribution,value:p.ironShield,sourceId:ABILITY});return true}
export function openMinerSourceDismantle(tx:EngineTransaction<AuthoritativeGameState>,r:LoadedRuleset,minerSeat:Seat,sourceSeat:Seat,deadlineAt:number,reason:string){const refs=Object.values(tx.draft.zones).filter((z)=>z.ownerSeat===sourceSeat&&!["outsideDeck","removedFromGame","resolving"].includes(z.zoneType)&&(z.zoneType!=="bossSlot"||r.settings.boss.allowGenericDismantle)).flatMap((z)=>z.orderedCardRefs);if(!refs.length)return false;const promptId=`prompt:miner-source-dismantle:${tx.draft.stateRevision+1}:${minerSeat}`;tx.draft.pendingWindows.unshift({promptId,kind:"minerSourceDismantle",prioritySeat:minerSeat,mandatory:true,deadlineAt,timeoutPolicy:"randomLegal",legalOfferIds:["offer:miner-source-dismantle"],context:{legalCardRefs:refs,sourceSeat,reason}});tx.emit("choice.requested",{kind:"minerSourceDismantle",promptId,seat:minerSeat,sourceSeat,legalCardRefs:refs});return true}
function sourceSeatFromRef(s:AuthoritativeGameState,sourceRef:string|null|undefined):Seat|null{const direct=/^character:([1-4])$/.exec(sourceRef??"");if(direct)return Number(direct[1]) as Seat;const card=sourceRef?s.cards[sourceRef]:undefined;return card?.controllerSeat??card?.ownerSeat??null}
function isCurrentSourceCardLegal(s:AuthoritativeGameState,r:LoadedRuleset,cardRef:string,sourceSeat:Seat){const card=s.cards[cardRef],zone=card?s.zones[card.zoneRef]:undefined;return Boolean(card&&zone&&zone.ownerSeat===sourceSeat&&!['outsideDeck','removedFromGame','resolving'].includes(zone.zoneType)&&(zone.zoneType!=="bossSlot"||r.settings.boss.allowGenericDismantle)&&zone.orderedCardRefs.includes(cardRef))}
export function handleMinerOffTurnActivePlay(tx:EngineTransaction<AuthoritativeGameState>,r:LoadedRuleset,input:{seat:Seat;respondsToAttackOrDamage:boolean;sourceRef?:string|null;sourceSeat?:Seat|null;deadlineAt?:number;reason:string}){if(tx.draft.activeSeat===input.seat||!isUnderground(tx.draft,input.seat))return false;exitUnderground(tx,input.seat,input.reason);const sourceSeat=input.sourceSeat??sourceSeatFromRef(tx.draft,input.sourceRef);if(input.respondsToAttackOrDamage&&sourceSeat)openMinerSourceDismantle(tx,r,input.seat,sourceSeat,input.deadlineAt??0,input.reason);tx.emit("miner.underground.exitTriggered",{seat:input.seat,reason:input.reason,respondsToAttackOrDamage:input.respondsToAttackOrDamage,sourceSeat});return true}
export function openMinerDigAtPlayEnd(tx:EngineTransaction<AuthoritativeGameState>,deadlineAt:number){const s=tx.draft,seat=s.activeSeat!,p=s.players.find((x)=>x.seat===seat)!,key=turnKey(s,seat);if(p.characterId!==CHARACTER||p.lifeState!=="alive"||p.presence!=="inPlay"||!p.skillIds.includes(ABILITY)||p.markers["miner.digDecisionTurnKey"]===key||isUnderground(s,seat))return false;const refs=[...s.zones[`hand:${seat}`]!.orderedCardRefs];if(!refs.length){p.markers["miner.digDecisionTurnKey"]=key;return false}const promptId=`prompt:miner-dig:${s.stateRevision+1}:${seat}`;s.pendingWindows.push({promptId,kind:"minerDigAtPlayEnd",prioritySeat:seat,mandatory:false,deadlineAt,timeoutPolicy:"pass",legalOfferIds:["offer:miner-dig:pass","offer:miner-dig:activate"],context:{legalCardRefs:refs,turnKey:key}});tx.emit("choice.requested",{kind:"minerDigAtPlayEnd",promptId,seat,legalCardRefs:refs});return true}
export function openMinerNaturalExitAtPrepare(tx:EngineTransaction<AuthoritativeGameState>,deadlineAt:number){const s=tx.draft,seat=s.activeSeat!;if(!isUnderground(s,seat))return false;exitUnderground(tx,seat,"owner.prepare.before");const targets=s.players.filter((x)=>x.presence==="inPlay"&&x.lifeState!=="eliminated").map((x)=>`character:${x.seat}`),promptId=`prompt:miner-natural-exit:${s.stateRevision+1}:${seat}`;s.pendingWindows.push({promptId,kind:"minerNaturalExitTarget",prioritySeat:seat,mandatory:true,deadlineAt,timeoutPolicy:"randomLegal",legalOfferIds:targets.map((x)=>`offer:miner-natural-exit:${x}`),context:{legalTargetRefs:targets}});tx.emit("choice.requested",{kind:"minerNaturalExitTarget",promptId,seat,legalTargetRefs:targets});return true}
export interface MinerCommand{commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string;cardRef?:string}
type Result={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
export class MinerSession{#state:AuthoritativeGameState;#results=new Map<string,Result>();constructor(state:AuthoritativeGameState,private r:LoadedRuleset){this.#state=state}get state(){return this.#state}handle(c:MinerCommand):Result{const prior=this.#results.get(c.commandId);if(prior)return structuredClone(prior);const reject=(reasonCode:string,refreshRequired:boolean):Result=>{const x={accepted:false as const,commandId:c.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired};this.#results.set(c.commandId,x);return structuredClone(x)};if(c.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(c.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const w=this.#state.pendingWindows.find((x)=>x.promptId===c.promptId),actor=this.#state.players.find((x)=>x.userId===c.actorUserId);if(!w)return reject("PROMPT_CLOSED",true);if(!actor||actor.seat!==w.prioritySeat)return reject("NOT_YOUR_PRIORITY",false);if(!w.legalOfferIds.includes(c.offerId))return reject("OFFER_EXPIRED",true);const tx=new EngineTransaction(this.#state);tx.draft.pendingWindows=tx.draft.pendingWindows.filter((x)=>x.promptId!==w.promptId);
 if(w.kind==="minerDigAtPlayEnd"){const p=tx.draft.players.find((x)=>x.seat===actor.seat)!;p.markers["miner.digDecisionTurnKey"]=String(w.context?.turnKey);if(c.offerId.endsWith(":activate")){const legal=Array.isArray(w.context?.legalCardRefs)?w.context.legalCardRefs:[];if(!c.cardRef||!legal.includes(c.cardRef)||tx.draft.cards[c.cardRef]?.zoneRef!==`hand:${actor.seat}`)return reject("COST_CARD_NO_LONGER_LEGAL",true);moveCardInTransaction(tx,{cardRef:c.cardRef,toZoneRef:"discardPile",moveKind:"discard",faceUp:true});enterUnderground(tx,actor.seat);tx.emit("ability.activation.committed",{seat:actor.seat,abilityId:ABILITY,cardRef:c.cardRef});}else if(c.cardRef)return reject("SELECTION_INVALID",false);tx.emit("choice.resolved",{seat:actor.seat,kind:w.kind,result:c.offerId.endsWith(":activate")?"activate":"pass"});}
 else if(w.kind==="minerNaturalExitTarget"){const targetRef=c.offerId.slice("offer:miner-natural-exit:".length),legal=Array.isArray(w.context?.legalTargetRefs)?w.context.legalTargetRefs:[];if(!legal.includes(targetRef))return reject("TARGET_NO_LONGER_LEGAL",true);tx.draft.scheduledEffects.unshift({scheduledId:`scheduled:miner-natural-exit:${tx.draft.stateRevision+1}:${actor.seat}`,sourceRef:`character:${actor.seat}`,controllerSeat:actor.seat,executeAt:"immediate.damagePipeline",effect:{op:"createDamage",targetRef,amount:1,damageType:"normal",element:"none",attackType:"field",deliveryType:"direct",sourceAbilityId:ABILITY},cancelled:false});tx.emit("ability.effect.queued",{seat:actor.seat,abilityId:ABILITY,targetRef,amount:1});}
 else if(w.kind==="minerSourceDismantle"){const legal=Array.isArray(w.context?.legalCardRefs)?w.context.legalCardRefs:[],sourceSeat=Number(w.context?.sourceSeat) as Seat;if(!c.cardRef||!legal.includes(c.cardRef)||!isCurrentSourceCardLegal(tx.draft,this.r,c.cardRef,sourceSeat))return reject("CARD_NO_LONGER_LEGAL",true);moveCardInTransaction(tx,{cardRef:c.cardRef,toZoneRef:"discardPile",moveKind:"dismantle",faceUp:true});tx.emit("card.dismantled",{cardRef:c.cardRef,sourceSeat:actor.seat,targetSeat:sourceSeat,sourceRef:ABILITY,reason:String(w.context?.reason)});}
 else return reject("PROMPT_KIND_INVALID",true);const committed=tx.commit();committed.state.history.domainEvents.push(...committed.events);validateAuthoritativeState(committed.state);this.#state=committed.state;const result={accepted:true as const,commandId:c.commandId,previousRevision:committed.previousRevision,stateRevision:committed.state.stateRevision,events:committed.events};this.#results.set(c.commandId,result);return structuredClone(result)}handleTimeout(commandId:string){const w=this.#state.pendingWindows.find((x)=>x.kind==="minerDigAtPlayEnd"||x.kind==="minerNaturalExitTarget"||x.kind==="minerSourceDismantle");if(!w)return{accepted:false as const,commandId,stateRevision:this.#state.stateRevision,reasonCode:"PROMPT_CLOSED",refreshRequired:true};if(w.kind==="minerDigAtPlayEnd")return this.handle({commandId,gameId:this.#state.gameId,expectedStateRevision:this.#state.stateRevision,actorUserId:this.#state.players.find((x)=>x.seat===w.prioritySeat)!.userId,promptId:w.promptId,offerId:"offer:miner-dig:pass"});const candidates=w.kind==="minerNaturalExitTarget"?[...w.legalOfferIds]:(Array.isArray(w.context?.legalCardRefs)?w.context.legalCardRefs.filter((x):x is string=>typeof x==="string"):[]),randomSeq=this.#state.randomSource.nextRandomSeq,shuffled=shuffleWithSource(candidates,this.#state.randomSource),chosen=shuffled.value[0]!;this.#state.randomSource=shuffled.source;this.#state.randomHistory.push({randomSeq,purpose:`timeout.${w.kind}`,candidateRefs:candidates,resultRefs:[chosen]});return this.handle({commandId,gameId:this.#state.gameId,expectedStateRevision:this.#state.stateRevision,actorUserId:this.#state.players.find((x)=>x.seat===w.prioritySeat)!.userId,promptId:w.promptId,offerId:w.kind==="minerNaturalExitTarget"?chosen:"offer:miner-source-dismantle",...(w.kind==="minerSourceDismantle"?{cardRef:chosen}:{})})}}
