import{resolve}from"node:path";import{beforeAll,describe,expect,it}from"vitest";import{loadFrozenRuleset}from"../ruleset/loadRuleset.js";import type{LoadedRuleset}from"../ruleset/types.js";import{createInitialSetup,resolveInitialRedraw}from"./setup.js";import{advanceTimeline}from"./timeline.js";import{MinerSession,enterUnderground,isUnderground}from"./miner.js";import{EngineTransaction}from"./transaction.js";import{executeNextImmediateDamageEffect}from"./directDamage.js";import{openAttackResponse}from"./response.js";
import{handleMinerOffTurnActivePlay}from"./miner.js";
let ruleset:LoadedRuleset;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"))});
function ready(){let s=createInitialSetup(ruleset,{gameId:"miner",firstSeat:1,seed:449,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.miner",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;return s}
function underground(){const tx=new EngineTransaction(ready());enterUnderground(tx,1);const c=tx.commit();c.state.history.domainEvents.push(...c.events);return c.state}
describe("Miner underground",()=>{
 it("offers at play end, pays exactly one hand card and gains one iron shield",()=>{let s=ready();s.activeSeat=1;s.phase="play";s.phaseMode="manual";s.phaseBoundary="body";s.phaseBodyResolved=true;s.pendingWindows=[];s=advanceTimeline(s,{kind:"normal"},ruleset,500).state;const w=s.pendingWindows[0]!,card=s.zones["hand:1"]!.orderedCardRefs[0]!,session=new MinerSession(s,ruleset);expect(w.kind).toBe("minerDigAtPlayEnd");expect(session.handle({commandId:"dig",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:"offer:miner-dig:activate",cardRef:card}).accepted).toBe(true);expect(session.state.players[0]).toMatchObject({ironShield:1,markers:{"miner.underground":true}});expect(session.state.cards[card]!.zoneRef).toBe("discardPile")});
 it("invalidates a paid ranged attack without asking the Miner to respond",()=>{let s=underground();s.combat.currentTargetRef="character:1";s.combat.attack={attackId:"ranged",attackerSeat:2,targetRefs:["character:1"],attackTypes:["ranged"],status:"committed"};const out=openAttackResponse(s,ruleset,600);expect(out.state.pendingWindows).toHaveLength(0);expect(out.state.combat.attack).toMatchObject({status:"targetMiss",currentTargetMissReason:"status.underground"});expect(isUnderground(out.state,1)).toBe(true)});
 it("exits on actual positive damage but not zero damage",()=>{let s=underground();s.players[0]!.ironShield=0;s.players[0]!.markers["miner.undergroundIronShield"]=0;s.scheduledEffects.push({scheduledId:"zero",sourceRef:"character:2",controllerSeat:2,executeAt:"immediate.damagePipeline",effect:{op:"createDamage",targetRef:"character:1",amount:0,damageType:"normal",element:"none"},cancelled:false});s=executeNextImmediateDamageEffect(s,ruleset).state;expect(isUnderground(s,1)).toBe(true);s.scheduledEffects.push({scheduledId:"positive",sourceRef:"character:2",controllerSeat:2,executeAt:"immediate.damagePipeline",effect:{op:"createDamage",targetRef:"character:1",amount:1,damageType:"normal",element:"none"},cancelled:false});s=executeNextImmediateDamageEffect(s,ruleset).state;expect(isUnderground(s,1)).toBe(false)});
 it("naturally exits before prepare recovery, queues mandatory field damage and then resumes prepare",()=>{let s=underground();s.activeSeat=4;s.phase="end";s.phaseMode="automatic";s.phaseBoundary="body";s.phaseBodyResolved=true;s.pendingWindows=[];s=advanceTimeline(s,{kind:"normal"},ruleset,700).state;expect(s).toMatchObject({activeSeat:1,phase:"prepare",phaseBodyResolved:false});expect(isUnderground(s,1)).toBe(false);const w=s.pendingWindows[0]!,session=new MinerSession(s,ruleset);expect(w.kind).toBe("minerNaturalExitTarget");expect(session.handle({commandId:"target",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:"offer:miner-natural-exit:character:2"}).accepted).toBe(true);const before=session.state.players[1]!.shield!,damaged=executeNextImmediateDamageEffect(session.state,ruleset);expect(damaged.state.players[1]!.shield).toBe(before-1);expect(damaged.state.phase).toBe("prepare")});
 it("exits for unrelated off-turn active play without dismantling",()=>{let s=underground();s.activeSeat=2;const tx=new EngineTransaction(s);expect(handleMinerOffTurnActivePlay(tx,ruleset,{seat:1,respondsToAttackOrDamage:false,reason:"test.unrelated"})).toBe(true);const out=tx.commit().state;expect(isUnderground(out,1)).toBe(false);expect(out.pendingWindows.some((w)=>w.kind==="minerSourceDismantle")).toBe(false)});
 it("opens source dismantle for a response and rejects a card moved away after quotation",()=>{let s=underground();s.activeSeat=2;const tx=new EngineTransaction(s);handleMinerOffTurnActivePlay(tx,ruleset,{seat:1,respondsToAttackOrDamage:true,sourceSeat:2,deadlineAt:800,reason:"test.response"});s=tx.commit().state;const w=s.pendingWindows.find((x)=>x.kind==="minerSourceDismantle")!,ref=(w.context!.legalCardRefs as unknown as string[])[0]!;const from=s.zones[s.cards[ref]!.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);s.zones.resolving!.orderedCardRefs.push(ref);s.cards[ref]!.zoneRef="resolving";const session=new MinerSession(s,ruleset),result=session.handle({commandId:"stale",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:"offer:miner-source-dismantle",cardRef:ref});expect(result).toMatchObject({accepted:false,reasonCode:"CARD_NO_LONGER_LEGAL"})});
});
