import type { LoadedRuleset } from "../ruleset/types.js";
import type { AuthoritativeGameState, Seat } from "./state.js";
import { validateAuthoritativeState } from "./stateValidation.js";
import { EngineTransaction } from "./transaction.js";
import type { DomainEvent } from "./types.js";
import { moveCardInTransaction } from "./zoneMovement.js";

type MountRule={familyId:string;occupiedSlots:Array<"mountOffenseSlot"|"mountDefenseSlot">;distanceModifier:{offenseDelta:number;defenseDelta:number};dynamicDistanceModifier?:unknown};
const rules=(r:LoadedRuleset)=>(r.documents.get("nonboss-rules.json") as {effectFamilies:MountRule[]}).effectFamilies.filter(x=>x.familyId.startsWith("mount."));
const canAct=(s:AuthoritativeGameState,n:Seat)=>s.activeSeat===n&&s.phase==="play"&&s.phaseBoundary==="body"&&!s.combat.attack&&s.pendingWindows.some(x=>x.kind==="playPhaseAction"&&x.prioritySeat===n);
const zone=(slot:string,n:Seat)=>slot==="mountOffenseSlot"?`mountOffense:${n}`:`mountDefense:${n}`;

export function mountRule(r:LoadedRuleset,id:string){return rules(r).find(x=>x.familyId===id)??null}
export function equippedMountRefs(s:AuthoritativeGameState,n:Seat){return [...new Set([...(s.zones[`mountOffense:${n}`]?.orderedCardRefs??[]),...(s.zones[`mountDefense:${n}`]?.orderedCardRefs??[])])];}
export function buildMountEquipOffers(s:AuthoritativeGameState,r:LoadedRuleset,n:Seat){
 if(!canAct(s,n))return[];
 return (s.zones[`hand:${n}`]?.orderedCardRefs??[]).flatMap(cardRef=>{const rule=mountRule(r,s.cards[cardRef]!.templateId);if(!rule)return[];const occupied=new Set(rule.occupiedSlots.map(x=>zone(x,n))),replaced=equippedMountRefs(s,n).filter(ref=>{const c=s.cards[ref]!,old=mountRule(r,c.templateId);return old?.occupiedSlots.some(x=>occupied.has(zone(x,n)));});return[{offerId:`offer:mount-equip:${cardRef}`,cardRef,replacedCardRefs:replaced,toZoneRef:zone(rule.occupiedSlots[0]!,n),occupiedZoneRefs:[...occupied]}];});
}
export function buildMountDiscardOffers(s:AuthoritativeGameState,n:Seat){return canAct(s,n)?equippedMountRefs(s,n).map(cardRef=>({offerId:`offer:mount-discard:${cardRef}`,cardRef})):[];}
type Command={commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string;cardRef:string};
type Result={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
abstract class Session{protected current:AuthoritativeGameState;private results=new Map<string,Result>();constructor(s:AuthoritativeGameState){this.current=s}get state(){return this.current}protected run(c:Command,offer:(n:Seat)=>{cardRef:string}|undefined,apply:(tx:EngineTransaction<AuthoritativeGameState>,n:Seat)=>void):Result{const old=this.results.get(c.commandId);if(old)return structuredClone(old);const no=(reasonCode:string,refreshRequired:boolean):Result=>({accepted:false,commandId:c.commandId,stateRevision:this.current.stateRevision,reasonCode,refreshRequired});if(c.gameId!==this.current.gameId)return no("GAME_NOT_FOUND",false);if(c.expectedStateRevision!==this.current.stateRevision)return no("STALE_REVISION",true);const actor=this.current.players.find(x=>x.userId===c.actorUserId),window=actor&&this.current.pendingWindows.find(x=>x.promptId===c.promptId&&x.prioritySeat===actor.seat),found=actor&&offer(actor.seat);if(!actor||!window)return no("NOT_YOUR_PRIORITY",false);if(!found||found.cardRef!==c.cardRef)return no("OFFER_EXPIRED",true);const tx=new EngineTransaction(this.current);apply(tx,actor.seat);const out=tx.commit();out.state.history.domainEvents.push(...out.events);validateAuthoritativeState(out.state);this.current=out.state;const result:Result={accepted:true,commandId:c.commandId,previousRevision:out.previousRevision,stateRevision:out.state.stateRevision,events:out.events};this.results.set(c.commandId,result);return structuredClone(result);}}
export class MountEquipSession extends Session{constructor(s:AuthoritativeGameState,private r:LoadedRuleset){super(s)}handle(c:Command){return this.run(c,n=>buildMountEquipOffers(this.current,this.r,n).find(x=>x.offerId===c.offerId), (tx,n)=>{const o=buildMountEquipOffers(tx.draft,this.r,n).find(x=>x.offerId===c.offerId)!,rule=mountRule(this.r,tx.draft.cards[c.cardRef]!.templateId)!;for(const ref of o.replacedCardRefs)moveCardInTransaction(tx,{cardRef:ref,toZoneRef:"discardPile",moveKind:"replace",faceUp:true});moveCardInTransaction(tx,{cardRef:c.cardRef,toZoneRef:o.toZoneRef,moveKind:"equip",faceUp:true});Object.assign(tx.draft.cards[c.cardRef]!.runtime,{mountOccupiedZoneRefs:o.occupiedZoneRefs,mountOffenseDelta:rule.distanceModifier.offenseDelta,mountDefenseDelta:rule.distanceModifier.defenseDelta,mountDynamicTalentDistance:rule.familyId==="mount.m11"});tx.emit("card.equipped",{seat:n,cardRef:c.cardRef,cardId:tx.draft.cards[c.cardRef]!.templateId,zoneRef:o.toZoneRef,occupiedZoneRefs:o.occupiedZoneRefs,replacedCardRefs:o.replacedCardRefs});});}}
export class MountDiscardSession extends Session{handle(c:Command){return this.run(c,n=>buildMountDiscardOffers(this.current,n).find(x=>x.offerId===c.offerId), (tx,n)=>{moveCardInTransaction(tx,{cardRef:c.cardRef,toZoneRef:"discardPile",moveKind:"discard",faceUp:true});tx.emit("card.discarded",{seat:n,cardRef:c.cardRef,cardId:tx.draft.cards[c.cardRef]!.templateId,category:"mount"});});}}
