import{resolve}from"node:path";import{beforeAll,describe,expect,it}from"vitest";import{loadFrozenRuleset}from"../ruleset/loadRuleset.js";import type{LoadedRuleset}from"../ruleset/types.js";import{applyDirectDamageInTransaction}from"./damage.js";import{buildNecromancerMarkOffers,NecromancerMarkSession,tickNecromancerMarksAtPrepare}from"./necromancer.js";import{createInitialSetup,resolveInitialRedraw}from"./setup.js";import{EngineTransaction}from"./transaction.js";
let ruleset:LoadedRuleset;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"))});
function ready(){let s=createInitialSetup(ruleset,{gameId:"necro",firstSeat:1,seed:3001,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.necromancer",2:"character.knight",3:"character.ranger",4:"character.wizard"}});for(const seat of[1,2,3,4]as const)s=resolveInitialRedraw(s,seat,false,ruleset).state;Object.assign(s,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});s.players[0]!.markers["necromancer.energy"]=8;s.players[1]!.shield=30;s.players[1]!.maxShield=30;s.pendingWindows=[{promptId:"play:necro",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];return s}
function mark(s=ready(),id="mark"){s.lastEventSeq=s.history.domainEvents.at(-1)?.eventSeq??0;const session=new NecromancerMarkSession(s,ruleset),w=s.pendingWindows[0]!;expect(buildNecromancerMarkOffers(s,ruleset,1)).toHaveLength(1);expect(session.handle({commandId:id,gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:"offer:skill.necromancer.mark",targetRef:"character:2"}).accepted).toBe(true);return session.state}
describe("Necromancer",()=>{
 it("gains energy from actual damage only and excludes the mark-created extra point",()=>{let s=ready();s.players[0]!.markers["necromancer.energy"]=0;let tx=new EngineTransaction(s);applyDirectDamageInTransaction(tx,{damageId:"plain",sourceSeat:1,targetRef:"character:2",amount:2,damageType:"normal",element:"none",isAdditional:false,ruleset});s=tx.commit().state;expect(s.players[0]!.markers["necromancer.energy"]).toBe(2);s.players[0]!.markers["necromancer.energy"]=8;s.pendingWindows=[{promptId:"play:necro",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];s=mark(s);s.players[0]!.markers["necromancer.energy"]=0;tx=new EngineTransaction(s);applyDirectDamageInTransaction(tx,{damageId:"marked",sourceSeat:1,targetRef:"character:2",amount:1,damageType:"normal",element:"none",isAdditional:false,ruleset});s=tx.commit().state;expect(s.players[0]!.markers["necromancer.energy"]).toBe(1);expect((s.players[1]!.markers["necromancer.mark"] as unknown as{extraDamageAccumulated:number}).extraDamageAccumulated).toBe(1)});
 it("refreshes without stacking iron shield and expires on the source second subsequent prepare",()=>{let s=mark();expect(s.players[1]!.ironShield).toBe(-1);s.players[0]!.markers["necromancer.energy"]=8;const w=s.pendingWindows[0]!,session=new NecromancerMarkSession(s,ruleset);expect(session.handle({commandId:"refresh",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:"offer:skill.necromancer.mark",targetRef:"character:2"}).accepted).toBe(true);s=session.state;expect(s.players[1]!.ironShield).toBe(-1);for(let i=0;i<2;i++){const tx=new EngineTransaction(s);tickNecromancerMarksAtPrepare(tx,ruleset,1);s=tx.commit().state}expect(s.players[1]!.ironShield).toBe(0);expect(s.players[1]!.markers["necromancer.mark"]).toBeUndefined()});
 it("caps mark-created extra damage at eight and then removes its negative iron contribution",()=>{let s=mark();s.players[0]!.markers["necromancer.energy"]=0;for(let i=0;i<8;i++){const tx=new EngineTransaction(s);applyDirectDamageInTransaction(tx,{damageId:`cap-${i}`,sourceSeat:3,targetRef:"character:2",amount:1,damageType:"normal",element:"none",isAdditional:false,ruleset});s=tx.commit().state}expect(s.players[1]!.ironShield).toBe(0);expect((s.players[1]!.markers["necromancer.mark"] as unknown as{extraDamageAccumulated:number;contributionActive:boolean})).toMatchObject({extraDamageAccumulated:8,contributionActive:false})});
});
