import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {JudgmentDesignationSession} from "./judgmentDesignation.js";import {openPreJudgmentWindow,PreJudgmentSession} from "./preJudgment.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState} from "./state.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.shaman",4:"character.wizard"} as const;beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function ready(){let state=createInitialSetup(ruleset,{gameId:"pre-judgment",firstSeat:1,seed:59,usersBySeat:users,characterIdsBySeat:characters});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;return state;}
function relocate(state:AuthoritativeGameState,ref:string,to:string){const card=state.cards[ref]!,from=state.zones[card.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(ref),1);state.zones[to]!.orderedCardRefs.push(ref);card.zoneRef=to;card.ownerSeat=state.zones[to]!.ownerSeat;card.controllerSeat=state.zones[to]!.ownerSeat;card.faceUp=state.zones[to]!.zoneType!=="hand";}
function ensurePair(state:AuthoritativeGameState){const facts=new Map((ruleset.documents.get("cards.json") as {items:Array<{cardId:string;color:string}>}).items.map(item=>[item.cardId,item])),refs=Object.values(state.cards).filter(card=>facts.get(card.templateId)?.color==="white").slice(0,2).map(card=>card.cardRef);for(const ref of refs)relocate(state,ref,"hand:3");return refs;}
const judgmentInput={controllerSeat:1 as const,sourceRef:"weapon:test",purpose:"criticalAndWeaponEffect",matchColors:["orange" as const],context:{attackId:"attack:test",judgmentRuleId:"on_hit",targetRef:"character:2",resumeAttackStatus:"targetHit"}};
function pass(session:PreJudgmentSession,seat:1|2|3|4){const window=session.state.pendingWindows.find(item=>item.kind==="preJudgment")!;return session.handle({commandId:`pass-${seat}`,gameId:session.state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:`u${seat}`,promptId:window.promptId,offerId:window.legalOfferIds.find(id=>id.includes(":pass:"))!});}
describe("pre-judgment replacement",()=>{
 it("lets Shaman pay two same-color hand cards and designate any color without drawing",()=>{const state=ready(),pair=ensurePair(state),drawCount=state.zones.drawPile!.orderedCardRefs.length,opened=openPreJudgmentWindow(state,ruleset,judgmentInput,800)!,session=new PreJudgmentSession(opened.state,ruleset);pass(session,1);pass(session,2);const window=session.state.pendingWindows.find(item=>item.kind==="preJudgment")!,activate=window.legalOfferIds.find(id=>id.includes(":defy-fate:"))!,result=session.handle({commandId:"defy",gameId:state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u3",promptId:window.promptId,offerId:activate,cardRefs:pair});expect(result.accepted).toBe(true);expect(session.state.players[2]!.markers.defyFateUsed).toBe(true);expect(pair.every(ref=>session.state.cards[ref]!.zoneRef==="discardPile")).toBe(true);expect(session.state.resolutionStack[0]!.context).toMatchObject({cardRef:null,designatedWithoutCard:true});expect(session.state.zones.drawPile!.orderedCardRefs).toHaveLength(drawCount);const designation=session.state.pendingWindows.find(item=>item.kind==="judgmentDesignation")!,designator=new JudgmentDesignationSession(session.state),red=designation.legalOfferIds.find(id=>id.includes(":red:"))!;designator.handle({commandId:"red",gameId:state.gameId,expectedStateRevision:session.state.stateRevision,actorUserId:"u3",promptId:designation.promptId,offerId:red});expect(designator.state.zones.drawPile!.orderedCardRefs).toHaveLength(drawCount);expect(openPreJudgmentWindow(designator.state,ruleset,judgmentInput,900)).toBeNull();});
 it("falls through to a real-card judgment after four passes",()=>{const state=ready();ensurePair(state);const drawCount=state.zones.drawPile!.orderedCardRefs.length,opened=openPreJudgmentWindow(state,ruleset,judgmentInput,800)!,session=new PreJudgmentSession(opened.state,ruleset);for(const seat of [1,2,3,4] as const)pass(session,seat);expect(session.state.resolutionStack[0]!.context.cardRef).toEqual(expect.any(String));expect(session.state.zones.drawPile!.orderedCardRefs).toHaveLength(drawCount-1);expect(session.state.pendingWindows.some(item=>item.kind==="judgmentIntervention")).toBe(true);});
});
