import type {LoadedRuleset} from "../ruleset/types.js";
import {beginDesignatedJudgmentChoice,beginJudgment,type BeginJudgmentInput,type PrintedColor} from "./judgment.js";
import {facts,sameColorRefs} from "./judgmentShared.js";
import type {AuthoritativeGameState,PendingWindowState,Seat} from "./state.js";
import {validateAuthoritativeState} from "./stateValidation.js";
import {EngineTransaction} from "./transaction.js";
import type {DomainEvent,JsonValue,TransactionCommit} from "./types.js";

export interface PreJudgmentCommand {commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string;cardRefs?:string[]}
export type PreJudgmentResult={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
const allColors:PrintedColor[]=["white","green","blue","orange","red"];
const activeWindow=(state:AuthoritativeGameState)=>state.pendingWindows.find(item=>item.kind==="preJudgment");
function eligibleShaman(state:AuthoritativeGameState,ruleset:LoadedRuleset):Seat|null{const player=state.players.find(item=>item.characterId==="character.shaman"&&item.lifeState!=="eliminated"&&item.markers.defyFateUsed!==true&&sameColorRefs(state,ruleset,item.seat).length>=2);return player?.seat??null;}
function inputFrom(window:PendingWindowState):BeginJudgmentInput{return{controllerSeat:Number(window.context?.controllerSeat) as Seat,sourceRef:typeof window.context?.sourceRef==="string"?window.context.sourceRef:null,purpose:String(window.context?.purpose),matchColors:(Array.isArray(window.context?.matchColors)?window.context.matchColors:[]) as PrintedColor[],context:(window.context?.judgmentContext&&typeof window.context.judgmentContext==="object"&&!Array.isArray(window.context.judgmentContext)?window.context.judgmentContext:{}) as Record<string,JsonValue>};}
function offers(judgmentId:string):string[]{return[`offer:pre-judgment:pass:${judgmentId}`,`offer:pre-judgment:defy-fate:${judgmentId}`];}

export function openPreJudgmentWindow(state:AuthoritativeGameState,ruleset:LoadedRuleset,input:BeginJudgmentInput,deadlineAt=0):TransactionCommit<AuthoritativeGameState>|null{const shamanSeat=eligibleShaman(state,ruleset);if(!shamanSeat)return null;const tx=new EngineTransaction(state),draft=tx.draft,judgmentId=`pre-judgment:${draft.stateRevision+1}:${input.controllerSeat}`,promptId=`prompt:${judgmentId}`;draft.pendingWindows.push({promptId,kind:"preJudgment",prioritySeat:shamanSeat,mandatory:false,deadlineAt,timeoutPolicy:"pass",legalOfferIds:offers(judgmentId),context:{judgmentId,shamanSeat,controllerSeat:input.controllerSeat,sourceRef:input.sourceRef,purpose:input.purpose,matchColors:[...input.matchColors],judgmentContext:structuredClone(input.context??{})}});if(draft.combat.attack&&typeof draft.combat.attack==="object"&&!Array.isArray(draft.combat.attack))(draft.combat.attack as Record<string,JsonValue>).status="awaitingPreJudgment";tx.emit("response.window.opened",{kind:"preJudgment",judgmentId,promptId,prioritySeat:shamanSeat});tx.emit("response.priority.granted",{kind:"preJudgment",judgmentId,seat:shamanSeat});const committed=tx.commit();committed.state.history.domainEvents.push(...committed.events);validateAuthoritativeState(committed.state);return committed;}

export class PreJudgmentSession{
  #state:AuthoritativeGameState;readonly #results=new Map<string,PreJudgmentResult>();constructor(state:AuthoritativeGameState,private readonly ruleset:LoadedRuleset){this.#state=state;}get state(){return this.#state;}
  handle(command:PreJudgmentCommand):PreJudgmentResult{const prior=this.#results.get(command.commandId);if(prior)return structuredClone(prior);const reject=(reasonCode:string,refreshRequired:boolean):PreJudgmentResult=>{const result={accepted:false as const,commandId:command.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired};this.#results.set(command.commandId,result);return structuredClone(result);};if(command.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(command.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const window=activeWindow(this.#state);if(!window||window.promptId!==command.promptId)return reject("PROMPT_CLOSED",true);const player=this.#state.players.find(item=>item.userId===command.actorUserId);if(!player||player.seat!==window.prioritySeat)return reject("NOT_YOUR_PRIORITY",false);if(!window.legalOfferIds.includes(command.offerId))return reject("OFFER_EXPIRED",true);const activate=command.offerId.includes(":defy-fate:"),input=inputFrom(window),events:DomainEvent[]=[];let previousRevision=this.#state.stateRevision;
    if(activate){const shamanSeat=Number(window.context?.shamanSeat) as Seat,refs=command.cardRefs??[],legal=sameColorRefs(this.#state,this.ruleset,shamanSeat),cardFacts=facts(this.ruleset);if(player.seat!==shamanSeat||refs.length!==2||new Set(refs).size!==2||refs.some(ref=>!legal.includes(ref))||cardFacts.get(this.#state.cards[refs[0]!]!.templateId)?.color!==cardFacts.get(this.#state.cards[refs[1]!]!.templateId)?.color)return reject("DEFY_FATE_COST_INVALID",false);const tx=new EngineTransaction(this.#state),draft=tx.draft;draft.pendingWindows=draft.pendingWindows.filter(item=>item.promptId!==window.promptId);for(const ref of refs){const hand=draft.zones[`hand:${shamanSeat}`]!,index=hand.orderedCardRefs.indexOf(ref);hand.orderedCardRefs.splice(index,1);draft.zones.discardPile!.orderedCardRefs.push(ref);const card=draft.cards[ref]!;card.zoneRef="discardPile";card.ownerSeat=null;card.controllerSeat=null;card.faceUp=true;tx.emit("card.played",{cardRef:ref,seat:shamanSeat,purpose:"skill.shaman.defy_fate"});}draft.players.find(item=>item.seat===shamanSeat)!.markers.defyFateUsed=true;tx.emit("ability.activation.committed",{seat:shamanSeat,abilityId:"skill.shaman.defy_fate",cardRefs:refs});const paid=tx.commit();paid.state.history.domainEvents.push(...paid.events);validateAuthoritativeState(paid.state);events.push(...paid.events);const designated=beginDesignatedJudgmentChoice(paid.state,{...input,controllerSeat:shamanSeat,sourceRef:"skill.shaman.defy_fate"},window.deadlineAt,allColors);this.#state=designated.state;events.push(...designated.events);
    }else{if(command.cardRefs?.length)return reject("DEFY_FATE_COST_INVALID",false);const tx=new EngineTransaction(this.#state),draft=tx.draft,draftWindow=draft.pendingWindows.find(item=>item.promptId===window.promptId)!,shamanSeat=Number(draftWindow.context?.shamanSeat) as Seat;draft.pendingWindows=draft.pendingWindows.filter(item=>item.promptId!==window.promptId);tx.emit("response.passed",{kind:"preJudgment",judgmentId:String(window.context?.judgmentId),seat:player.seat});if(shamanSeat===player.seat){const committed=tx.commit();committed.state.history.domainEvents.push(...committed.events);validateAuthoritativeState(committed.state);events.push(...committed.events);this.#state=committed.state;const begun=beginJudgment(this.#state,this.ruleset,input,window.deadlineAt);this.#state=begun.state;events.push(...begun.events);}else{const passedCommit=tx.commit();passedCommit.state.history.domainEvents.push(...passedCommit.events);validateAuthoritativeState(passedCommit.state);events.push(...passedCommit.events);this.#state=passedCommit.state;}}
    const result={accepted:true as const,commandId:command.commandId,previousRevision,stateRevision:this.#state.stateRevision,events};this.#results.set(command.commandId,result);return structuredClone(result);
  }
  handleTimeout(commandId:string):PreJudgmentResult{const window=activeWindow(this.#state);if(!window)return{accepted:false,commandId,stateRevision:this.#state.stateRevision,reasonCode:"PROMPT_CLOSED",refreshRequired:true};return this.handle({commandId,gameId:this.#state.gameId,expectedStateRevision:this.#state.stateRevision,actorUserId:this.#state.players.find(item=>item.seat===window.prioritySeat)!.userId,promptId:window.promptId,offerId:window.legalOfferIds.find(id=>id.includes(":pass:"))!});}
}
