// 无目标雕像（巫师/狂战士/牧师/刺客）使用后不得出现 statueResolutionChoice 选目标窗口：
// 目标完全由规则确定（或无目标），应由服务端自动结算。覆盖引擎层与应用层（GameService）两条路径。
import {resolve} from "node:path";
import {beforeAll,describe,expect,it} from "vitest";
import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";
import type {LoadedRuleset} from "../ruleset/types.js";
import {createInitialSetup,resolveInitialRedraw} from "./setup.js";
import type {AuthoritativeGameState,Seat} from "./state.js";
import {buildStatuePlayOffers,StatuePlaySession,openStatueResolutionWindow} from "./statueDoubleTrigger.js";
import {finalizeJudgment} from "./judgment.js";
import {runAutomaticScheduler} from "./automaticScheduler.js";
import {GameService} from "../app/gameService.js";
import type {AppRoom,AppSettings,AppUser} from "../app/types.js";

let r:LoadedRuleset;beforeAll(async()=>{r=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
const settings:AppSettings={roomName:"雕像无目标窗口",allowGuests:true,allowSpectators:false,turnTimeSeconds:60,responseTimeSeconds:20,reserveTimeSeconds:30,rulesetVersion:"1.3.4",dismantleBossEnabled:true};
const users:Record<Seat,AppUser>={1:{userId:"u1",displayName:"一"},2:{userId:"u2",displayName:"二"},3:{userId:"u3",displayName:"三"},4:{userId:"u4",displayName:"四"}};
function game(){let s=createInitialSetup(r,{gameId:"statues",firstSeat:1,seed:827,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.knight",2:"character.ranger",3:"character.shaman",4:"character.druid"}});for(const n of [1,2,3,4] as const)s=resolveInitialRedraw(s,n,false,r).state;Object.assign(s,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});s.players[2]!.markers.defyFateUsed=true;s.pendingWindows=[];return s;}
function move(s:AuthoritativeGameState,ref:string,to:string,owner:Seat|null=null){const c=s.cards[ref]!,z=s.zones[c.zoneRef]!;z.orderedCardRefs.splice(z.orderedCardRefs.indexOf(ref),1);s.zones[to]!.orderedCardRefs.push(ref);Object.assign(c,{zoneRef:to,ownerSeat:owner,controllerSeat:owner,faceUp:to!=="hand:1"});}
function clearPaladins(s:AuthoritativeGameState){for(const n of [1,2,3,4] as const)for(const ref of [...s.zones[`hand:${n}`]!.orderedCardRefs])if(s.cards[ref]!.templateId.startsWith("statue.paladin."))move(s,ref,"drawPile");}
function statueInHand(s:AuthoritativeGameState,prefix:string){const c=Object.values(s.cards).find(x=>x.templateId.startsWith(prefix))!;move(s,c.cardRef,"hand:1",1);return c.cardRef;}
function useStatue(s:AuthoritativeGameState,ref:string){s.pendingWindows=[{promptId:"prompt:play:1",kind:"playPhaseAction",prioritySeat:1 as Seat,mandatory:false,deadlineAt:900,timeoutPolicy:"pass" as const,legalOfferIds:[]}];const w=s.pendingWindows[0]!,offer=buildStatuePlayOffers(s,1).find(o=>o.cardRef===ref);if(!offer)throw new Error("STATUE_OFFER_MISSING");const session=new StatuePlaySession(s,r,900),res=session.handle({commandId:"c:1",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:offer.offerId,cardRef:ref},900);expect(res.accepted,"雕像使用应被接受").toBe(true);return session;}
const hasResolutionWindow=(s:AuthoritativeGameState)=>s.pendingWindows.some(w=>w.kind==="statueResolutionChoice");
function openedState(seed=501):AuthoritativeGameState{let state=createInitialSetup(r,{gameId:`statue-app-${seed}`,firstSeat:1,seed,usersBySeat:{1:users[1]!.userId,2:users[2]!.userId,3:users[3]!.userId,4:users[4]!.userId},characterIdsBySeat:{1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"}});for(const n of [1,2,3,4] as const)state=resolveInitialRedraw(state,n,false,r).state;const scheduled=runAutomaticScheduler(state,r,()=>21000);state=scheduled.state;if(state.phase!=="play")throw new Error(`expected play phase, got ${state.phase}`);return state;}
function makeRoom(state:AuthoritativeGameState):AppRoom{return{roomId:state.gameId,roomCode:"APP",revision:1,phase:"inGame",settings,passwordHash:null,players:state.players.map(player=>({userId:player.userId,displayName:users[player.seat]!.displayName,seat:player.seat,team:player.team,isHost:player.seat===1,ready:true,connection:"online",latencyMs:null,selectionState:"revealed",candidates:[],preselectedCharacterId:null,lockedCharacterId:null,selectionDeadlineAt:null})),spectators:[],chat:[],gameChat:[],game:state,createdAt:0,updatedAt:0};}

describe("无目标雕像自动结算（不出现选目标窗口）",()=>{
 it("巫师：无双触判定时直接摸牌，不出现 statueResolutionChoice 窗口",()=>{let s=game();clearPaladins(s);const ref=statueInHand(s,"statue.wizard."),before=s.zones["hand:1"]!.orderedCardRefs.length;const session=useStatue(s,ref);expect(hasResolutionWindow(session.state),"巫师雕像不得打开选目标窗口").toBe(false);expect(session.state.zones["hand:1"]!.orderedCardRefs,"巫师应摸配置数量（使用后雕像离手-1再摸2）").toHaveLength(before+1);expect(session.state.cards[ref]!.zoneRef).toBe("discardPile");});
 it("狂战士：直接修改剩余攻击次数，不出现选目标窗口",()=>{let s=game();clearPaladins(s);const ref=statueInHand(s,"statue.berserker."),old=Number(s.players[0]!.limits[r.settings.combat.attackCountLimitId]??0);const session=useStatue(s,ref);expect(hasResolutionWindow(session.state)).toBe(false);expect(session.state.players[0]!.limits[r.settings.combat.attackCountLimitId]).toBe(old+1);});
 it("牧师：不出现选目标窗口（仅开顺序确定的拿/不拿窗口）",()=>{let s=game();clearPaladins(s);const ref=statueInHand(s,"statue.priest.");const session=useStatue(s,ref);expect(hasResolutionWindow(session.state)).toBe(false);expect(session.state.pendingWindows.some(w=>w.kind==="statuePriestTake"),"牧师应开拿/不拿窗口").toBe(true);});
 it("刺客：直接建立逆时针全员攻击，不出现选目标窗口",()=>{let s=game();clearPaladins(s);const ref=statueInHand(s,"statue.assassin.");const session=useStatue(s,ref);expect(hasResolutionWindow(session.state)).toBe(false);expect(session.state.combat.attack).toMatchObject({attackerSeat:1,targetRefs:["character:2","character:3","character:4"]});});
 it("巫师：双触判定后由自动调度结算，不出现选目标窗口",()=>{let s=game();clearPaladins(s);const ref=statueInHand(s,"statue.wizard."),before=s.zones["hand:1"]!.orderedCardRefs.length;s.pendingWindows=[{promptId:"prompt:play:1",kind:"playPhaseAction",prioritySeat:1 as Seat,mandatory:false,deadlineAt:900,timeoutPolicy:"pass" as const,legalOfferIds:[]}];const offer=buildStatuePlayOffers(s,1).find(o=>o.cardRef===ref)!;const session=new StatuePlaySession(s,r,900),res=session.handle({commandId:"c:1",gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"prompt:play:1",offerId:offer.offerId,cardRef:ref},900);expect(res.accepted).toBe(true);let cur=session.state;const kind=cur.pendingWindows[0]?.kind;expect(kind,"雕像使用后应无双触直接结算或有判定窗口").not.toBe("statueResolutionChoice");if(kind==="judgmentDesignation"||kind==="judgmentIntervention"){cur=finalizeJudgment(cur,"red").state;}expect(hasResolutionWindow(cur),"双触路径全程不得出现选目标窗口").toBe(false);expect(cur.zones["hand:1"]!.orderedCardRefs,"判定后应完成摸牌").toHaveLength(before+1);});
 it("防御：openStatueResolutionWindow 对无选择报价拒绝打开窗口（防空窗口回归）",async()=>{let s=game();clearPaladins(s);const ref=statueInHand(s,"statue.wizard.");move(s,ref,"resolving");Object.assign(s.cards[ref]!.runtime,{statueOwnerSeat:1,statueResumePlayDeadlineAt:900});const {buildStatueResolutionOffers}=await import("./statueEffects.js");const resolution=buildStatueResolutionOffers(s,r,1,ref);expect(resolution,"巫师雕像解析报价应无目标").toHaveLength(1);expect(resolution[0]!.targetRef,"巫师雕像报价不得携带目标").toBeUndefined();const opened=openStatueResolutionWindow(s,ref,1,900,resolution);expect(opened,"无目标报价不得打开选目标窗口").toBe(false);expect(s.pendingWindows.some(w=>w.kind==="statueResolutionChoice"),"防御后不得残留空窗口").toBe(false);});
 it("巫师：圣骑士响应（放弃）后仍不出现选目标窗口、直接完成摸牌",async()=>{let s=game();clearPaladins(s);const paladin=Object.values(s.cards).find(x=>x.templateId.startsWith("statue.paladin."))!;move(s,paladin.cardRef,"hand:2",2);const ref=statueInHand(s,"statue.wizard."),before=s.zones["hand:1"]!.orderedCardRefs.length;const session=useStatue(s,ref);expect(session.state.pendingWindows[0]!.kind,"圣骑士持有者应先收到响应窗口").toBe("statuePaladinResponse");const {StatueChoiceSession}=await import("./statueEffects.js"),choice=new StatueChoiceSession(session.state,r),w=choice.state.pendingWindows[0]!;const res=choice.handle({commandId:"c:2",gameId:choice.state.gameId,expectedStateRevision:choice.state.stateRevision,actorUserId:"u2",promptId:w.promptId,offerId:"offer:statue-paladin:pass"});expect(res.accepted).toBe(true);expect(hasResolutionWindow(choice.state),"圣骑士放弃后不得出现选目标窗口").toBe(false);expect(choice.state.cards[ref]!.zoneRef,"巫师正文应执行完成").toBe("discardPile");expect(choice.state.zones["hand:1"]!.orderedCardRefs,"圣骑士放弃后应完成摸牌").toHaveLength(before+1);});
 it("应用层：GameService 提交巫师雕像使用后快照无选目标窗口、恢复出牌窗口",()=>{let state=openedState(503);const ref=statueInHand(state,"statue.wizard.");const before=state.zones["hand:1"]!.orderedCardRefs.length;const room=makeRoom(state),service=new GameService(r,()=>1000),offerId=`offer:statue-play:${ref}`;const command={type:"GAME_COMMAND" as const,commandId:"statue-app-1",gameId:room.game!.gameId,expectedStateRevision:room.game!.stateRevision,promptId:room.game!.pendingWindows[0]!.promptId,offerId,command:"EXECUTE_OFFER" as const,payload:{selections:{}}};const res=service.handle(room,users[1]!,command);expect(res.accepted,`雕像应用层使用被拒:${JSON.stringify(res)}`).toBe(true);expect(room.game!.pendingWindows.some(w=>w.kind==="statueResolutionChoice"),"应用层快照不得出现选目标窗口").toBe(false);expect(room.game!.pendingWindows[0]!.kind,"雕像结算后应恢复出牌窗口").toBe("playPhaseAction");expect(room.game!.zones["hand:1"]!.orderedCardRefs,"应用层摸牌生效").toHaveLength(before+1);});
});
