import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {finalizeJudgment} from "./judgment.js";import {resolvePhaseBody} from "./phaseBody.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import type {AuthoritativeGameState,Seat} from "./state.js";import {beginStatueResolution,StatueChoiceSession} from "./statueEffects.js";
let r:LoadedRuleset;beforeAll(async()=>{r=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function game(){let s=createInitialSetup(r,{gameId:"statues",firstSeat:1,seed:827,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.knight",2:"character.ranger",3:"character.shaman",4:"character.druid"}});for(const n of [1,2,3,4] as const)s=resolveInitialRedraw(s,n,false,r).state;Object.assign(s,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});s.players[2]!.markers.defyFateUsed=true;s.pendingWindows=[];return s;}
function move(s:AuthoritativeGameState,ref:string,to:string,owner:Seat|null=null){const c=s.cards[ref]!,z=s.zones[c.zoneRef]!;z.orderedCardRefs.splice(z.orderedCardRefs.indexOf(ref),1);s.zones[to]!.orderedCardRefs.push(ref);Object.assign(c,{zoneRef:to,ownerSeat:owner,controllerSeat:owner,faceUp:to!=="hand:1"});}
function statue(s:AuthoritativeGameState,prefix:string){const c=Object.values(s.cards).find(x=>x.templateId.startsWith(prefix))!;move(s,c.cardRef,"resolving");Object.assign(c.runtime,{statueOwnerSeat:1,statueResumePlayDeadlineAt:900});return c.cardRef;}
function clearPaladins(s:AuthoritativeGameState){for(const n of [1,2,3,4] as const)for(const ref of [...s.zones[`hand:${n}`]!.orderedCardRefs])if(s.cards[ref]!.templateId.startsWith("statue.paladin."))move(s,ref,"drawPile");}
function choose(session:StatueChoiceSession,offerId:string){const s=session.state,w=s.pendingWindows[0]!;return session.handle({commandId:`c:${s.stateRevision}:${offerId}`,gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:s.players.find(x=>x.seat===w.prioritySeat)!.userId,promptId:w.promptId,offerId});}
describe("statue bodies",()=>{
 it("resolves wizard and berserker through configured common lifecycle",()=>{let s=game();clearPaladins(s);const before=s.zones["hand:1"]!.orderedCardRefs.length,ref=statue(s,"statue.wizard.");s=beginStatueResolution(s,r,ref,{deadlineAt:900}).state;expect(s.zones["hand:1"]!.orderedCardRefs).toHaveLength(before+2);expect(s.cards[ref]!.zoneRef).toBe("discardPile");s.pendingWindows=[];const berserker=statue(s,"statue.berserker."),old=Number(s.players[0]!.limits[r.settings.combat.attackCountLimitId]??0);s=beginStatueResolution(s,r,berserker,{deadlineAt:900}).state;expect(s.players[0]!.limits[r.settings.combat.attackCountLimitId]).toBe(old+1);});
 it("drains only actual shield loss and opens identity-safe elf selection",()=>{let s=game();clearPaladins(s);s.players[0]!.shield=0;s.players[1]!.shield=1;let ref=statue(s,"statue.werewolf.");s=beginStatueResolution(s,r,ref,{targetRef:"character:2",modeId:"drain_shield",deadlineAt:900}).state;expect(s.players[1]!.shield).toBe(0);expect(s.players[0]!.shield).toBe(1);s.pendingWindows=[];const victim=s.zones["hand:2"]!.orderedCardRefs[0]!,elf=statue(s,"statue.elf.");s=beginStatueResolution(s,r,elf,{targetRef:"character:2",deadlineAt:900}).state;const w=s.pendingWindows[0]!,refs=w.context!.legalCardRefs as unknown as string[],session=new StatueChoiceSession(s,r);choose(session,w.legalOfferIds[refs.indexOf(victim)]!);expect(session.state.cards[victim]!.zoneRef).toBe("discardPile");});
 it("gains the selected public-or-card-back candidate with rogue statue",()=>{let s=game();clearPaladins(s);const victim=s.zones["hand:2"]!.orderedCardRefs[0]!,ref=statue(s,"statue.rogue.");s=beginStatueResolution(s,r,ref,{targetRef:"character:2",deadlineAt:900}).state;const w=s.pendingWindows[0]!,refs=w.context!.legalCardRefs as unknown as string[],session=new StatueChoiceSession(s,r);choose(session,w.legalOfferIds[refs.indexOf(victim)]!);expect(session.state.cards[victim]).toMatchObject({zoneRef:"hand:1",ownerSeat:1});});
 it("lets every in-play character take at most once from priest display",()=>{let s=game();clearPaladins(s);const ref=statue(s,"statue.priest.");s=beginStatueResolution(s,r,ref,{deadlineAt:900}).state;const session=new StatueChoiceSession(s,r);for(let i=0;i<4;i++){const w=session.state.pendingWindows[0]!;choose(session,i===0?w.legalOfferIds[1]!:w.legalOfferIds[0]!);}expect(session.state.cards[ref]!.zoneRef).toBe("discardPile");expect(session.state.pendingWindows[0]).toMatchObject({kind:"playPhaseAction",prioritySeat:1});});
 it("creates the assassin's ordered attack and the knight winner's free weapon attack",()=>{let s=game();clearPaladins(s);let ref=statue(s,"statue.assassin.");s=beginStatueResolution(s,r,ref,{deadlineAt:900}).state;expect(s.combat.attack).toMatchObject({attackerSeat:1,targetRefs:["character:2","character:3","character:4"],responsePolicy:"standardAttack"});s=game();clearPaladins(s);const weapon=Object.values(s.cards).find(x=>x.templateId==="weapon.w01")!;move(s,weapon.cardRef,"weapon:1:1",1);ref=statue(s,"statue.knight.");s=beginStatueResolution(s,r,ref,{targetRef:"character:2",deadlineAt:900}).state;const session=new StatueChoiceSession(s,r);choose(session,"offer:statue-knight:pass");const w=session.state.pendingWindows[0]!;choose(session,w.legalOfferIds[1]!);expect(session.state.combat.attack).toMatchObject({attackerSeat:1,targetRefs:["character:2"],ignoreArmor:true,responsePolicy:"noDodge"});});
 it("passes engineer statues after a miss and removes them on green",()=>{let s=game();clearPaladins(s);const ref=statue(s,"statue.engineer.");s=beginStatueResolution(s,r,ref,{targetRef:"character:2",deadlineAt:900}).state;Object.assign(s,{activeSeat:2,phase:"judgment",phaseBodyResolved:false});s=resolvePhaseBody(s,r,900).state;s=finalizeJudgment(s,"red").state;expect(s.cards[ref]!.zoneRef).toBe("judgment:3");Object.assign(s,{activeSeat:3,phase:"judgment",phaseBodyResolved:false});s=resolvePhaseBody(s,r,900).state;s=finalizeJudgment(s,"green").state;expect(s.cards[ref]!.zoneRef).toBe("discardPile");expect(s.scheduledEffects.some(x=>x.effect&&typeof x.effect==="object"&&!Array.isArray(x.effect)&&x.effect.sourceAbilityId==="statue.engineer")).toBe(true);});
 it("allows a paladin statue to invalidate another statue before its body",()=>{let s=game();clearPaladins(s);const paladin=Object.values(s.cards).find(x=>x.templateId.startsWith("statue.paladin."))!;move(s,paladin.cardRef,"hand:2",2);const base=statue(s,"statue.wizard."),before=s.zones["hand:1"]!.orderedCardRefs.length;s=beginStatueResolution(s,r,base,{deadlineAt:900}).state;const session=new StatueChoiceSession(s,r);choose(session,session.state.pendingWindows[0]!.legalOfferIds[1]!);for(let i=0;i<3;i++)choose(session,"offer:statue-paladin:pass");expect(session.state.cards[base]!.zoneRef).toBe("discardPile");expect(session.state.zones["hand:1"]!.orderedCardRefs).toHaveLength(before);});
 it("resolves nested paladin statues last-in-first-out",()=>{let s=game();clearPaladins(s);const cards=Object.values(s.cards).filter(x=>x.templateId.startsWith("statue.paladin.")).slice(0,2);move(s,cards[0]!.cardRef,"hand:2",2);move(s,cards[1]!.cardRef,"hand:3",3);const base=statue(s,"statue.wizard."),before=s.zones["hand:1"]!.orderedCardRefs.length;s=beginStatueResolution(s,r,base,{deadlineAt:900}).state;const session=new StatueChoiceSession(s,r);choose(session,session.state.pendingWindows[0]!.legalOfferIds[1]!);choose(session,session.state.pendingWindows[0]!.legalOfferIds[1]!);expect(session.state.pendingWindows.some(w=>w.kind==="statueResolutionChoice"),"无目标雕像全程不得出现选目标窗口").toBe(false);expect(session.state.cards[base]!.zoneRef).toBe("discardPile");expect(session.state.zones["hand:1"]!.orderedCardRefs).toHaveLength(before+2);expect(cards.every(x=>session.state.cards[x.cardRef]!.zoneRef==="discardPile")).toBe(true);});
});
