import type {LoadedRuleset} from "../ruleset/types.js";
import {resolvePreselectedAttackSource} from "./attack.js";
import {calculateEffectiveDistance} from "./distance.js";
import {drawCardsInTransaction,takeTopCardsToResolvingInTransaction} from "./deck.js";
import {applyDirectDamageInTransaction} from "./damage.js";
import {beginJudgmentInTransaction} from "./judgment.js";
import {shuffleWithSource} from "./random.js";
import {createCompositeScriptedAttackInTransaction,createScriptedAttackInTransaction} from "./scriptedAttack.js";
import type {AuthoritativeGameState,Seat} from "./state.js";
import {validateAuthoritativeState} from "./stateValidation.js";
import {EngineTransaction} from "./transaction.js";
import type {DomainEvent,JsonValue,TransactionCommit} from "./types.js";
import {moveCardInTransaction} from "./zoneMovement.js";

type RecordValue=Record<string,JsonValue>;
const object=(v:unknown):RecordValue=>v&&typeof v==="object"&&!Array.isArray(v)?v as RecordValue:{};
const list=(v:unknown):JsonValue[]=>Array.isArray(v)?v:[];
function statueRule(r:LoadedRuleset,id:string){const doc=r.documents.get("nonboss-rules.json") as {effectFamilies:RecordValue[]},rule=doc.effectFamilies.find(x=>x.familyId===id);if(!rule)throw new Error("STATUE_RULE_MISSING");return rule;}
function effectParams(rule:RecordValue,op:string){const walk=(value:JsonValue):RecordValue|null=>{if(Array.isArray(value)){for(const x of value){const found=walk(x);if(found)return found;}return null;}if(value&&typeof value==="object"){const item=value as RecordValue;if(item.op===op)return object(item.params);for(const x of Object.values(item)){const found=walk(x);if(found)return found;}}return null;};return walk(rule as unknown as JsonValue);}
function numberValue(v:JsonValue|undefined,code:string){const n=Number(v);if(!Number.isFinite(n))throw new Error(code);return n;}
const seatOf=(ref:string)=>Number(ref.split(":")[1]) as Seat;
const player=(s:AuthoritativeGameState,n:Seat)=>s.players.find(x=>x.seat===n)!;
const inPlay=(s:AuthoritativeGameState,n:Seat)=>{const p=player(s,n);return p.presence==="inPlay"&&p.lifeState!=="eliminated"};
const family=(id:string)=>id.split(".").slice(0,2).join(".");
const equipmentZones=new Set(["weaponSlot","thirdWeaponSlot","armorSlot","mountOffenseSlot","mountDefenseSlot","talentZone","bossSlot"]);
const ownedSelectable=(s:AuthoritativeGameState,n:Seat)=>Object.values(s.zones).filter(z=>z.ownerSeat===n&&(z.zoneType==="hand"||z.zoneType==="judgment"||equipmentZones.has(z.zoneType))).flatMap(z=>z.orderedCardRefs);
const commit=(tx:EngineTransaction<AuthoritativeGameState>)=>{const out=tx.commit();out.state.history.domainEvents.push(...out.events);validateAuthoritativeState(out.state);return out;};
function closeStatue(tx:EngineTransaction<AuthoritativeGameState>,ref:string,resume=true,prevented=false){const card=tx.draft.cards[ref]!;const owner=Number(card.runtime.statueOwnerSeat??card.controllerSeat??card.ownerSeat) as Seat,deadline=Number(card.runtime.statueResumePlayDeadlineAt??0);tx.emit(prevented?"card.effect.prevented":"card.effect.resolved",{cardRef:ref,cardId:card.templateId,category:"statue",reason:prevented?"paladinStatue":null});if(card.runtime.returnAfterStatue===true){delete card.runtime.returnAfterStatue;moveCardInTransaction(tx,{cardRef:ref,toZoneRef:`hand:${owner}`,moveKind:"return",faceUp:false});tx.emit("talent.statueDoubleTrigger.returned",{statueRef:ref});}else moveCardInTransaction(tx,{cardRef:ref,toZoneRef:"discardPile",moveKind:"discard",faceUp:true});delete card.runtime.statueOwnerSeat;delete card.runtime.statueResumePlayDeadlineAt;if(resume&&deadline>0&&!tx.draft.pendingWindows.length&&!tx.draft.combat.attack&&tx.draft.activeSeat===owner&&tx.draft.phase==="play"){const promptId=`prompt:playPhaseAction:${tx.draft.round}:${owner}:${tx.draft.stateRevision+1}`;tx.draft.pendingWindows.push({promptId,kind:"playPhaseAction",prioritySeat:owner,mandatory:false,deadlineAt:deadline,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}});tx.emit("choice.requested",{seat:owner,kind:"playPhaseAction",resumedAfterStatue:true});}}
function legalTarget(s:AuthoritativeGameState,owner:Seat,targetRef:string,range:number|"unlimited"){if(!/^character:[1-4]$/.test(targetRef))return false;const n=seatOf(targetRef);return inPlay(s,n)&&(range==="unlimited"||calculateEffectiveDistance(s,owner,n)<=range);}
function openWindow(tx:EngineTransaction<AuthoritativeGameState>,kind:string,seat:Seat,deadlineAt:number,offers:string[],context:RecordValue,mandatory=true,timeoutPolicy:"pass"|"randomLegal"="randomLegal"){const promptId=`prompt:${kind}:${tx.draft.stateRevision+1}:${tx.draft.pendingWindows.length}`;tx.draft.pendingWindows.push({promptId,kind,prioritySeat:seat,mandatory,deadlineAt,timeoutPolicy,legalOfferIds:offers,context});tx.emit("choice.requested",{kind,promptId,seat,legalOfferIds:offers});}

export interface BeginStatueInput{targetRef?:string;modeId?:string;deadlineAt:number}
interface StatueResolutionOffer{offerId:string;statueRef:string;targetRef?:string;modeId?:string}
export function buildStatueResolutionOffers(s:AuthoritativeGameState,r:LoadedRuleset,seat:Seat,ref:string):StatueResolutionOffer[]{const card=s.cards[ref];if(!card||card.zoneRef!=="resolving"||Number(card.runtime.statueOwnerSeat??card.controllerSeat)!==seat||s.pendingWindows.some(w=>w.kind!=="statueResolutionChoice"))return[];const id=family(card.templateId),rule=statueRule(r,id),targets=(range:number|"unlimited",needsCard=false)=>([1,2,3,4] as Seat[]).filter(n=>legalTarget(s,seat,`character:${n}`,range)&&(!needsCard||ownedSelectable(s,n).length)).map(n=>`character:${n}`);if(id==="statue.wizard"||id==="statue.berserker"||id==="statue.priest"||id==="statue.assassin")return[{offerId:`offer:statue-resolve:${ref}`,statueRef:ref}];if(id==="statue.werewolf"){const range=numberValue(object(rule.targetRule).range,"STATUE_RANGE_INVALID");return targets(range).flatMap(targetRef=>list(rule.modes).map(object).map(mode=>({offerId:`offer:statue-resolve:${ref}:${targetRef}:${String(mode.modeId)}`,statueRef:ref,targetRef,modeId:String(mode.modeId)})));}if(id==="statue.elf"||id==="statue.rogue"){const raw=object(rule.targetRule).range,range=raw==="unlimited"?"unlimited":numberValue(raw,"STATUE_RANGE_INVALID");return targets(range,true).map(targetRef=>({offerId:`offer:statue-resolve:${ref}:${targetRef}`,statueRef:ref,targetRef}));}if(id==="statue.engineer"||id==="statue.knight"){const raw=object(rule.targetRule).range,range=raw==="unlimited"||raw===undefined?"unlimited":numberValue(raw,"STATUE_RANGE_INVALID");return targets(range).map(targetRef=>({offerId:`offer:statue-resolve:${ref}:${targetRef}`,statueRef:ref,targetRef}));}return[];}
type StartCommand={commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;offerId:string;statueRef:string;targetRef?:string;modeId?:string};
export class StatueResolutionSession{#state:AuthoritativeGameState;#results=new Map<string,ChoiceResult>();constructor(s:AuthoritativeGameState,private r:LoadedRuleset){this.#state=s}get state(){return this.#state}handle(c:StartCommand,deadlineAt:number):ChoiceResult{const old=this.#results.get(c.commandId);if(old)return structuredClone(old);const no=(reasonCode:string,refreshRequired:boolean):ChoiceResult=>({accepted:false,commandId:c.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired});if(c.gameId!==this.#state.gameId)return no("GAME_NOT_FOUND",false);if(c.expectedStateRevision!==this.#state.stateRevision)return no("STALE_REVISION",true);const actor=this.#state.players.find(x=>x.userId===c.actorUserId),offer=actor?buildStatueResolutionOffers(this.#state,this.r,actor.seat,c.statueRef).find(x=>x.offerId===c.offerId&&x.targetRef===c.targetRef&&x.modeId===c.modeId):undefined;if(!actor)return no("NOT_YOUR_PRIORITY",false);if(!offer)return no("OFFER_EXPIRED",true);const input:BeginStatueInput={deadlineAt,...(c.targetRef?{targetRef:c.targetRef}:{}),...(c.modeId?{modeId:c.modeId}:{})},clean={...this.#state,pendingWindows:this.#state.pendingWindows.filter(w=>w.kind!=="statueResolutionChoice")},out=beginStatueResolution(clean,this.r,c.statueRef,input);this.#state=out.state;const result:ChoiceResult={accepted:true,commandId:c.commandId,previousRevision:out.previousRevision,stateRevision:out.state.stateRevision,events:out.events};this.#results.set(c.commandId,result);return structuredClone(result);}}
export function beginStatueResolution(s:AuthoritativeGameState,r:LoadedRuleset,ref:string,input:BeginStatueInput):TransactionCommit<AuthoritativeGameState>{
 const card=s.cards[ref];if(!card||card.zoneRef!=="resolving"||!card.templateId.startsWith("statue."))throw new Error("STATUE_NOT_RESOLVING");if(s.pendingWindows.length)throw new Error("STATUE_WINDOW_CONFLICT");const owner=Number(card.runtime.statueOwnerSeat??card.controllerSeat) as Seat,id=family(card.templateId),rule=statueRule(r,id),tx=new EngineTransaction(s);
 if(card.runtime.paladinResponseChecked!==true){const response=openPaladinResponseInTransaction(tx,ref,owner,input);if(response)return commit(tx);tx.draft.cards[ref]!.runtime.paladinResponseChecked=true;}
 if(id==="statue.wizard"){drawCardsInTransaction(tx,owner,numberValue(effectParams(rule,"drawCards")?.count,"STATUE_DRAW_COUNT_INVALID"),id);closeStatue(tx,ref);}
 else if(id==="statue.berserker"){const delta=numberValue(effectParams(rule,"modifyAttackCount")?.delta,"STATUE_ATTACK_COUNT_DELTA_INVALID"),p=player(tx.draft,owner),key=r.settings.combat.attackCountLimitId,before=Number(p.limits[key]??0);p.limits[key]=before+delta;tx.emit("limit.changed",{seat:owner,limitId:key,from:before,to:before+delta,sourceRef:ref});closeStatue(tx,ref);}
 else if(id==="statue.werewolf"){const range=numberValue(object(rule.targetRule).range,"STATUE_RANGE_INVALID"),mode=list(rule.modes).map(object).find(x=>x.modeId===input.modeId);if(!input.targetRef||!legalTarget(s,owner,input.targetRef,range))throw new Error("STATUE_TARGET_INVALID");if(!mode)throw new Error("STATUE_MODE_INVALID");const damage=list(mode.effects).map(object).find(x=>x.op==="createDamage"),params=object(damage?.params),damageType=String(params.damageType),shield=damageType==="shield",amount=numberValue(params.amount,"STATUE_DAMAGE_INVALID"),hit=applyDirectDamageInTransaction(tx,{damageId:`damage:statue-werewolf:${ref}:${s.stateRevision+1}`,sourceSeat:owner,targetRef:input.targetRef,amount,damageType,element:"none",isAdditional:false,ruleset:r}),actual=shield?hit.actualShieldLoss:hit.actualHpLoss,p=player(tx.draft,owner);if(actual>0){if(shield&&p.shield!==null&&p.maxShield!==null){const before=p.shield;p.shield=Math.min(p.maxShield,p.shield+actual);tx.emit("shield.recovered",{seat:owner,amount:p.shield-before,sourceRef:ref});}else if(!shield&&p.hp!==null&&p.maxHp!==null){const before=p.hp;p.hp=Math.min(p.maxHp,p.hp+actual);tx.emit("health.recovered",{seat:owner,amount:p.hp-before,sourceRef:ref});}}if(tx.draft.pendingWindows.length||tx.draft.combat.dyingStack.length)tx.draft.cards[ref]!.runtime.finishStatueAfterDying=true;else closeStatue(tx,ref);}
 else if(id==="statue.elf"||id==="statue.rogue"){const rawRange=object(rule.targetRule).range,range=rawRange==="unlimited"?"unlimited":numberValue(rawRange,"STATUE_RANGE_INVALID");if(!input.targetRef||!legalTarget(s,owner,input.targetRef,range))throw new Error("STATUE_TARGET_INVALID");const targets=ownedSelectable(s,seatOf(input.targetRef));if(!targets.length)throw new Error("STATUE_TARGET_HAS_NO_CARD");const handSet=new Set(s.zones[`hand:${seatOf(input.targetRef)}`]!.orderedCardRefs),publicRefs=targets.filter(x=>!handSet.has(x)),hidden=targets.filter(x=>handSet.has(x)),randomSeq=tx.draft.randomSource.nextRandomSeq,shuffled=shuffleWithSource(hidden,tx.draft.randomSource);tx.draft.randomSource=shuffled.source;tx.draft.randomHistory.push({randomSeq,purpose:`${id}.hiddenSelectionOrder`,candidateRefs:hidden,resultRefs:shuffled.value});const legal=[...publicRefs,...shuffled.value];openWindow(tx,"statueCardSelection",owner,input.deadlineAt,legal.map((_,i)=>`offer:statue-card:${i}`),{statueRef:ref,statueFamily:id,targetRef:input.targetRef,legalCardRefs:legal,publicCardRefs:publicRefs,hiddenCardCount:hidden.length});}
 else if(id==="statue.priest"){const order=([0,1,2,3] as const).map(d=>(((owner-1+d)%4)+1) as Seat).filter(n=>inPlay(s,n)),shown=takeTopCardsToResolvingInTransaction(tx,order.length,id).cardRefs;for(const cardRef of shown)tx.draft.cards[cardRef]!.faceUp=true;tx.draft.cards[ref]!.runtime.priestDisplayedRefs=shown;tx.draft.cards[ref]!.runtime.priestRemainingSeats=order as unknown as JsonValue;if(shown.length&&order.length)openPriestChoice(tx,ref,order,shown,input.deadlineAt);else closeStatue(tx,ref);}
 else if(id==="statue.assassin"){const params=effectParams(rule,"createAttack")!,attackType=String(params.attackType),range=params.range==="unlimited"?"unlimited":numberValue(params.range,"STATUE_RANGE_INVALID"),segments=list(params.damageSegments),targets=([1,2,3,4] as Seat[]).filter(n=>n!==owner&&inPlay(s,n)).sort((a,b)=>((a-owner+4)%4)-((b-owner+4)%4));closeStatue(tx,ref,false);if(targets.length)createCompositeScriptedAttackInTransaction(tx,{attackId:`attack:statue-assassin:${ref}:${s.stateRevision+1}`,attackerSeat:owner,sourceRef:ref,weaponId:"statue.assassin.dart",modeId:"dart",range,targetGroups:targets.map(n=>({targetRef:`character:${n}`,attackTypes:[attackType],damageSegments:structuredClone(segments)})),tags:["statueAttack"],preserveTargetOrder:true,resumePlayDeadlineAt:Number(card.runtime.statueResumePlayDeadlineAt??0)});}
 else if(id==="statue.engineer"){const targetRule=object(rule.targetRule),range=targetRule.range==="unlimited"?"unlimited":numberValue(targetRule.range,"STATUE_RANGE_INVALID"),encoded=JSON.stringify(rule.delayedTrigger),damage=effectParams(object(rule.delayedTrigger),"createDamage"),colors=(encoded.match(/"matchedColors":\[([^\]]*)\]/)?.[1]?.match(/"(white|green|blue|orange|red)"/g)??[]).map(x=>x.slice(1,-1));if(!input.targetRef||!legalTarget(s,owner,input.targetRef,range))throw new Error("STATUE_TARGET_INVALID");const draftCard=tx.draft.cards[ref]!;draftCard.runtime.engineerPersistentSourceSeat=owner;draftCard.runtime.engineerMatchedColors=colors;draftCard.runtime.engineerDamageAmount=numberValue(damage?.amount,"STATUE_ENGINEER_DAMAGE_INVALID");delete draftCard.runtime.statueOwnerSeat;delete draftCard.runtime.statueResumePlayDeadlineAt;moveCardInTransaction(tx,{cardRef:ref,toZoneRef:`judgment:${seatOf(input.targetRef)}`,moveKind:"use",faceUp:true});tx.emit("statue.engineer.placed",{cardRef:ref,sourceSeat:owner,targetSeat:seatOf(input.targetRef)});}
 else if(id==="statue.knight"){if(!input.targetRef||!legalTarget(s,owner,input.targetRef,"unlimited"))throw new Error("STATUE_TARGET_INVALID");const target=seatOf(input.targetRef);tx.draft.cards[ref]!.runtime.knightDuelController=owner;tx.draft.cards[ref]!.runtime.knightDuelTarget=target;openKnightDuel(tx,ref,target,owner,input.deadlineAt);}
 else throw new Error("STATUE_RESOLVER_REQUIRES_RESPONSE_FLOW");return commit(tx);
}
function paladinsInHand(s:AuthoritativeGameState,n:Seat){return s.zones[`hand:${n}`]!.orderedCardRefs.filter(x=>family(s.cards[x]!.templateId)==="statue.paladin");}
function nextEligiblePriority(s:AuthoritativeGameState,targetController:Seat,passed:Seat[]){return ([1,2,3,4] as Seat[]).sort((a,b)=>((a-targetController+4)%4)-((b-targetController+4)%4)).find(n=>n!==targetController&&inPlay(s,n)&&!passed.includes(n)&&paladinsInHand(s,n).length>0)??null;}
function openPaladinResponseWindow(tx:EngineTransaction<AuthoritativeGameState>,baseRef:string,stackRefs:string[],targetController:Seat,passed:Seat[],deadlineAt:number){const priority=nextEligiblePriority(tx.draft,targetController,passed);if(!priority)return false;const refs=paladinsInHand(tx.draft,priority),offers=["offer:statue-paladin:pass",...refs.map((_,i)=>`offer:statue-paladin:${i}`)];openWindow(tx,"statuePaladinResponse",priority,deadlineAt,offers,{baseStatueRef:baseRef,stackRefs:stackRefs as unknown as JsonValue,targetController,passedSeats:passed as unknown as JsonValue,paladinCardRefs:refs},false,"pass");return true;}
function openPaladinResponseInTransaction(tx:EngineTransaction<AuthoritativeGameState>,baseRef:string,controller:Seat,input:BeginStatueInput){const eligible=([1,2,3,4] as Seat[]).some(n=>n!==controller&&inPlay(tx.draft,n)&&paladinsInHand(tx.draft,n).length);if(!eligible)return false;const card=tx.draft.cards[baseRef]!;card.runtime.pendingStatueTargetRef=input.targetRef??null;card.runtime.pendingStatueModeId=input.modeId??null;card.runtime.pendingStatueDeadlineAt=input.deadlineAt;return openPaladinResponseWindow(tx,baseRef,[baseRef],controller,[],input.deadlineAt);}
function settlePaladinStack(tx:EngineTransaction<AuthoritativeGameState>,base:string,stack:string[],deadlineAt:number){if(stack.length===1){const baseCard=tx.draft.cards[base]!;baseCard.runtime.paladinResponseChecked=true;baseCard.runtime.resumeStatueResolutionNow=true;return;}const responder=stack.pop()!,target=stack.pop()!;if(tx.draft.cards[responder]?.zoneRef==="resolving")moveCardInTransaction(tx,{cardRef:responder,toZoneRef:"discardPile",moveKind:"discard",faceUp:true});tx.emit("card.effect.resolved",{cardRef:responder,cardId:tx.draft.cards[responder]!.templateId,category:"statue",preventedTargetRef:target});if(target===base)closeStatue(tx,base,true,true);else if(tx.draft.cards[target]?.zoneRef==="resolving"){moveCardInTransaction(tx,{cardRef:target,toZoneRef:"discardPile",moveKind:"discard",faceUp:true});tx.emit("card.effect.prevented",{cardRef:target,cardId:tx.draft.cards[target]!.templateId,category:"statue",reason:"paladinStatue"});}if(stack.length&&tx.draft.cards[base]?.zoneRef==="resolving"&&!openPaladinResponseWindow(tx,base,stack,Number(tx.draft.cards[stack.at(-1)!]!.runtime.paladinControllerSeat??tx.draft.cards[base]!.runtime.statueOwnerSeat) as Seat,[],deadlineAt))settlePaladinStack(tx,base,stack,deadlineAt);}
function openPriestChoice(tx:EngineTransaction<AuthoritativeGameState>,ref:string,seats:Seat[],cards:string[],deadlineAt:number){const seat=seats[0]!,offers=["offer:statue-priest:pass",...cards.map((_,i)=>`offer:statue-priest:${i}`)];openWindow(tx,"statuePriestTake",seat,deadlineAt,offers,{statueRef:ref,remainingSeats:seats as unknown as JsonValue,remainingCardRefs:cards},false,"pass");}
function openKnightDuel(tx:EngineTransaction<AuthoritativeGameState>,ref:string,current:Seat,other:Seat,deadlineAt:number){const kills=tx.draft.zones[`hand:${current}`]!.orderedCardRefs.filter(x=>tx.draft.cards[x]!.templateId.startsWith("basic.kill."));openWindow(tx,"statueKnightDuel",current,deadlineAt,["offer:statue-knight:pass",...kills.map((_,i)=>`offer:statue-knight:kill:${i}`)],{statueRef:ref,currentSeat:current,otherSeat:other,killCardRefs:kills},false,"pass");}

type ChoiceCommand={commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string};
type ChoiceResult={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[]}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
export class StatueChoiceSession{#state:AuthoritativeGameState;#results=new Map<string,ChoiceResult>();constructor(s:AuthoritativeGameState,private r:LoadedRuleset){this.#state=s}get state(){return this.#state}handle(c:ChoiceCommand):ChoiceResult{const prior=this.#results.get(c.commandId);if(prior)return structuredClone(prior);const no=(reasonCode:string,refreshRequired:boolean):ChoiceResult=>({accepted:false,commandId:c.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired});if(c.gameId!==this.#state.gameId)return no("GAME_NOT_FOUND",false);if(c.expectedStateRevision!==this.#state.stateRevision)return no("STALE_REVISION",true);const w=this.#state.pendingWindows.find(x=>x.promptId===c.promptId),actor=this.#state.players.find(x=>x.userId===c.actorUserId);if(!w||!actor||actor.seat!==w.prioritySeat)return no("NOT_YOUR_PRIORITY",false);const oi=w.legalOfferIds.indexOf(c.offerId);if(oi<0)return no("OFFER_EXPIRED",true);const tx=new EngineTransaction(this.#state);tx.draft.pendingWindows=tx.draft.pendingWindows.filter(x=>x.promptId!==w.promptId);const ctx=w.context??{},ref=String(ctx.statueRef),deadline=w.deadlineAt;
 if(w.kind==="statueCardSelection"){const refs=ctx.legalCardRefs as unknown as string[],selected=refs[oi];if(!selected||!ownedSelectable(tx.draft,seatOf(String(ctx.targetRef))).includes(selected))return no("OFFER_EXPIRED",true);moveCardInTransaction(tx,{cardRef:selected,toZoneRef:String(ctx.statueFamily)==="statue.rogue"?`hand:${actor.seat}`:"discardPile",moveKind:String(ctx.statueFamily)==="statue.rogue"?"gain":"dismantle",faceUp:String(ctx.statueFamily)!=="statue.rogue"});tx.emit(String(ctx.statueFamily)==="statue.rogue"?"card.gained":"card.dismantled",{seat:actor.seat,cardRef:selected,sourceRef:ref});closeStatue(tx,ref);}
 else if(w.kind==="statuePriestTake"){const seats=ctx.remainingSeats as unknown as Seat[],cards=ctx.remainingCardRefs as unknown as string[],pass=c.offerId.endsWith(":pass"),selected=pass?null:cards[oi-1];if(selected){moveCardInTransaction(tx,{cardRef:selected,toZoneRef:`hand:${actor.seat}`,moveKind:"gain",faceUp:false});cards.splice(cards.indexOf(selected),1);tx.emit("card.gained",{seat:actor.seat,cardRef:selected,sourceRef:ref});}const remaining=seats.slice(1);if(remaining.length&&cards.length)openPriestChoice(tx,ref,remaining,cards,deadline);else{for(const x of cards)if(tx.draft.cards[x]?.zoneRef==="resolving")moveCardInTransaction(tx,{cardRef:x,toZoneRef:"discardPile",moveKind:"discard",faceUp:true});closeStatue(tx,ref);}}
 else if(w.kind==="statueKnightDuel"){const current=Number(ctx.currentSeat) as Seat,other=Number(ctx.otherSeat) as Seat,kills=ctx.killCardRefs as unknown as string[],pass=c.offerId.endsWith(":pass");if(pass)openKnightWeaponChoice(tx,ref,other,current,deadline,this.r);else{const kill=kills[oi-1];if(!kill||!tx.draft.zones[`hand:${current}`]!.orderedCardRefs.includes(kill))return no("OFFER_EXPIRED",true);moveCardInTransaction(tx,{cardRef:kill,toZoneRef:"discardPile",moveKind:"respond",faceUp:true});tx.emit("card.responded",{seat:current,cardRef:kill,request:"statueKnightDuel"});openKnightDuel(tx,ref,other,current,deadline);}}
 else if(w.kind==="statueKnightWeapon"){const winner=Number(ctx.winnerSeat) as Seat,loser=Number(ctx.loserSeat) as Seat,refs=ctx.weaponRefs as unknown as string[],pass=c.offerId.endsWith(":pass");if(pass)closeStatue(tx,ref);else{const weaponRef=refs[oi-1];if(!weaponRef)return no("OFFER_EXPIRED",true);const card=tx.draft.cards[weaponRef],zoneRef=card?.zoneRef;if(!card||!zoneRef||!tx.draft.zones[zoneRef]?.orderedCardRefs.includes(weaponRef))return no("OFFER_EXPIRED",true);const shadow=structuredClone(tx.draft);shadow.preselection[winner]={weaponSlot:zoneRef,modeId:null};for(const key of Object.keys(shadow.cards[weaponRef]!.runtime))if(key.toLowerCase().includes("charge"))shadow.cards[weaponRef]!.runtime[key]=0;let source;try{source=resolvePreselectedAttackSource(shadow,winner,this.r);}catch{return no("STATUE_KNIGHT_WEAPON_MODE_UNRESOLVED",true);}const resumeDeadline=Number(tx.draft.cards[ref]!.runtime.statueResumePlayDeadlineAt??0);closeStatue(tx,ref,false);createScriptedAttackInTransaction(tx,{attackId:`attack:statue-knight:${ref}:${tx.draft.stateRevision+1}`,attackerSeat:winner,targetRef:`character:${loser}`,sourceRef:weaponRef,weaponId:source.weaponId!,modeId:source.mode.modeId,range:source.mode.range,attackTypes:source.mode.attackTypes,damageSegments:source.mode.damageSegments as unknown as JsonValue[],cannotMeleeBlock:true,ignoreArmor:true,tags:["statueAttack","cannotDodge"],resumePlayDeadlineAt:resumeDeadline});const attack=tx.draft.combat.attack as RecordValue;attack.responsePolicy="noDodge";}}
 else if(w.kind==="statuePaladinResponse"){const base=String(ctx.baseStatueRef),stack=[...(ctx.stackRefs as unknown as string[])],targetController=Number(ctx.targetController) as Seat,passed=[...(ctx.passedSeats as unknown as Seat[])],refs=ctx.paladinCardRefs as unknown as string[],pass=c.offerId.endsWith(":pass");if(!pass){const selected=refs[oi-1];if(!selected||!tx.draft.zones[`hand:${actor.seat}`]!.orderedCardRefs.includes(selected))return no("OFFER_EXPIRED",true);moveCardInTransaction(tx,{cardRef:selected,toZoneRef:"resolving",moveKind:"respond",faceUp:true});tx.draft.cards[selected]!.runtime.statueOwnerSeat=actor.seat;tx.draft.cards[selected]!.runtime.paladinControllerSeat=actor.seat;stack.push(selected);tx.emit("card.responded",{seat:actor.seat,cardRef:selected,cardId:tx.draft.cards[selected]!.templateId,responseTo:stack.at(-2)??null,category:"statue"});if(!openPaladinResponseWindow(tx,base,stack,actor.seat,[],deadline))settlePaladinStack(tx,base,stack,deadline);}else{passed.push(actor.seat);if(!openPaladinResponseWindow(tx,base,stack,targetController,passed,deadline))settlePaladinStack(tx,base,stack,deadline);}}
 else return no("STATUE_WINDOW_UNSUPPORTED",false);let out=commit(tx),events=[...out.events];const baseRef=Object.values(out.state.cards).find(x=>x.runtime.resumeStatueResolutionNow===true)?.cardRef;if(baseRef){const pending=out.state.cards[baseRef]!.runtime;delete pending.resumeStatueResolutionNow;const targetRef=typeof pending.pendingStatueTargetRef==="string"?pending.pendingStatueTargetRef:null,modeId=typeof pending.pendingStatueModeId==="string"?pending.pendingStatueModeId:null,deadlineAt=Number(pending.pendingStatueDeadlineAt??deadline),resumeInput:BeginStatueInput={deadlineAt,...(targetRef?{targetRef}:{}),...(modeId?{modeId}:{})};const resumed=beginStatueResolution(out.state,this.r,baseRef,resumeInput);out={previousRevision:out.previousRevision,state:resumed.state,events:[...events,...resumed.events]};events=out.events;}this.#state=out.state;const result:ChoiceResult={accepted:true,commandId:c.commandId,previousRevision:out.previousRevision,stateRevision:out.state.stateRevision,events};this.#results.set(c.commandId,result);return structuredClone(result);}handleTimeout(commandId:string){const w=this.#state.pendingWindows[0];if(!w)throw new Error("PROMPT_CLOSED");const pass=w.legalOfferIds.find(x=>x.endsWith(":pass")),offerId=pass??w.legalOfferIds[0]!;return this.handle({commandId,gameId:this.#state.gameId,expectedStateRevision:this.#state.stateRevision,actorUserId:player(this.#state,w.prioritySeat).userId,promptId:w.promptId,offerId});}}
function openKnightWeaponChoice(tx:EngineTransaction<AuthoritativeGameState>,ref:string,winner:Seat,loser:Seat,deadlineAt:number,r:LoadedRuleset){const enabled=player(tx.draft,winner).markers.equipmentEffectsDisabled!==true&&!player(tx.draft,winner).statuses.some(x=>x.statusId==="status.equipmentDisabled"),refs=enabled?[`weapon:1:${winner}`,`weapon:2:${winner}`,`weapon:3:${winner}`,`thirdWeapon:${winner}`].flatMap(z=>tx.draft.zones[z]?.orderedCardRefs??[]):[];const legal=refs.filter(x=>{const copy=structuredClone(tx.draft),z=copy.cards[x]!.zoneRef;copy.preselection[winner]={weaponSlot:z,modeId:null};for(const key of Object.keys(copy.cards[x]!.runtime))if(key.toLowerCase().includes("charge"))copy.cards[x]!.runtime[key]=0;try{resolvePreselectedAttackSource(copy,winner,r);return true;}catch{return false;}});openWindow(tx,"statueKnightWeapon",winner,deadlineAt,["offer:statue-knight:pass",...legal.map((_,i)=>`offer:statue-knight:weapon:${i}`)],{statueRef:ref,winnerSeat:winner,loserSeat:loser,weaponRefs:legal},false,"pass");}
export function resumeStatueAfterDying(s:AuthoritativeGameState,ref:string){const card=s.cards[ref];if(!card||card.runtime.finishStatueAfterDying!==true||s.combat.dyingStack.length||s.pendingWindows.length)return null;const tx=new EngineTransaction(s);delete tx.draft.cards[ref]!.runtime.finishStatueAfterDying;closeStatue(tx,ref);return commit(tx);}
export function openEngineerStatueAtJudgment(tx:EngineTransaction<AuthoritativeGameState>,r:LoadedRuleset,seat:Seat,deadlineAt:number){const candidate=tx.draft.zones[`judgment:${seat}`]!.orderedCardRefs[0],card=candidate?tx.draft.cards[candidate]:undefined;if(!card||!candidate||family(card.templateId)!=="statue.engineer")return false;const ref:string=candidate,colors=(Array.isArray(card.runtime.engineerMatchedColors)?card.runtime.engineerMatchedColors:["green"]) as import("./judgment.js").PrintedColor[];beginJudgmentInTransaction(tx,r,{controllerSeat:seat,sourceRef:ref,purpose:"engineerStatue",matchColors:colors,context:{engineerStatue:true,engineerStatueRef:ref,engineerHolderSeat:seat,engineerSourceSeat:Number(card.runtime.engineerPersistentSourceSeat),engineerDamageAmount:Number(card.runtime.engineerDamageAmount)}},deadlineAt);tx.draft.phaseBodyResolved=true;tx.emit("effect.execution.before",{familyId:"statue.engineer",cardRef:ref,sourceSeat:Number(card.runtime.engineerPersistentSourceSeat),targetSeat:seat,phase:"judgment"});return true;}
