import {resolve} from "node:path";import {beforeAll,describe,expect,it} from "vitest";import {loadFrozenRuleset} from "../ruleset/loadRuleset.js";import type {LoadedRuleset} from "../ruleset/types.js";import {createInitialSetup,resolveInitialRedraw} from "./setup.js";import {advanceTimeline} from "./timeline.js";
import {addDrawCountModifierInTransaction,drawCountModifiers} from "./drawCount.js";import {EngineTransaction} from "./transaction.js";
let ruleset:LoadedRuleset;const users={1:"u1",2:"u2",3:"u3",4:"u4"} as const,characters={1:"character.knight",2:"character.alchemist",3:"character.ranger",4:"character.wizard"} as const;
beforeAll(async()=>{ruleset=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"));});
function started(firstSeat:1|2|3|4=1){let state=createInitialSetup(ruleset,{gameId:"g",firstSeat,seed:3,usersBySeat:users,characterIdsBySeat:characters});for(const seat of [1,2,3,4] as const)state=resolveInitialRedraw(state,seat,false,ruleset).state;state.phaseBodyResolved=true;return state;}
function equipBoss(state:ReturnType<typeof started>,seat:1|2|3|4,id:string){const card=Object.values(state.cards).find(item=>item.templateId===id)!,from=state.zones[card.zoneRef]!,to=state.zones[`boss:${seat}`]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(card.cardRef),1);to.orderedCardRefs.push(card.cardRef);card.zoneRef=to.zoneRef;card.ownerSeat=seat;card.controllerSeat=seat;card.faceUp=true;return card;}
describe("turn and phase timeline",()=>{
 it("advances through the standard phase order",()=>{let state=started();for(const expected of ["judgment","draw","play","discard","end"] as const){const result=advanceTimeline(state);state=result.state;expect(state.phase).toBe(expected);expect(state.phaseBoundary).toBe("body");expect(result.events.map(event=>event.eventType)).toContain("phase.before");state.phaseBodyResolved=true;}expect(state.phaseMode).toBe("automatic");});
 it("records skipped phases without start/body/end",()=>{const result=advanceTimeline(started(),{kind:"skip",reason:"status.test"});expect(result.state).toMatchObject({phase:"judgment",phaseBoundary:"after"});expect(result.events.map(event=>event.eventType)).toEqual(["phase.end.before","phase.end","phase.after","phase.before","phase.skip","phase.after"]);const resumed=advanceTimeline(result.state);expect(resumed.state).toMatchObject({phase:"draw",phaseBoundary:"body"});});
 it("consumes one-shot draw modifiers when the affected draw phase is skipped",()=>{let state=started();state.phase="judgment";state.phaseBoundary="body";state.phaseBodyResolved=true;const tx=new EngineTransaction(state);addDrawCountModifierInTransaction(tx,{seat:1,modifierId:"test:skip",delta:-1,remainingAffectedDraws:1});const added=tx.commit();added.state.history.domainEvents.push(...added.events);state=added.state;const result=advanceTimeline(state,{kind:"skip",reason:"status.electrified"});expect(result.state).toMatchObject({phase:"draw",phaseBoundary:"after"});expect(drawCountModifiers(result.state,1)).toHaveLength(0);expect(result.events.find(event=>event.eventType==="draw.modifier.consumed")?.payload).toMatchObject({modifierId:"test:skip",boundary:"skipped"});});
 it("skips eliminated turn owners and increments round across first seat",()=>{let state=started(1);state.activeSeat=4;state.phase="end";state.phaseBoundary="body";state.phaseMode="automatic";state.players.find(player=>player.seat===1)!.lifeState="eliminated";const result=advanceTimeline(state);expect(result.state).toMatchObject({activeSeat:2,phase:"prepare",round:2});});
 it("refuses to advance across a live window",()=>{const state=started();state.pendingWindows.push({promptId:"p",kind:"test",prioritySeat:1,mandatory:false,deadlineAt:1,timeoutPolicy:"pass",legalOfferIds:[]});expect(()=>advanceTimeline(state)).toThrow("TIMELINE_NOT_STABLE");});
 it("counts Iron Pirate's later own turns and eliminates at the second end-phase start",()=>{let state=started();const boss=equipBoss(state,1,"boss.iron_pirate_king"),owner=state.players[0]!;owner.lifeState="deadNotEliminated";owner.hp=null;owner.shield=null;state.activeSeat=4;state.phase="end";state.phaseBoundary="body";state.phaseMode="automatic";state.phaseBodyResolved=true;state=advanceTimeline(state).state;expect(state).toMatchObject({activeSeat:1,phase:"prepare"});expect(state.cards[boss.cardRef]!.runtime.postDeathOwnTurnCount).toBe(1);state.cards[boss.cardRef]!.runtime.postDeathOwnTurnCount=2;state.phase="discard";state.phaseBoundary="body";state.phaseMode="manual";state.phaseBodyResolved=true;const eliminated=advanceTimeline(state);expect(eliminated.state.players[0]!.lifeState).toBe("eliminated");expect(eliminated.state.phase).toBe("end");expect(eliminated.events.find(event=>event.eventType==="elimination.occurred")?.payload).toMatchObject({reason:"ironPirateTwoTurnsElapsed"});});
 it("decreases Traveler's health floor only at the start of their own end phase",()=>{let state=started(),traveler=state.players[0]!;traveler.characterId="character.interdimensional_traveler";traveler.initialTalentIds=["talent.parallel_traversal"];traveler.markers.healthFloor=3;state.activeSeat=2;state.phase="discard";state.phaseBoundary="body";state.phaseMode="manual";state.phaseBodyResolved=true;state=advanceTimeline(state).state;expect(traveler.markers.healthFloor).toBe(3);expect(state.players[0]!.markers.healthFloor).toBe(3);state.activeSeat=1;state.phase="discard";state.phaseBoundary="body";state.phaseMode="manual";state.phaseBodyResolved=true;const own=advanceTimeline(state);expect(own.state.players[0]!.markers.healthFloor).toBe(2);expect(own.events.find(event=>event.eventType==="value.changed")?.payload).toMatchObject({path:"healthFloor",from:3,to:2});});
});
