import{resolve}from"node:path";import{beforeAll,describe,expect,it}from"vitest";import{loadFrozenRuleset}from"../ruleset/loadRuleset.js";import type{LoadedRuleset}from"../ruleset/types.js";import{createInitialSetup,resolveInitialRedraw}from"./setup.js";import type{AuthoritativeGameState}from"./state.js";import{buildWeaponEquipOffers,WeaponDiscardSession,WeaponEquipSession}from"./weaponEquipment.js";
let r:LoadedRuleset;beforeAll(async()=>{r=await loadFrozenRuleset(resolve(import.meta.dirname,"../../../rulesets/v1.3.4"))});
function ready(){let s=createInitialSetup(r,{gameId:"weapon-equipment",firstSeat:1,seed:4101,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.knight",2:"character.ranger",3:"character.wizard",4:"character.druid"}});for(const n of[1,2,3,4]as const)s=resolveInitialRedraw(s,n,false,r).state;Object.assign(s,{activeSeat:1,phase:"play",phaseBoundary:"body",phaseMode:"manual",phaseBodyResolved:false});s.pendingWindows=[{promptId:"play",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];return s}
function move(s:AuthoritativeGameState,id:string,to:string){const c=Object.values(s.cards).find(x=>x.templateId===id)!,from=s.zones[c.zoneRef]!;from.orderedCardRefs.splice(from.orderedCardRefs.indexOf(c.cardRef),1);s.zones[to]!.orderedCardRefs.push(c.cardRef);Object.assign(c,{zoneRef:to,ownerSeat:s.zones[to]!.ownerSeat,controllerSeat:s.zones[to]!.ownerSeat,faceUp:!to.startsWith("hand:")});return c.cardRef}
const command=(s:AuthoritativeGameState,offerId:string,cardRef:string,id:string)=>({commandId:id,gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:"u1",promptId:"play",offerId,cardRef});
describe("weapon equipment lifecycle",()=>{
 it("equips and replaces a regular weapon through authoritative offers",()=>{let s=ready(),first=move(s,"weapon.w01","hand:1"),second=move(s,"weapon.w02","hand:1"),session=new WeaponEquipSession(s,r),offer=buildWeaponEquipOffers(s,r,1).find(x=>x.cardRef===first&&x.toZoneRef==="weapon:1:1")!;expect(session.handle(command(s,offer.offerId,first,"first")).accepted).toBe(true);s=session.state;session=new WeaponEquipSession(s,r);offer=buildWeaponEquipOffers(s,r,1).find(x=>x.cardRef===second&&x.toZoneRef==="weapon:1:1")!;expect(offer.replacedCardRef).toBe(first);expect(session.handle(command(s,offer.offerId,second,"replace")).accepted).toBe(true);expect(session.state.cards[first]!.zoneRef).toBe("discardPile");expect(session.state.cards[second]!.zoneRef).toBe("weapon:1:1");expect(session.state.history.domainEvents.some(e=>e.eventType==="card.lost")).toBe(true)});
 it("routes a third weapon only to its independent slot",()=>{const s=ready(),ref=move(s,"weapon.w14","hand:1"),offers=buildWeaponEquipOffers(s,r,1).filter(x=>x.cardRef===ref);expect(offers.map(x=>x.toZoneRef)).toEqual(["thirdWeapon:1"])});
 it("actively discards and redirects a synthesized weapon outside the deck",()=>{let s=ready(),ref=move(s,"weapon.w01","weapon:1:1");s.cards[ref]!.runtime.generatedExitZoneRef="outsideDeck";const session=new WeaponDiscardSession(s),offerId=`offer:weapon-discard:${ref}`;expect(session.handle(command(s,offerId,ref,"discard")).accepted).toBe(true);expect(session.state.cards[ref]!.zoneRef).toBe("outsideDeck")});
});
