import type { LoadedRuleset } from "../ruleset/types.js";
import { copyTemporaryCardToHandInTransaction } from "./generatedCards.js";
import type { AuthoritativeGameState, Seat } from "./state.js";
import { validateAuthoritativeState } from "./stateValidation.js";
import { EngineTransaction } from "./transaction.js";
import type { DomainEvent } from "./types.js";
import { moveCardInTransaction } from "./zoneMovement.js";

interface RecipeInput { templateId:string; count:number }
interface Recipe { recipeId:string; inputs:RecipeInput[]; outputTemplateId:string; window:string; inputZones:string[]; inputMoveKind:string; inputsDestination:string; outputZone:string; generatedInstanceExitZone:string }
interface Document { synthesisRecipes:Recipe[] }
const document=(r:LoadedRuleset)=>r.documents.get("weapon-rules.json") as unknown as Document;
const equipmentTypes=new Set(["weaponSlot","thirdWeaponSlot","armorSlot","mountOffenseSlot","mountDefenseSlot","talentZone"]);
function eligibleRefs(s:AuthoritativeGameState,seat:Seat){return Object.values(s.zones).filter(z=>z.ownerSeat===seat&&(z.zoneType==="hand"||equipmentTypes.has(z.zoneType))).flatMap(z=>z.orderedCardRefs)}
function validateRecipe(recipe:Recipe){if(recipe.window!=="owner.phase.play"||JSON.stringify(recipe.inputZones)!==JSON.stringify(["hand","equipment"])||recipe.inputMoveKind!=="synthesizeConsume"||recipe.inputsDestination!=="discardPile"||recipe.outputZone!=="hand"||recipe.generatedInstanceExitZone!=="outsideDeck"||!recipe.inputs.length||recipe.inputs.some(x=>!Number.isInteger(x.count)||x.count<1))throw new Error("WEAPON_SYNTHESIS_RULE_INVALID")}
export interface WeaponSynthesisOffer{offerId:string;recipeId:string;outputTemplateId:string;requirements:RecipeInput[];legalCardRefs:string[];requiredCardCount:number}
export function buildWeaponSynthesisOffers(s:AuthoritativeGameState,r:LoadedRuleset,seat:Seat):WeaponSynthesisOffer[]{if(s.lifecycle!=="inProgress"||s.activeSeat!==seat||s.phase!=="play"||s.phaseBoundary!=="body"||s.combat.attack||!s.pendingWindows.some(w=>w.kind==="playPhaseAction"&&w.prioritySeat===seat))return[];const refs=eligibleRefs(s,seat);return document(r).synthesisRecipes.flatMap(recipe=>{validateRecipe(recipe);const available=recipe.inputs.every(input=>refs.filter(ref=>s.cards[ref]?.templateId===input.templateId).length>=input.count);return available?[{offerId:`offer:weapon-synthesis:${recipe.recipeId}:${s.stateRevision}`,recipeId:recipe.recipeId,outputTemplateId:recipe.outputTemplateId,requirements:structuredClone(recipe.inputs),legalCardRefs:refs.filter(ref=>recipe.inputs.some(x=>x.templateId===s.cards[ref]?.templateId)),requiredCardCount:recipe.inputs.reduce((n,x)=>n+x.count,0)}]:[]})}
export interface WeaponSynthesisCommand{commandId:string;gameId:string;expectedStateRevision:number;actorUserId:string;promptId:string;offerId:string;cardRefs:string[]}
export type WeaponSynthesisResult={accepted:true;commandId:string;previousRevision:number;stateRevision:number;events:DomainEvent[];productCardRef:string}|{accepted:false;commandId:string;stateRevision:number;reasonCode:string;refreshRequired:boolean};
export class WeaponSynthesisSession{#state:AuthoritativeGameState;#results=new Map<string,WeaponSynthesisResult>();constructor(s:AuthoritativeGameState,private r:LoadedRuleset){this.#state=s}get state(){return this.#state}handle(c:WeaponSynthesisCommand):WeaponSynthesisResult{const old=this.#results.get(c.commandId);if(old)return structuredClone(old);const reject=(reasonCode:string,refreshRequired:boolean):WeaponSynthesisResult=>{const x={accepted:false as const,commandId:c.commandId,stateRevision:this.#state.stateRevision,reasonCode,refreshRequired};this.#results.set(c.commandId,x);return structuredClone(x)};if(c.gameId!==this.#state.gameId)return reject("GAME_NOT_FOUND",false);if(c.expectedStateRevision!==this.#state.stateRevision)return reject("STALE_REVISION",true);const actor=this.#state.players.find(p=>p.userId===c.actorUserId),window=actor?this.#state.pendingWindows.find(w=>w.promptId===c.promptId&&w.kind==="playPhaseAction"&&w.prioritySeat===actor.seat):undefined;if(!actor||!window)return reject("NOT_YOUR_PRIORITY",false);const offer=buildWeaponSynthesisOffers(this.#state,this.r,actor.seat).find(x=>x.offerId===c.offerId);if(!offer)return reject("OFFER_EXPIRED",true);if(c.cardRefs.length!==offer.requiredCardCount||new Set(c.cardRefs).size!==c.cardRefs.length)return reject("SYNTHESIS_INPUT_INVALID",false);const eligible=new Set(eligibleRefs(this.#state,actor.seat));if(c.cardRefs.some(ref=>!eligible.has(ref)))return reject("SYNTHESIS_INPUT_NO_LONGER_LEGAL",true);for(const requirement of offer.requirements)if(c.cardRefs.filter(ref=>this.#state.cards[ref]?.templateId===requirement.templateId).length!==requirement.count)return reject("SYNTHESIS_INPUT_INVALID",false);if(c.cardRefs.some(ref=>!offer.requirements.some(x=>x.templateId===this.#state.cards[ref]?.templateId)))return reject("SYNTHESIS_INPUT_INVALID",false);const recipe=document(this.r).synthesisRecipes.find(x=>x.recipeId===offer.recipeId)!;validateRecipe(recipe);const tx=new EngineTransaction(this.#state);for(const ref of c.cardRefs)moveCardInTransaction(tx,{cardRef:ref,toZoneRef:"discardPile",moveKind:"synthesizeConsume",faceUp:true});const productCardRef=copyTemporaryCardToHandInTransaction(tx,{templateId:recipe.outputTemplateId,ownerSeat:actor.seat,sourceRef:recipe.recipeId,generatedBy:recipe.recipeId,exitZoneRef:"outsideDeck"});tx.emit("card.synthesized",{seat:actor.seat,recipeId:recipe.recipeId,inputCardRefs:c.cardRefs,outputTemplateId:recipe.outputTemplateId,productCardRef,inputMoveKind:"synthesizeConsume",outputZone:`hand:${actor.seat}`,generatedInstanceExitZone:"outsideDeck"});const out=tx.commit();out.state.history.domainEvents.push(...out.events);validateAuthoritativeState(out.state);this.#state=out.state;const result={accepted:true as const,commandId:c.commandId,previousRevision:out.previousRevision,stateRevision:out.state.stateRevision,events:out.events,productCardRef};this.#results.set(c.commandId,result);return structuredClone(result)}}
