import { resolve } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { loadFrozenRuleset } from "../ruleset/loadRuleset.js";
import type { LoadedRuleset } from "../ruleset/types.js";
import { activateAnubisProjectiles } from "./anubisWeapon.js";
import { commitAttack, buildAttackOffer, resolvePreselectedAttackSource } from "./attack.js";
import { runCombatUntilBlocked } from "./combatScheduler.js";
import { aimLaserFish, cancelLaserFishAim, consumeLaserFishAttackCount } from "./laserFishWeapon.js";
import { activateMeteorWeapon } from "./meteorWeapon.js";
import { setWeaponPreselection } from "./preselection.js";
import { AttackResponseSession } from "./response.js";
import { createInitialSetup, resolveInitialRedraw } from "./setup.js";
import type { AuthoritativeGameState, Seat } from "./state.js";
import { TemporaryCoinSession } from "./coinGun.js";
import { WrenchChoiceSession } from "./wrenchWeapon.js";
import { applyStatus } from "./status.js";

let ruleset: LoadedRuleset;
beforeAll(async () => { ruleset = await loadFrozenRuleset(resolve(import.meta.dirname, "../../../rulesets/v1.3.4")); });
function move(s:AuthoritativeGameState,ref:string,to:string){const c=s.cards[ref]!,z=s.zones[c.zoneRef]!,i=z.orderedCardRefs.indexOf(ref);if(i>=0)z.orderedCardRefs.splice(i,1);s.zones[to]!.orderedCardRefs.push(ref);Object.assign(c,{zoneRef:to,ownerSeat:s.zones[to]!.ownerSeat,controllerSeat:s.zones[to]!.ownerSeat,faceUp:true});}
function ready(id:string){let s=createInitialSetup(ruleset,{gameId:`remaining-${id}`,firstSeat:1,seed:91,usersBySeat:{1:"u1",2:"u2",3:"u3",4:"u4"},characterIdsBySeat:{1:"character.knight",2:"character.wizard",3:"character.ranger",4:"character.alchemist"}});for(const n of [1,2,3,4] as Seat[])s=resolveInitialRedraw(s,n,false,ruleset).state;Object.assign(s,{lifecycle:"inProgress",phase:"play",phaseBoundary:"body",phaseMode:"manual",activeSeat:1});s.players[0]!.limits.attackCountRemaining=8;const card=Object.values(s.cards).find(c=>c.templateId===id)??Object.values(s.cards).find(c=>c.templateId==="weapon.w01")!;card.templateId=id;move(s,card.cardRef,"weapon:1:1");s=setWeaponPreselection(s,1,"weapon:1:1",null,ruleset).state;const kill=Object.values(s.cards).find(c=>c.templateId.startsWith("basic.kill."))!;move(s,kill.cardRef,"hand:1");s.pendingWindows=[{promptId:"play",kind:"playPhaseAction",prioritySeat:1,mandatory:false,deadlineAt:900,timeoutPolicy:"pass",legalOfferIds:["offer:playPhaseAction:finish"],context:{}}];return{s,weaponRef:card.cardRef,killRef:kill.cardRef};}
function pass(s:AuthoritativeGameState){const w=s.pendingWindows[0]!,session=new AttackResponseSession(s);session.handle({commandId:`pass-${s.stateRevision}`,gameId:s.gameId,expectedStateRevision:s.stateRevision,actorUserId:`u${w.prioritySeat}`,promptId:w.promptId,offerId:w.legalOfferIds.find(x=>x.includes(":pass:"))!});return session.state;}

describe("remaining special weapons",()=>{
 it("W54 coin mode consumes a coin resource instead of Kill/count",()=>{const x=ready("weapon.w54"),coin=Object.values(x.s.cards).find(c=>c.templateId==="basic.coin.white")??Object.values(x.s.cards).find(c=>c.templateId.startsWith("basic."))!;coin.templateId="basic.coin.white";move(x.s,coin.cardRef,"hand:1");x.s=setWeaponPreselection(x.s,1,"weapon:1:1","coin",ruleset).state;const before=x.s.players[0]!.limits.attackCountRemaining;x.s=commitAttack(x.s,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[],resourceCardRefs:[coin.cardRef]}).state;expect(x.s.players[0]!.limits.attackCountRemaining).toBe(before);expect(x.s.cards[coin.cardRef]!.zoneRef).toBe("resolving");});
 it("W58 pays once, targets every in-play character, and starts cooldown",()=>{const x=ready("weapon.w58"),out=activateMeteorWeapon(x.s,1,x.killRef);expect(out.state.combat.targetQueue).toEqual(["character:1","character:2","character:3","character:4"]);expect(out.state.cards[x.weaponRef]!.runtime.cooldownRemaining).toBe(2);});
 it("W61 repeats by current durability and opens optional replacement after a hit",()=>{const x=ready("weapon.w61");x.s.cards[x.weaponRef]!.runtime.durabilityCurrent=2;expect(buildAttackOffer(x.s,1,ruleset).source.mode.damageSegments[0]!.repeat).toBe(2);x.s=commitAttack(x.s,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[x.killRef]}).state;let run=runCombatUntilBlocked(x.s,ruleset,()=>900);x.s=pass(run.state);run=runCombatUntilBlocked(x.s,ruleset,()=>900);expect(run.state.pendingWindows[0]?.kind).toBe("weaponW61Choice");const w=run.state.pendingWindows[0]!,session=new WrenchChoiceSession(run.state);session.handle({commandId:"dismantle",gameId:run.state.gameId,expectedStateRevision:run.state.stateRevision,actorUserId:"u1",promptId:w.promptId,offerId:"offer:w61:dismantle"});expect(session.state.cards[x.weaponRef]!.runtime.durabilityCurrent).toBe(1);expect((session.state.combat.attack as any).damageSegments).toEqual([]);});
 it("W64 aim consumes one count without attacking, then converts later count into locked attack",()=>{const x=ready("weapon.w64");x.s=aimLaserFish(x.s,1,2,x.killRef).state;expect(x.s.cards[x.weaponRef]!.runtime.aimTarget).toBe("character:2");expect(x.s.combat.attack).toBeNull();const out=consumeLaserFishAttackCount(x.s,1)!;expect((out.state.combat.attack as any).weaponId).toBe("weapon.w64");});
 it("W66 creates a zone-less immediate coin choice on its hit",()=>{const x=ready("weapon.w66");x.s=commitAttack(x.s,ruleset,{attackerSeat:1,targetRefs:["character:2"],killCardRefs:[x.killRef]}).state;let run=runCombatUntilBlocked(x.s,ruleset,()=>900);expect(run.state.pendingWindows[0]?.kind).toBe("temporaryCoinImmediateUse");const w=run.state.pendingWindows[0]!,session=new TemporaryCoinSession(run.state);expect(session.handle({commandId:"pass",gameId:run.state.gameId,expectedStateRevision:run.state.stateRevision,actorUserId:"u2",promptId:w.promptId,offerId:"offer:temporary-coin:pass"}).accepted).toBe(true);});
 it("W56 commits independent projectile attacks and records a shared batch",()=>{const x=ready("weapon.w56"),out=activateAnubisProjectiles(x.s,ruleset,1,["character:2","character:2"],x.killRef);expect((out.state.combat.attack as any).anubisProjectile).toBe(true);expect((out.state.combat.attack as any).afterAttackQueue).toHaveLength(1);expect(out.state.cards[x.weaponRef]!.runtime.anubisBatch).toBeTruthy();});
 it("Anubis curse immediately replaces equipped-weapon attack resolution with the temporary pistol",()=>{const x=ready("weapon.w56"),cursed=applyStatus(x.s,ruleset,{ownerSeat:1,statusId:"status.anubisCurse",sourceRef:x.weaponRef}).state;expect(resolvePreselectedAttackSource(cursed,1,ruleset)).toMatchObject({kind:"weapon",weaponId:"weapon.w32"});expect(cursed.durations.some(d=>d.expiryPoint==="target.nextPhase.prepare.before")).toBe(true);});
});
